# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelDrsChecksum")

model_instance <- OrgSagebionetworksRepoModelDrsChecksum$new()

test_that("checksum", {
  # tests for the property `checksum` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`checksum`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})
