# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelDiscussionMessageURL")

model_instance <- OrgSagebionetworksRepoModelDiscussionMessageURL$new()

test_that("messageUrl", {
  # tests for the property `messageUrl` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`messageUrl`, "EXPECTED_RESULT")
})
