# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AccessApprovalNotification")

model.instance <- AccessApprovalNotification$new()

test_that("notificationType", {
  # tests for the property `notificationType` (NotificationType)

  # uncomment below to test the property 
  #expect_equal(model.instance$`notificationType`, "EXPECTED_RESULT")
})

test_that("recipientId", {
  # tests for the property `recipientId` (numeric)
  # The id of the recipient.

  # uncomment below to test the property 
  #expect_equal(model.instance$`recipientId`, "EXPECTED_RESULT")
})

test_that("requirementId", {
  # tests for the property `requirementId` (numeric)
  # The id of the access requirement.

  # uncomment below to test the property 
  #expect_equal(model.instance$`requirementId`, "EXPECTED_RESULT")
})

test_that("sentOn", {
  # tests for the property `sentOn` (character)
  # When the notification was sent.

  # uncomment below to test the property 
  #expect_equal(model.instance$`sentOn`, "EXPECTED_RESULT")
})

