# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelQuizResponseCorrectness")

model_instance <- OrgSagebionetworksRepoModelQuizResponseCorrectness$new()

test_that("question", {
  # tests for the property `question` (OrgSagebionetworksRepoModelQuizQuestion)

  # uncomment below to test the property
  #expect_equal(model.instance$`question`, "EXPECTED_RESULT")
})

test_that("response", {
  # tests for the property `response` (OrgSagebionetworksRepoModelQuizQuestionResponse)

  # uncomment below to test the property
  #expect_equal(model.instance$`response`, "EXPECTED_RESULT")
})

test_that("isCorrect", {
  # tests for the property `isCorrect` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isCorrect`, "EXPECTED_RESULT")
})
