# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelTableTextMatchesQueryFilter")

model_instance <- OrgSagebionetworksRepoModelTableTextMatchesQueryFilter$new()

test_that("concreteType", {
  # tests for the property `concreteType` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`concreteType`, "EXPECTED_RESULT")
})

test_that("isDefiningCondition", {
  # tests for the property `isDefiningCondition` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isDefiningCondition`, "EXPECTED_RESULT")
})

test_that("searchExpression", {
  # tests for the property `searchExpression` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`searchExpression`, "EXPECTED_RESULT")
})
