# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelDataaccessSubmissionPageRequest")

model_instance <- OrgSagebionetworksRepoModelDataaccessSubmissionPageRequest$new()

test_that("accessRequirementId", {
  # tests for the property `accessRequirementId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`accessRequirementId`, "EXPECTED_RESULT")
})

test_that("nextPageToken", {
  # tests for the property `nextPageToken` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`nextPageToken`, "EXPECTED_RESULT")
})

test_that("filterBy", {
  # tests for the property `filterBy` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`filterBy`, "EXPECTED_RESULT")
})

test_that("accessorId", {
  # tests for the property `accessorId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`accessorId`, "EXPECTED_RESULT")
})

test_that("orderBy", {
  # tests for the property `orderBy` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`orderBy`, "EXPECTED_RESULT")
})

test_that("isAscending", {
  # tests for the property `isAscending` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isAscending`, "EXPECTED_RESULT")
})
