# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BatchAccessApprovalInfoResponse")

model.instance <- BatchAccessApprovalInfoResponse$new()

test_that("results", {
  # tests for the property `results` (array[AccessApprovalInfo])
  # The list of resulting AccessApprovalInfo.

  # uncomment below to test the property 
  #expect_equal(model.instance$`results`, "EXPECTED_RESULT")
})

