# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test EntityBundleCreateV2")

model.instance <- EntityBundleCreateV2$new()

test_that("accessControlList", {
  # tests for the property `accessControlList` (AccessControlList)

  # uncomment below to test the property 
  #expect_equal(model.instance$`accessControlList`, "EXPECTED_RESULT")
})

test_that("annotations", {
  # tests for the property `annotations` (AnnotationsV2)

  # uncomment below to test the property 
  #expect_equal(model.instance$`annotations`, "EXPECTED_RESULT")
})

test_that("entity", {
  # tests for the property `entity` (Entity)

  # uncomment below to test the property 
  #expect_equal(model.instance$`entity`, "EXPECTED_RESULT")
})

