# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ListResponse")

model.instance <- ListResponse$new()

test_that("nextPageToken", {
  # tests for the property `nextPageToken` (character)
  # The results are automatically paginated. If another page of results exists then a nextPageToken will be provided. Forward the provided nextPageTokens in a subsequent list request to get the next page. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`nextPageToken`, "EXPECTED_RESULT")
})

test_that("page", {
  # tests for the property `page` (array[FormData])
  # A single page of results matching the request.

  # uncomment below to test the property 
  #expect_equal(model.instance$`page`, "EXPECTED_RESULT")
})

