# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test CreateDiscussionReply")

model.instance <- CreateDiscussionReply$new()

test_that("messageMarkdown", {
  # tests for the property `messageMarkdown` (character)
  # The markdown of the Reply&#39;s message 

  # uncomment below to test the property 
  #expect_equal(model.instance$`messageMarkdown`, "EXPECTED_RESULT")
})

test_that("threadId", {
  # tests for the property `threadId` (character)
  # The ID of the thread this Reply belongs to

  # uncomment below to test the property 
  #expect_equal(model.instance$`threadId`, "EXPECTED_RESULT")
})

