# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DockerRegistryEventServicesApi")

api_instance <- DockerRegistryEventServicesApi$new()

test_that("PostDockerRegistryListenerV1Events", {
  # tests for PostDockerRegistryListenerV1Events
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_docker_docker_registry_event_list OrgSagebionetworksRepoModelDockerDockerRegistryEventList 
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
