# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelDoiV2DataciteMetadata")

model_instance <- OrgSagebionetworksRepoModelDoiV2DataciteMetadata$new()

test_that("creators", {
  # tests for the property `creators` (array[OrgSagebionetworksRepoModelDoiV2DoiCreator])
  # Required. The main researchers involved in producing the data, or the authors of the publication, in priority order.

  # uncomment below to test the property
  #expect_equal(model.instance$`creators`, "EXPECTED_RESULT")
})

test_that("titles", {
  # tests for the property `titles` (array[OrgSagebionetworksRepoModelDoiV2DoiTitle])
  # Required. A name or title by which a resource is known.

  # uncomment below to test the property
  #expect_equal(model.instance$`titles`, "EXPECTED_RESULT")
})

test_that("publicationYear", {
  # tests for the property `publicationYear` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`publicationYear`, "EXPECTED_RESULT")
})

test_that("resourceType", {
  # tests for the property `resourceType` (OrgSagebionetworksRepoModelDoiV2DoiResourceType)

  # uncomment below to test the property
  #expect_equal(model.instance$`resourceType`, "EXPECTED_RESULT")
})

test_that("associationId", {
  # tests for the property `associationId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`associationId`, "EXPECTED_RESULT")
})

test_that("etag", {
  # tests for the property `etag` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`etag`, "EXPECTED_RESULT")
})

test_that("doiUri", {
  # tests for the property `doiUri` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`doiUri`, "EXPECTED_RESULT")
})

test_that("doiUrl", {
  # tests for the property `doiUrl` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`doiUrl`, "EXPECTED_RESULT")
})

test_that("objectId", {
  # tests for the property `objectId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`objectId`, "EXPECTED_RESULT")
})

test_that("objectType", {
  # tests for the property `objectType` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`objectType`, "EXPECTED_RESULT")
})

test_that("objectVersion", {
  # tests for the property `objectVersion` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`objectVersion`, "EXPECTED_RESULT")
})

test_that("associatedBy", {
  # tests for the property `associatedBy` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`associatedBy`, "EXPECTED_RESULT")
})

test_that("associatedOn", {
  # tests for the property `associatedOn` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`associatedOn`, "EXPECTED_RESULT")
})

test_that("updatedBy", {
  # tests for the property `updatedBy` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`updatedBy`, "EXPECTED_RESULT")
})

test_that("updatedOn", {
  # tests for the property `updatedOn` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`updatedOn`, "EXPECTED_RESULT")
})
