# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelAuthTwoFactorAuthRecoveryCodes")

model_instance <- OrgSagebionetworksRepoModelAuthTwoFactorAuthRecoveryCodes$new()

test_that("codes", {
  # tests for the property `codes` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`codes`, "EXPECTED_RESULT")
})
