# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelFileFileHandleAssociation")

model_instance <- OrgSagebionetworksRepoModelFileFileHandleAssociation$new()

test_that("fileHandleId", {
  # tests for the property `fileHandleId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`fileHandleId`, "EXPECTED_RESULT")
})

test_that("associateObjectId", {
  # tests for the property `associateObjectId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`associateObjectId`, "EXPECTED_RESULT")
})

test_that("associateObjectType", {
  # tests for the property `associateObjectType` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`associateObjectType`, "EXPECTED_RESULT")
})
