# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelPrincipalPrincipalAlias")

model_instance <- OrgSagebionetworksRepoModelPrincipalPrincipalAlias$new()

test_that("aliasId", {
  # tests for the property `aliasId` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`aliasId`, "EXPECTED_RESULT")
})

test_that("etag", {
  # tests for the property `etag` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`etag`, "EXPECTED_RESULT")
})

test_that("principalId", {
  # tests for the property `principalId` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`principalId`, "EXPECTED_RESULT")
})

test_that("alias", {
  # tests for the property `alias` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`alias`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})
