# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelDataaccessSubmissionInfo")

model_instance <- OrgSagebionetworksRepoModelDataaccessSubmissionInfo$new()

test_that("institution", {
  # tests for the property `institution` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`institution`, "EXPECTED_RESULT")
})

test_that("projectLead", {
  # tests for the property `projectLead` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`projectLead`, "EXPECTED_RESULT")
})

test_that("intendedDataUseStatement", {
  # tests for the property `intendedDataUseStatement` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`intendedDataUseStatement`, "EXPECTED_RESULT")
})

test_that("modifiedOn", {
  # tests for the property `modifiedOn` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`modifiedOn`, "EXPECTED_RESULT")
})

test_that("submittedBy", {
  # tests for the property `submittedBy` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`submittedBy`, "EXPECTED_RESULT")
})

test_that("accessorChanges", {
  # tests for the property `accessorChanges` (array[OrgSagebionetworksRepoModelDataaccessAccessorChange])
  # List of user changes. A user can gain access, renew access or have access revoked.

  # uncomment below to test the property
  #expect_equal(model.instance$`accessorChanges`, "EXPECTED_RESULT")
})
