# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test QueryNextPageToken")

model.instance <- QueryNextPageToken$new()

test_that("concreteType", {
  # tests for the property `concreteType` (character)
  # Concrete Type

  # uncomment below to test the property 
  #expect_equal(model.instance$`concreteType`, "EXPECTED_RESULT")
})

test_that("entityId", {
  # tests for the property `entityId` (character)
  # The ID of an Entity.

  # uncomment below to test the property 
  #expect_equal(model.instance$`entityId`, "EXPECTED_RESULT")
})

test_that("token", {
  # tests for the property `token` (character)
  # The token for the next page.

  # uncomment below to test the property 
  #expect_equal(model.instance$`token`, "EXPECTED_RESULT")
})

