# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelPaginatedTeamIds")

model_instance <- OrgSagebionetworksRepoModelPaginatedTeamIds$new()

test_that("teamIds", {
  # tests for the property `teamIds` (array[character])
  # The requested team IDs.

  # uncomment below to test the property
  #expect_equal(model.instance$`teamIds`, "EXPECTED_RESULT")
})

test_that("nextPageToken", {
  # tests for the property `nextPageToken` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`nextPageToken`, "EXPECTED_RESULT")
})
