# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelTableQueryBundleRequest")

model_instance <- OrgSagebionetworksRepoModelTableQueryBundleRequest$new()

test_that("concreteType", {
  # tests for the property `concreteType` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`concreteType`, "EXPECTED_RESULT")
})

test_that("entityId", {
  # tests for the property `entityId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`entityId`, "EXPECTED_RESULT")
})

test_that("query", {
  # tests for the property `query` (OrgSagebionetworksRepoModelTableQuery)

  # uncomment below to test the property
  #expect_equal(model.instance$`query`, "EXPECTED_RESULT")
})

test_that("partMask", {
  # tests for the property `partMask` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`partMask`, "EXPECTED_RESULT")
})
