# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TeamMember")

model.instance <- TeamMember$new()

test_that("isAdmin", {
  # tests for the property `isAdmin` (character)
  # True if the user is an administrator in the Team.

  # uncomment below to test the property 
  #expect_equal(model.instance$`isAdmin`, "EXPECTED_RESULT")
})

test_that("member", {
  # tests for the property `member` (UserGroupHeader)

  # uncomment below to test the property 
  #expect_equal(model.instance$`member`, "EXPECTED_RESULT")
})

test_that("teamId", {
  # tests for the property `teamId` (character)
  # The id of the Team.

  # uncomment below to test the property 
  #expect_equal(model.instance$`teamId`, "EXPECTED_RESULT")
})

