# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SelectColumn")

model.instance <- SelectColumn$new()

test_that("columnType", {
  # tests for the property `columnType` (ColumnType)

  # uncomment below to test the property 
  #expect_equal(model.instance$`columnType`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (character)
  # The optional ID of the select column, if this is a direct column selected

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # The required display name of the column

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

