# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelTableTableStatus")

model_instance <- OrgSagebionetworksRepoModelTableTableStatus$new()

test_that("state", {
  # tests for the property `state` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`state`, "EXPECTED_RESULT")
})

test_that("tableId", {
  # tests for the property `tableId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`tableId`, "EXPECTED_RESULT")
})

test_that("version", {
  # tests for the property `version` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`version`, "EXPECTED_RESULT")
})

test_that("startedOn", {
  # tests for the property `startedOn` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`startedOn`, "EXPECTED_RESULT")
})

test_that("changedOn", {
  # tests for the property `changedOn` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`changedOn`, "EXPECTED_RESULT")
})

test_that("resetToken", {
  # tests for the property `resetToken` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`resetToken`, "EXPECTED_RESULT")
})

test_that("lastTableChangeEtag", {
  # tests for the property `lastTableChangeEtag` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`lastTableChangeEtag`, "EXPECTED_RESULT")
})

test_that("progressMessage", {
  # tests for the property `progressMessage` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`progressMessage`, "EXPECTED_RESULT")
})

test_that("progressCurrent", {
  # tests for the property `progressCurrent` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`progressCurrent`, "EXPECTED_RESULT")
})

test_that("progressTotal", {
  # tests for the property `progressTotal` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`progressTotal`, "EXPECTED_RESULT")
})

test_that("errorMessage", {
  # tests for the property `errorMessage` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`errorMessage`, "EXPECTED_RESULT")
})

test_that("errorDetails", {
  # tests for the property `errorDetails` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`errorDetails`, "EXPECTED_RESULT")
})

test_that("totalTimeMS", {
  # tests for the property `totalTimeMS` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`totalTimeMS`, "EXPECTED_RESULT")
})
