# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelDownloadDownloadListManifestResponse")

model_instance <- OrgSagebionetworksRepoModelDownloadDownloadListManifestResponse$new()

test_that("concreteType", {
  # tests for the property `concreteType` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`concreteType`, "EXPECTED_RESULT")
})

test_that("resultFileHandleId", {
  # tests for the property `resultFileHandleId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`resultFileHandleId`, "EXPECTED_RESULT")
})
