# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelMigrationMigrationTypeCount")

model_instance <- OrgSagebionetworksRepoModelMigrationMigrationTypeCount$new()

test_that("concreteType", {
  # tests for the property `concreteType` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`concreteType`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("count", {
  # tests for the property `count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`count`, "EXPECTED_RESULT")
})

test_that("maxid", {
  # tests for the property `maxid` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`maxid`, "EXPECTED_RESULT")
})

test_that("minid", {
  # tests for the property `minid` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`minid`, "EXPECTED_RESULT")
})
