# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelSchemaListJsonSchemaInfoRequest")

model_instance <- OrgSagebionetworksRepoModelSchemaListJsonSchemaInfoRequest$new()

test_that("organizationName", {
  # tests for the property `organizationName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`organizationName`, "EXPECTED_RESULT")
})

test_that("nextPageToken", {
  # tests for the property `nextPageToken` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`nextPageToken`, "EXPECTED_RESULT")
})
