# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AnnotationsValueType")

model.instance <- AnnotationsValueType$new()

