# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelTableAppendableRowSetRequest")

model_instance <- OrgSagebionetworksRepoModelTableAppendableRowSetRequest$new()

test_that("concreteType", {
  # tests for the property `concreteType` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`concreteType`, "EXPECTED_RESULT")
})

test_that("entityId", {
  # tests for the property `entityId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`entityId`, "EXPECTED_RESULT")
})

test_that("toAppend", {
  # tests for the property `toAppend` (OrgSagebionetworksRepoModelTableAppendableRowSet)

  # uncomment below to test the property
  #expect_equal(model.instance$`toAppend`, "EXPECTED_RESULT")
})
