# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test TableUpdateRequest")

model.instance <- TableUpdateRequest$new()

test_that("concreteType", {
  # tests for the property `concreteType` (character)
  # Concrete Type

  # uncomment below to test the property 
  #expect_equal(model.instance$`concreteType`, "EXPECTED_RESULT")
})

test_that("entityId", {
  # tests for the property `entityId` (character)
  # Entity Id

  # uncomment below to test the property 
  #expect_equal(model.instance$`entityId`, "EXPECTED_RESULT")
})

