# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelSearchHit")

model_instance <- OrgSagebionetworksRepoModelSearchHit$new()

test_that("id", {
  # tests for the property `id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("etag", {
  # tests for the property `etag` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`etag`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("alias", {
  # tests for the property `alias` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`alias`, "EXPECTED_RESULT")
})

test_that("path", {
  # tests for the property `path` (OrgSagebionetworksRepoModelEntityPath)

  # uncomment below to test the property
  #expect_equal(model.instance$`path`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("node_type", {
  # tests for the property `node_type` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`node_type`, "EXPECTED_RESULT")
})

test_that("created_on", {
  # tests for the property `created_on` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`created_on`, "EXPECTED_RESULT")
})

test_that("modified_on", {
  # tests for the property `modified_on` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`modified_on`, "EXPECTED_RESULT")
})

test_that("created_by", {
  # tests for the property `created_by` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`created_by`, "EXPECTED_RESULT")
})

test_that("modified_by", {
  # tests for the property `modified_by` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`modified_by`, "EXPECTED_RESULT")
})

test_that("diagnosis", {
  # tests for the property `diagnosis` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`diagnosis`, "EXPECTED_RESULT")
})

test_that("tissue", {
  # tests for the property `tissue` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`tissue`, "EXPECTED_RESULT")
})

test_that("consortium", {
  # tests for the property `consortium` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`consortium`, "EXPECTED_RESULT")
})

test_that("organ", {
  # tests for the property `organ` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`organ`, "EXPECTED_RESULT")
})
