# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SubmissionStatusForm")

model.instance <- SubmissionStatusForm$new()

test_that("rejectionMessage", {
  # tests for the property `rejectionMessage` (character)
  # The message provided by the reviewer when a submission is rejected.

  # uncomment below to test the property 
  #expect_equal(model.instance$`rejectionMessage`, "EXPECTED_RESULT")
})

test_that("reviewedBy", {
  # tests for the property `reviewedBy` (character)
  # The id of the service user that reviewed the submission.

  # uncomment below to test the property 
  #expect_equal(model.instance$`reviewedBy`, "EXPECTED_RESULT")
})

test_that("reviewedOn", {
  # tests for the property `reviewedOn` (character)
  # The date when this submission was reviewed.

  # uncomment below to test the property 
  #expect_equal(model.instance$`reviewedOn`, "EXPECTED_RESULT")
})

test_that("state", {
  # tests for the property `state` (StateEnum)

  # uncomment below to test the property 
  #expect_equal(model.instance$`state`, "EXPECTED_RESULT")
})

test_that("submittedOn", {
  # tests for the property `submittedOn` (character)
  # The date when the object was submitted.

  # uncomment below to test the property 
  #expect_equal(model.instance$`submittedOn`, "EXPECTED_RESULT")
})

