# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelFavorite")

model_instance <- OrgSagebionetworksRepoModelFavorite$new()

test_that("entityId", {
  # tests for the property `entityId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`entityId`, "EXPECTED_RESULT")
})

test_that("principalId", {
  # tests for the property `principalId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`principalId`, "EXPECTED_RESULT")
})

test_that("createdOn", {
  # tests for the property `createdOn` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`createdOn`, "EXPECTED_RESULT")
})
