# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AsynchronousJobServicesApi")

api_instance <- AsynchronousJobServicesApi$new()

test_that("GetRepoV1AsynchronousJobJobId", {
  # tests for GetRepoV1AsynchronousJobJobId
  # base path: https://repo-prod.prod.sagebase.org
  # @param job_id character The jobId issued to a job that has been launched with ,<a href=\"${POST.asynchronous.job}\">,POST         /asynchronous/job,</a>
  # @return [OrgSagebionetworksRepoModelAsynchAsynchronousJobStatus]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PostRepoV1AsynchronousJob", {
  # tests for PostRepoV1AsynchronousJob
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_asynch_asynchronous_request_body OrgSagebionetworksRepoModelAsynchAsynchronousRequestBody 
  # @return [OrgSagebionetworksRepoModelAsynchAsynchronousJobStatus]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
