# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelOauthOAuthUrlResponse")

model_instance <- OrgSagebionetworksRepoModelOauthOAuthUrlResponse$new()

test_that("authorizationUrl", {
  # tests for the property `authorizationUrl` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`authorizationUrl`, "EXPECTED_RESULT")
})
