# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelAsynchAsynchronousResponseBody")

model_instance <- OrgSagebionetworksRepoModelAsynchAsynchronousResponseBody$new()

test_that("concreteType", {
  # tests for the property `concreteType` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`concreteType`, "EXPECTED_RESULT")
})

test_that("updateResults", {
  # tests for the property `updateResults` (array[OrgSagebionetworksRepoModelTableEntityUpdateResult])
  # List of Results

  # uncomment below to test the property
  #expect_equal(model.instance$`updateResults`, "EXPECTED_RESULT")
})

test_that("newVersionInfo", {
  # tests for the property `newVersionInfo` (OrgSagebionetworksRepoModelSchemaJsonSchemaVersionInfo)

  # uncomment below to test the property
  #expect_equal(model.instance$`newVersionInfo`, "EXPECTED_RESULT")
})

test_that("validationSchema", {
  # tests for the property `validationSchema` (OrgSagebionetworksRepoModelSchemaJsonSchema)

  # uncomment below to test the property
  #expect_equal(model.instance$`validationSchema`, "EXPECTED_RESULT")
})

test_that("responseDetails", {
  # tests for the property `responseDetails` (OrgSagebionetworksRepoModelDownloadQueryResponseDetails)

  # uncomment below to test the property
  #expect_equal(model.instance$`responseDetails`, "EXPECTED_RESULT")
})

test_that("rowReferenceSet", {
  # tests for the property `rowReferenceSet` (OrgSagebionetworksRepoModelTableRowReferenceSet)

  # uncomment below to test the property
  #expect_equal(model.instance$`rowReferenceSet`, "EXPECTED_RESULT")
})

test_that("resultsFileHandleId", {
  # tests for the property `resultsFileHandleId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`resultsFileHandleId`, "EXPECTED_RESULT")
})

test_that("tableId", {
  # tests for the property `tableId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`tableId`, "EXPECTED_RESULT")
})

test_that("etag", {
  # tests for the property `etag` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`etag`, "EXPECTED_RESULT")
})

test_that("headers", {
  # tests for the property `headers` (array[OrgSagebionetworksRepoModelTableSelectColumn])
  # The list of SelectColumns that describes the rows of this set.

  # uncomment below to test the property
  #expect_equal(model.instance$`headers`, "EXPECTED_RESULT")
})

test_that("adminResponse", {
  # tests for the property `adminResponse` (OrgSagebionetworksRepoModelMigrationAdminResponse)

  # uncomment below to test the property
  #expect_equal(model.instance$`adminResponse`, "EXPECTED_RESULT")
})

test_that("resultZipFileHandleId", {
  # tests for the property `resultZipFileHandleId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`resultZipFileHandleId`, "EXPECTED_RESULT")
})

test_that("fileSummary", {
  # tests for the property `fileSummary` (array[OrgSagebionetworksRepoModelFileFileDownloadSummary])
  # The summary of each requested file.

  # uncomment below to test the property
  #expect_equal(model.instance$`fileSummary`, "EXPECTED_RESULT")
})

test_that("userId", {
  # tests for the property `userId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`userId`, "EXPECTED_RESULT")
})

test_that("numberOfFilesAdded", {
  # tests for the property `numberOfFilesAdded` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`numberOfFilesAdded`, "EXPECTED_RESULT")
})

test_that("downloadList", {
  # tests for the property `downloadList` (OrgSagebionetworksRepoModelFileDownloadList)

  # uncomment below to test the property
  #expect_equal(model.instance$`downloadList`, "EXPECTED_RESULT")
})

test_that("doi", {
  # tests for the property `doi` (OrgSagebionetworksRepoModelDoiV2Doi)

  # uncomment below to test the property
  #expect_equal(model.instance$`doi`, "EXPECTED_RESULT")
})

test_that("queryResult", {
  # tests for the property `queryResult` (OrgSagebionetworksRepoModelTableQueryResult)

  # uncomment below to test the property
  #expect_equal(model.instance$`queryResult`, "EXPECTED_RESULT")
})

test_that("queryCount", {
  # tests for the property `queryCount` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`queryCount`, "EXPECTED_RESULT")
})

test_that("selectColumns", {
  # tests for the property `selectColumns` (array[OrgSagebionetworksRepoModelTableSelectColumn])
  # The list of SelectColumns from the select clause. Use mask &#x3D; 0x4 to include in the bundle.

  # uncomment below to test the property
  #expect_equal(model.instance$`selectColumns`, "EXPECTED_RESULT")
})

test_that("maxRowsPerPage", {
  # tests for the property `maxRowsPerPage` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`maxRowsPerPage`, "EXPECTED_RESULT")
})

test_that("columnModels", {
  # tests for the property `columnModels` (array[OrgSagebionetworksRepoModelTableColumnModel])
  # The list of ColumnModels for the table. Use mask &#x3D; 0x10 to include in the bundle.

  # uncomment below to test the property
  #expect_equal(model.instance$`columnModels`, "EXPECTED_RESULT")
})

test_that("facets", {
  # tests for the property `facets` (array[OrgSagebionetworksRepoModelTableFacetColumnResult])
  # The list of facets for the search results

  # uncomment below to test the property
  #expect_equal(model.instance$`facets`, "EXPECTED_RESULT")
})

test_that("sumFileSizes", {
  # tests for the property `sumFileSizes` (OrgSagebionetworksRepoModelTableSumFileSizes)

  # uncomment below to test the property
  #expect_equal(model.instance$`sumFileSizes`, "EXPECTED_RESULT")
})

test_that("lastUpdatedOn", {
  # tests for the property `lastUpdatedOn` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`lastUpdatedOn`, "EXPECTED_RESULT")
})

test_that("combinedSql", {
  # tests for the property `combinedSql` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`combinedSql`, "EXPECTED_RESULT")
})

test_that("actionsRequired", {
  # tests for the property `actionsRequired` (array[OrgSagebionetworksRepoModelDownloadActionRequiredCount])
  # The first 50 actions required to download the files that are part of the query. Use mask &#x3D; 0x200 to include them in the bundle.

  # uncomment below to test the property
  #expect_equal(model.instance$`actionsRequired`, "EXPECTED_RESULT")
})

test_that("suggestedColumns", {
  # tests for the property `suggestedColumns` (array[OrgSagebionetworksRepoModelTableColumnModel])
  # The list of ColumnModels that are compatible with the CSV file.  This is more accurate for a full scan than a partial scan.

  # uncomment below to test the property
  #expect_equal(model.instance$`suggestedColumns`, "EXPECTED_RESULT")
})

test_that("sampleRows", {
  # tests for the property `sampleRows` (array[OrgSagebionetworksRepoModelTableRow])
  # A sampling of the first few rows from the CSV as they would be applied with the provided parameters.

  # uncomment below to test the property
  #expect_equal(model.instance$`sampleRows`, "EXPECTED_RESULT")
})

test_that("rowsScanned", {
  # tests for the property `rowsScanned` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`rowsScanned`, "EXPECTED_RESULT")
})

test_that("schema", {
  # tests for the property `schema` (array[OrgSagebionetworksRepoModelTableColumnModel])
  # The resulting schema after the change.

  # uncomment below to test the property
  #expect_equal(model.instance$`schema`, "EXPECTED_RESULT")
})

test_that("resultFileHandleId", {
  # tests for the property `resultFileHandleId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`resultFileHandleId`, "EXPECTED_RESULT")
})

test_that("searchEnabled", {
  # tests for the property `searchEnabled` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`searchEnabled`, "EXPECTED_RESULT")
})

test_that("restoreResults", {
  # tests for the property `restoreResults` (array[OrgSagebionetworksRepoModelFileFileHandleRestoreResult])
  # The list of restore operation status for each of the file handle in the original request.

  # uncomment below to test the property
  #expect_equal(model.instance$`restoreResults`, "EXPECTED_RESULT")
})

test_that("results", {
  # tests for the property `results` (array[OrgSagebionetworksRepoModelTableColumnModel])
  # A page of &lt;a href&#x3D;\&quot;${org.sagebionetworks.repo.model.table.ColumnModel}\&quot;&gt;ColumnModels&lt;/a&gt;

  # uncomment below to test the property
  #expect_equal(model.instance$`results`, "EXPECTED_RESULT")
})

test_that("snapshotVersionNumber", {
  # tests for the property `snapshotVersionNumber` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`snapshotVersionNumber`, "EXPECTED_RESULT")
})

test_that("nextPageToken", {
  # tests for the property `nextPageToken` (OrgSagebionetworksRepoModelTableQueryNextPageToken)

  # uncomment below to test the property
  #expect_equal(model.instance$`nextPageToken`, "EXPECTED_RESULT")
})

test_that("count", {
  # tests for the property `count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`count`, "EXPECTED_RESULT")
})

test_that("rowsProcessed", {
  # tests for the property `rowsProcessed` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`rowsProcessed`, "EXPECTED_RESULT")
})

test_that("queryResults", {
  # tests for the property `queryResults` (OrgSagebionetworksRepoModelTableRowSet)

  # uncomment below to test the property
  #expect_equal(model.instance$`queryResults`, "EXPECTED_RESULT")
})
