# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelVersionInfo")

model_instance <- OrgSagebionetworksRepoModelVersionInfo$new()

test_that("id", {
  # tests for the property `id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("versionNumber", {
  # tests for the property `versionNumber` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`versionNumber`, "EXPECTED_RESULT")
})

test_that("versionLabel", {
  # tests for the property `versionLabel` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`versionLabel`, "EXPECTED_RESULT")
})

test_that("versionComment", {
  # tests for the property `versionComment` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`versionComment`, "EXPECTED_RESULT")
})

test_that("isLatestVersion", {
  # tests for the property `isLatestVersion` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isLatestVersion`, "EXPECTED_RESULT")
})

test_that("modifiedBy", {
  # tests for the property `modifiedBy` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`modifiedBy`, "EXPECTED_RESULT")
})

test_that("contentSize", {
  # tests for the property `contentSize` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`contentSize`, "EXPECTED_RESULT")
})

test_that("contentMd5", {
  # tests for the property `contentMd5` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`contentMd5`, "EXPECTED_RESULT")
})

test_that("modifiedByPrincipalId", {
  # tests for the property `modifiedByPrincipalId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`modifiedByPrincipalId`, "EXPECTED_RESULT")
})

test_that("modifiedOn", {
  # tests for the property `modifiedOn` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`modifiedOn`, "EXPECTED_RESULT")
})
