# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelFormListResponse")

model_instance <- OrgSagebionetworksRepoModelFormListResponse$new()

test_that("page", {
  # tests for the property `page` (array[OrgSagebionetworksRepoModelFormFormData])
  # A single page of results matching the request.

  # uncomment below to test the property
  #expect_equal(model.instance$`page`, "EXPECTED_RESULT")
})

test_that("nextPageToken", {
  # tests for the property `nextPageToken` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`nextPageToken`, "EXPECTED_RESULT")
})
