# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelFileGoogleCloudFileHandle")

model_instance <- OrgSagebionetworksRepoModelFileGoogleCloudFileHandle$new()

test_that("id", {
  # tests for the property `id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("etag", {
  # tests for the property `etag` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`etag`, "EXPECTED_RESULT")
})

test_that("createdBy", {
  # tests for the property `createdBy` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`createdBy`, "EXPECTED_RESULT")
})

test_that("createdOn", {
  # tests for the property `createdOn` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`createdOn`, "EXPECTED_RESULT")
})

test_that("modifiedOn", {
  # tests for the property `modifiedOn` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`modifiedOn`, "EXPECTED_RESULT")
})

test_that("concreteType", {
  # tests for the property `concreteType` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`concreteType`, "EXPECTED_RESULT")
})

test_that("contentType", {
  # tests for the property `contentType` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`contentType`, "EXPECTED_RESULT")
})

test_that("contentMd5", {
  # tests for the property `contentMd5` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`contentMd5`, "EXPECTED_RESULT")
})

test_that("fileName", {
  # tests for the property `fileName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`fileName`, "EXPECTED_RESULT")
})

test_that("storageLocationId", {
  # tests for the property `storageLocationId` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`storageLocationId`, "EXPECTED_RESULT")
})

test_that("contentSize", {
  # tests for the property `contentSize` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`contentSize`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("bucketName", {
  # tests for the property `bucketName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`bucketName`, "EXPECTED_RESULT")
})

test_that("key", {
  # tests for the property `key` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`key`, "EXPECTED_RESULT")
})

test_that("previewId", {
  # tests for the property `previewId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`previewId`, "EXPECTED_RESULT")
})

test_that("isPreview", {
  # tests for the property `isPreview` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isPreview`, "EXPECTED_RESULT")
})
