# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelEntityFileHandleUpdateRequest")

model_instance <- OrgSagebionetworksRepoModelEntityFileHandleUpdateRequest$new()

test_that("oldFileHandleId", {
  # tests for the property `oldFileHandleId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`oldFileHandleId`, "EXPECTED_RESULT")
})

test_that("newFileHandleId", {
  # tests for the property `newFileHandleId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`newFileHandleId`, "EXPECTED_RESULT")
})
