# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelDataaccessOpenSubmission")

model_instance <- OrgSagebionetworksRepoModelDataaccessOpenSubmission$new()

test_that("numberOfSubmittedSubmission", {
  # tests for the property `numberOfSubmittedSubmission` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`numberOfSubmittedSubmission`, "EXPECTED_RESULT")
})

test_that("accessRequirementId", {
  # tests for the property `accessRequirementId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`accessRequirementId`, "EXPECTED_RESULT")
})
