# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelSubscriptionSubscriptionRequest")

model_instance <- OrgSagebionetworksRepoModelSubscriptionSubscriptionRequest$new()

test_that("objectType", {
  # tests for the property `objectType` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`objectType`, "EXPECTED_RESULT")
})

test_that("idList", {
  # tests for the property `idList` (array[character])
  # The list of objectId

  # uncomment below to test the property
  #expect_equal(model.instance$`idList`, "EXPECTED_RESULT")
})

test_that("sortByType", {
  # tests for the property `sortByType` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`sortByType`, "EXPECTED_RESULT")
})

test_that("sortDirection", {
  # tests for the property `sortDirection` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`sortDirection`, "EXPECTED_RESULT")
})
