# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelDiscussionCreateDiscussionThread")

model_instance <- OrgSagebionetworksRepoModelDiscussionCreateDiscussionThread$new()

test_that("forumId", {
  # tests for the property `forumId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`forumId`, "EXPECTED_RESULT")
})

test_that("title", {
  # tests for the property `title` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`title`, "EXPECTED_RESULT")
})

test_that("messageMarkdown", {
  # tests for the property `messageMarkdown` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`messageMarkdown`, "EXPECTED_RESULT")
})
