# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ColumnModel")

model.instance <- ColumnModel$new()

test_that("columnType", {
  # tests for the property `columnType` (ColumnType)

  # uncomment below to test the property 
  #expect_equal(model.instance$`columnType`, "EXPECTED_RESULT")
})

test_that("defaultValue", {
  # tests for the property `defaultValue` (character)
  # The default value for this column. Columns of type ENTITYID, FILEHANDLEID, USERID, and LARGETEXT are not allowed to have default values. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`defaultValue`, "EXPECTED_RESULT")
})

test_that("enumValues", {
  # tests for the property `enumValues` (array[character])
  # Columns of type STRING can be constrained to an enumeration values set on this list. The maximum number of entries for an enum is 100 

  # uncomment below to test the property 
  #expect_equal(model.instance$`enumValues`, "EXPECTED_RESULT")
})

test_that("facetType", {
  # tests for the property `facetType` (FacetType)

  # uncomment below to test the property 
  #expect_equal(model.instance$`facetType`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (character)
  # The immutable ID issued to new columns

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("maximumListLength", {
  # tests for the property `maximumListLength` (integer)
  # Required if using a columnType with a \&quot;_LIST\&quot; suffix. Describes the maximum number of values that will appear in that list. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`maximumListLength`, "EXPECTED_RESULT")
})

test_that("maximumSize", {
  # tests for the property `maximumSize` (numeric)
  # A parameter for columnTypes with a maximum size. For example, ColumnType. STRINGs have a default maximum size of 50 characters, but can be set to a maximumSize of 1 to 1000 characters. For columnType of STRING_LIST, this limits the size of individual string elements in the list 

  # uncomment below to test the property 
  #expect_equal(model.instance$`maximumSize`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # The display name of the column

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

