# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelUserGroupHeader")

model_instance <- OrgSagebionetworksRepoModelUserGroupHeader$new()

test_that("ownerId", {
  # tests for the property `ownerId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`ownerId`, "EXPECTED_RESULT")
})

test_that("firstName", {
  # tests for the property `firstName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`firstName`, "EXPECTED_RESULT")
})

test_that("lastName", {
  # tests for the property `lastName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`lastName`, "EXPECTED_RESULT")
})

test_that("userName", {
  # tests for the property `userName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`userName`, "EXPECTED_RESULT")
})

test_that("email", {
  # tests for the property `email` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`email`, "EXPECTED_RESULT")
})

test_that("displayName", {
  # tests for the property `displayName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`displayName`, "EXPECTED_RESULT")
})

test_that("isIndividual", {
  # tests for the property `isIndividual` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isIndividual`, "EXPECTED_RESULT")
})
