# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelNode")

model_instance <- OrgSagebionetworksRepoModelNode$new()

test_that("id", {
  # tests for the property `id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("parentId", {
  # tests for the property `parentId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`parentId`, "EXPECTED_RESULT")
})

test_that("createdByPrincipalId", {
  # tests for the property `createdByPrincipalId` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`createdByPrincipalId`, "EXPECTED_RESULT")
})

test_that("createdOn", {
  # tests for the property `createdOn` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`createdOn`, "EXPECTED_RESULT")
})

test_that("modifiedByPrincipalId", {
  # tests for the property `modifiedByPrincipalId` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`modifiedByPrincipalId`, "EXPECTED_RESULT")
})

test_that("modifiedOn", {
  # tests for the property `modifiedOn` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`modifiedOn`, "EXPECTED_RESULT")
})

test_that("nodeType", {
  # tests for the property `nodeType` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`nodeType`, "EXPECTED_RESULT")
})

test_that("eTag", {
  # tests for the property `eTag` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`eTag`, "EXPECTED_RESULT")
})

test_that("versionNumber", {
  # tests for the property `versionNumber` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`versionNumber`, "EXPECTED_RESULT")
})

test_that("versionComment", {
  # tests for the property `versionComment` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`versionComment`, "EXPECTED_RESULT")
})

test_that("versionLabel", {
  # tests for the property `versionLabel` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`versionLabel`, "EXPECTED_RESULT")
})

test_that("isLatestVersion", {
  # tests for the property `isLatestVersion` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isLatestVersion`, "EXPECTED_RESULT")
})

test_that("activityId", {
  # tests for the property `activityId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`activityId`, "EXPECTED_RESULT")
})

test_that("fileHandleId", {
  # tests for the property `fileHandleId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`fileHandleId`, "EXPECTED_RESULT")
})

test_that("columnModelIds", {
  # tests for the property `columnModelIds` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`columnModelIds`, "EXPECTED_RESULT")
})

test_that("scopeIds", {
  # tests for the property `scopeIds` (array[character])
  # For FileVeiws, the list of IDs the define the scope of the view.

  # uncomment below to test the property
  #expect_equal(model.instance$`scopeIds`, "EXPECTED_RESULT")
})

test_that("items", {
  # tests for the property `items` (array[OrgSagebionetworksRepoModelEntityRef])
  # For Datasets and Dataset Collections, the list of entity references the define the view.

  # uncomment below to test the property
  #expect_equal(model.instance$`items`, "EXPECTED_RESULT")
})

test_that("reference", {
  # tests for the property `reference` (OrgSagebionetworksRepoModelReference)

  # uncomment below to test the property
  #expect_equal(model.instance$`reference`, "EXPECTED_RESULT")
})

test_that("alias", {
  # tests for the property `alias` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`alias`, "EXPECTED_RESULT")
})

test_that("isSearchEnabled", {
  # tests for the property `isSearchEnabled` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isSearchEnabled`, "EXPECTED_RESULT")
})

test_that("definingSQL", {
  # tests for the property `definingSQL` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`definingSQL`, "EXPECTED_RESULT")
})
