# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SubmissionInfoPageRequest")

model.instance <- SubmissionInfoPageRequest$new()

test_that("accessRequirementId", {
  # tests for the property `accessRequirementId` (character)
  # The ID of an AccessRequirement.

  # uncomment below to test the property 
  #expect_equal(model.instance$`accessRequirementId`, "EXPECTED_RESULT")
})

test_that("nextPageToken", {
  # tests for the property `nextPageToken` (character)
  # The token to get the next page result.

  # uncomment below to test the property 
  #expect_equal(model.instance$`nextPageToken`, "EXPECTED_RESULT")
})

