# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelEntityRef")

model_instance <- OrgSagebionetworksRepoModelEntityRef$new()

test_that("entityId", {
  # tests for the property `entityId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`entityId`, "EXPECTED_RESULT")
})

test_that("versionNumber", {
  # tests for the property `versionNumber` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`versionNumber`, "EXPECTED_RESULT")
})
