# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ValidationSummaryStatistics")

model.instance <- ValidationSummaryStatistics$new()

test_that("containerId", {
  # tests for the property `containerId` (character)
  # The ID of the container Entity.

  # uncomment below to test the property 
  #expect_equal(model.instance$`containerId`, "EXPECTED_RESULT")
})

test_that("generatedOn", {
  # tests for the property `generatedOn` (character)
  # The date-time when the statistics were calculated.

  # uncomment below to test the property 
  #expect_equal(model.instance$`generatedOn`, "EXPECTED_RESULT")
})

test_that("numberOfInvalidChildren", {
  # tests for the property `numberOfInvalidChildren` (integer)
  # The total number of children that are invalid according to their bound JSON schema.

  # uncomment below to test the property 
  #expect_equal(model.instance$`numberOfInvalidChildren`, "EXPECTED_RESULT")
})

test_that("numberOfUnknownChildren", {
  # tests for the property `numberOfUnknownChildren` (integer)
  # The total number of children that do not have validation results. This can occur when a child does not have a bound JSON schema or when a child has not been validated yet.

  # uncomment below to test the property 
  #expect_equal(model.instance$`numberOfUnknownChildren`, "EXPECTED_RESULT")
})

test_that("numberOfValidChildren", {
  # tests for the property `numberOfValidChildren` (integer)
  # The total number of children that are valid according to their bound JSON schema.

  # uncomment below to test the property 
  #expect_equal(model.instance$`numberOfValidChildren`, "EXPECTED_RESULT")
})

test_that("totalNumberOfChildren", {
  # tests for the property `totalNumberOfChildren` (integer)
  # The total number of children in the container.

  # uncomment below to test the property 
  #expect_equal(model.instance$`totalNumberOfChildren`, "EXPECTED_RESULT")
})

