# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AccessorGroup")

model.instance <- AccessorGroup$new()

test_that("accessRequirementId", {
  # tests for the property `accessRequirementId` (character)
  # The ID of an AccessRequirement.

  # uncomment below to test the property 
  #expect_equal(model.instance$`accessRequirementId`, "EXPECTED_RESULT")
})

test_that("accessorIds", {
  # tests for the property `accessorIds` (array[character])
  # The ID of accessors.

  # uncomment below to test the property 
  #expect_equal(model.instance$`accessorIds`, "EXPECTED_RESULT")
})

test_that("expiredOn", {
  # tests for the property `expiredOn` (character)
  # The date this group will be expired.

  # uncomment below to test the property 
  #expect_equal(model.instance$`expiredOn`, "EXPECTED_RESULT")
})

test_that("submitterId", {
  # tests for the property `submitterId` (character)
  # The ID of the submitter.

  # uncomment below to test the property 
  #expect_equal(model.instance$`submitterId`, "EXPECTED_RESULT")
})

