# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelOauthOIDCClaimsRequestDetails")

model_instance <- OrgSagebionetworksRepoModelOauthOIDCClaimsRequestDetails$new()

test_that("essential", {
  # tests for the property `essential` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`essential`, "EXPECTED_RESULT")
})

test_that("value", {
  # tests for the property `value` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`value`, "EXPECTED_RESULT")
})

test_that("values", {
  # tests for the property `values` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`values`, "EXPECTED_RESULT")
})
