# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelTableColumnChange")

model_instance <- OrgSagebionetworksRepoModelTableColumnChange$new()

test_that("oldColumnId", {
  # tests for the property `oldColumnId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`oldColumnId`, "EXPECTED_RESULT")
})

test_that("newColumnId", {
  # tests for the property `newColumnId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`newColumnId`, "EXPECTED_RESULT")
})
