# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test UserGroupHeaderResponse")

model.instance <- UserGroupHeaderResponse$new()

test_that("list", {
  # tests for the property `list` (array[UserGroupHeader])
  # The list of UserGroupHeaders

  # uncomment below to test the property 
  #expect_equal(model.instance$`list`, "EXPECTED_RESULT")
})

