# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test PrincipalServicesApi")

api_instance <- PrincipalServicesApi$new()

test_that("DeleteRepoV1Email", {
  # tests for DeleteRepoV1Email
  # base path: https://repo-prod.prod.sagebase.org
  # @param email character the email address to remove
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetRepoV1NotificationEmail", {
  # tests for GetRepoV1NotificationEmail
  # base path: https://repo-prod.prod.sagebase.org
  # @return [OrgSagebionetworksRepoModelPrincipalNotificationEmail]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PostRepoV1Account2", {
  # tests for PostRepoV1Account2
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_principal_account_setup_info OrgSagebionetworksRepoModelPrincipalAccountSetupInfo 
  # @return [OrgSagebionetworksRepoModelAuthLoginResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PostRepoV1AccountEmailValidation", {
  # tests for PostRepoV1AccountEmailValidation
  # base path: https://repo-prod.prod.sagebase.org
  # @param portal_endpoint character the beginning of the URL included in the email verification message. When concatenated with         a list of ampersand (,&,) separated request parameters, must become a well formed URL. The concatenated         string must be included with the ,<a href=\"${POST.account2}\">,POST /account,</a>, request.
  # @param org_sagebionetworks_repo_model_auth_new_user OrgSagebionetworksRepoModelAuthNewUser 
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PostRepoV1AccountIdEmailValidation", {
  # tests for PostRepoV1AccountIdEmailValidation
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character the ID of the user account to which the email address is to be added. Must match the ID of the user         making the request.
  # @param portal_endpoint character the beginning of the URL included in the email verification message. When concatenated with         a list of ampersand (,&,) separated request parameters, must become a well formed URL. The concatenated         string must be included with the ,<a href=\"${POST.email}\">,POST /email,</a>, request.
  # @param org_sagebionetworks_repo_model_auth_username OrgSagebionetworksRepoModelAuthUsername 
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PostRepoV1Email", {
  # tests for PostRepoV1Email
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_principal_email_validation_signed_token OrgSagebionetworksRepoModelPrincipalEmailValidationSignedToken 
  # @param set_as_notification_email character if true then the newly added email address becomes the address  used by the system for sending messages to the user. (optional)
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PostRepoV1PrincipalAlias", {
  # tests for PostRepoV1PrincipalAlias
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_principal_principal_alias_request OrgSagebionetworksRepoModelPrincipalPrincipalAliasRequest 
  # @return [OrgSagebionetworksRepoModelPrincipalPrincipalAliasResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PostRepoV1PrincipalAvailable", {
  # tests for PostRepoV1PrincipalAvailable
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_principal_alias_check_request OrgSagebionetworksRepoModelPrincipalAliasCheckRequest 
  # @return [OrgSagebionetworksRepoModelPrincipalAliasCheckResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PutRepoV1NotificationEmail", {
  # tests for PutRepoV1NotificationEmail
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_auth_username OrgSagebionetworksRepoModelAuthUsername 
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
