# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test EntityIdList")

model.instance <- EntityIdList$new()

test_that("idList", {
  # tests for the property `idList` (array[character])
  # List of Entity Ids

  # uncomment below to test the property 
  #expect_equal(model.instance$`idList`, "EXPECTED_RESULT")
})

