# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test AccessApproval")

model.instance <- AccessApproval$new()

test_that("accessorId", {
  # tests for the property `accessorId` (character)
  # The ID of the principal (user or group) approved for access

  # uncomment below to test the property 
  #expect_equal(model.instance$`accessorId`, "EXPECTED_RESULT")
})

test_that("createdBy", {
  # tests for the property `createdBy` (character)
  # The user that created this object.

  # uncomment below to test the property 
  #expect_equal(model.instance$`createdBy`, "EXPECTED_RESULT")
})

test_that("createdOn", {
  # tests for the property `createdOn` (character)
  # The date this object was created.

  # uncomment below to test the property 
  #expect_equal(model.instance$`createdOn`, "EXPECTED_RESULT")
})

test_that("etag", {
  # tests for the property `etag` (character)
  # Synapse employs an Optimistic Concurrency Control (OCC) scheme to handle concurrent updates. Since the E-Tag changes every time an entity is updated it is used to detect when a client&#39;s current representation of an entity is out-of-date. 

  # uncomment below to test the property 
  #expect_equal(model.instance$`etag`, "EXPECTED_RESULT")
})

test_that("expiredOn", {
  # tests for the property `expiredOn` (character)
  # The date this object will be expired.

  # uncomment below to test the property 
  #expect_equal(model.instance$`expiredOn`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (integer)
  # The unique immutable ID

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("modifiedBy", {
  # tests for the property `modifiedBy` (character)
  # The user that last modified this object.

  # uncomment below to test the property 
  #expect_equal(model.instance$`modifiedBy`, "EXPECTED_RESULT")
})

test_that("modifiedOn", {
  # tests for the property `modifiedOn` (character)
  # The date this object was last modified.

  # uncomment below to test the property 
  #expect_equal(model.instance$`modifiedOn`, "EXPECTED_RESULT")
})

test_that("requirementId", {
  # tests for the property `requirementId` (integer)
  # The ID of the Access Requirement.

  # uncomment below to test the property 
  #expect_equal(model.instance$`requirementId`, "EXPECTED_RESULT")
})

test_that("requirementVersion", {
  # tests for the property `requirementVersion` (integer)
  # The version of the Access Requirement.

  # uncomment below to test the property 
  #expect_equal(model.instance$`requirementVersion`, "EXPECTED_RESULT")
})

test_that("state", {
  # tests for the property `state` (ApprovalState)

  # uncomment below to test the property 
  #expect_equal(model.instance$`state`, "EXPECTED_RESULT")
})

test_that("submitterId", {
  # tests for the property `submitterId` (character)
  # The user who performed the necessary action(s) to gain this approval.

  # uncomment below to test the property 
  #expect_equal(model.instance$`submitterId`, "EXPECTED_RESULT")
})

