# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelOauthOIDConnectConfiguration")

model_instance <- OrgSagebionetworksRepoModelOauthOIDConnectConfiguration$new()

test_that("issuer", {
  # tests for the property `issuer` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`issuer`, "EXPECTED_RESULT")
})

test_that("authorization_endpoint", {
  # tests for the property `authorization_endpoint` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`authorization_endpoint`, "EXPECTED_RESULT")
})

test_that("token_endpoint", {
  # tests for the property `token_endpoint` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`token_endpoint`, "EXPECTED_RESULT")
})

test_that("revocation_endpoint", {
  # tests for the property `revocation_endpoint` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`revocation_endpoint`, "EXPECTED_RESULT")
})

test_that("userinfo_endpoint", {
  # tests for the property `userinfo_endpoint` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`userinfo_endpoint`, "EXPECTED_RESULT")
})

test_that("jwks_uri", {
  # tests for the property `jwks_uri` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`jwks_uri`, "EXPECTED_RESULT")
})

test_that("registration_endpoint", {
  # tests for the property `registration_endpoint` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`registration_endpoint`, "EXPECTED_RESULT")
})

test_that("scopes_supported", {
  # tests for the property `scopes_supported` (array[character])
  # List of the OAuth 2.0 scope values that Synapse supports.

  # uncomment below to test the property
  #expect_equal(model.instance$`scopes_supported`, "EXPECTED_RESULT")
})

test_that("response_types_supported", {
  # tests for the property `response_types_supported` (array[character])
  # List of the OAuth 2.0 response types that Synapse supports.

  # uncomment below to test the property
  #expect_equal(model.instance$`response_types_supported`, "EXPECTED_RESULT")
})

test_that("grant_types_supported", {
  # tests for the property `grant_types_supported` (array[character])
  # List of the OAuth 2.0 grant types that Synapse supports.

  # uncomment below to test the property
  #expect_equal(model.instance$`grant_types_supported`, "EXPECTED_RESULT")
})

test_that("subject_types_supported", {
  # tests for the property `subject_types_supported` (array[character])
  # List of the subject identified types that Synapse supports.

  # uncomment below to test the property
  #expect_equal(model.instance$`subject_types_supported`, "EXPECTED_RESULT")
})

test_that("id_token_signing_alg_values_supported", {
  # tests for the property `id_token_signing_alg_values_supported` (array[character])
  # List of the JWS signing algorithms (alg values) supported by Synapse for the ID Token to encode the Claims in a JWT

  # uncomment below to test the property
  #expect_equal(model.instance$`id_token_signing_alg_values_supported`, "EXPECTED_RESULT")
})

test_that("userinfo_signing_alg_values_supported", {
  # tests for the property `userinfo_signing_alg_values_supported` (array[character])
  # List of the JWS signing algorithms (alg values) supported by the UserInfo Endpoint to encode the Claims in a JWT

  # uncomment below to test the property
  #expect_equal(model.instance$`userinfo_signing_alg_values_supported`, "EXPECTED_RESULT")
})

test_that("request_object_signing_alg_values_supported", {
  # tests for the property `request_object_signing_alg_values_supported` (array[character])
  # List of signing algorithms supported for signing request objects, or &#39;[\&quot;none\&quot;]&#39; if passing by &#39;request&#39; parameter is unsupported.  See &lt;a href&#x3D;\&quot;https://openid.net/specs/openid-connect-core-1_0.html#RequestObject\&quot;&gt;OpenID Connect Core 1.0&lt;/a&gt;

  # uncomment below to test the property
  #expect_equal(model.instance$`request_object_signing_alg_values_supported`, "EXPECTED_RESULT")
})

test_that("claims_supported", {
  # tests for the property `claims_supported` (array[character])
  # List of the Claim Names of the Claims that the Synapse MAY be able to supply values for.

  # uncomment below to test the property
  #expect_equal(model.instance$`claims_supported`, "EXPECTED_RESULT")
})

test_that("service_documentation", {
  # tests for the property `service_documentation` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`service_documentation`, "EXPECTED_RESULT")
})

test_that("claims_parameter_supported", {
  # tests for the property `claims_parameter_supported` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`claims_parameter_supported`, "EXPECTED_RESULT")
})

test_that("token_endpoint_auth_methods_supported", {
  # tests for the property `token_endpoint_auth_methods_supported` (array[character])
  # a list of Client Authentication methods supported by Synapse&#39;s Token Endpoint.  See &lt;a href&#x3D;\&quot;https://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication\&quot;&gt;OpenID Connect Core 1.0 Client Authentication&lt;/a&gt;

  # uncomment below to test the property
  #expect_equal(model.instance$`token_endpoint_auth_methods_supported`, "EXPECTED_RESULT")
})
