# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test EntityId")

model.instance <- EntityId$new()

test_that("id", {
  # tests for the property `id` (character)
  # The id of an entity.

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

