# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelDownloadRemoveBatchOfFilesFromDownloadListRequest")

model_instance <- OrgSagebionetworksRepoModelDownloadRemoveBatchOfFilesFromDownloadListRequest$new()

test_that("batchToRemove", {
  # tests for the property `batchToRemove` (array[OrgSagebionetworksRepoModelDownloadDownloadListItem])
  # The batch of files to remove from the user&#39;s download list. Note: There is a limit of 1000 files per batch.

  # uncomment below to test the property
  #expect_equal(model.instance$`batchToRemove`, "EXPECTED_RESULT")
})
