# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ResponseCorrectness")

model.instance <- ResponseCorrectness$new()

test_that("isCorrect", {
  # tests for the property `isCorrect` (character)
  # Is the response correct?

  # uncomment below to test the property 
  #expect_equal(model.instance$`isCorrect`, "EXPECTED_RESULT")
})

test_that("question", {
  # tests for the property `question` (Question)

  # uncomment below to test the property 
  #expect_equal(model.instance$`question`, "EXPECTED_RESULT")
})

test_that("response", {
  # tests for the property `response` (QuestionResponse)

  # uncomment below to test the property 
  #expect_equal(model.instance$`response`, "EXPECTED_RESULT")
})

