# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelStatusStackStatus")

model_instance <- OrgSagebionetworksRepoModelStatusStackStatus$new()

test_that("status", {
  # tests for the property `status` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("currentMessage", {
  # tests for the property `currentMessage` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`currentMessage`, "EXPECTED_RESULT")
})

test_that("pendingMaintenanceMessage", {
  # tests for the property `pendingMaintenanceMessage` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`pendingMaintenanceMessage`, "EXPECTED_RESULT")
})
