# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelTableTableUpdateRequest")

model_instance <- OrgSagebionetworksRepoModelTableTableUpdateRequest$new()

test_that("concreteType", {
  # tests for the property `concreteType` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`concreteType`, "EXPECTED_RESULT")
})

test_that("entityId", {
  # tests for the property `entityId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`entityId`, "EXPECTED_RESULT")
})

test_that("searchEnabled", {
  # tests for the property `searchEnabled` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`searchEnabled`, "EXPECTED_RESULT")
})

test_that("toAppend", {
  # tests for the property `toAppend` (OrgSagebionetworksRepoModelTableAppendableRowSet)

  # uncomment below to test the property
  #expect_equal(model.instance$`toAppend`, "EXPECTED_RESULT")
})

test_that("tableId", {
  # tests for the property `tableId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`tableId`, "EXPECTED_RESULT")
})

test_that("uploadFileHandleId", {
  # tests for the property `uploadFileHandleId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`uploadFileHandleId`, "EXPECTED_RESULT")
})

test_that("updateEtag", {
  # tests for the property `updateEtag` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`updateEtag`, "EXPECTED_RESULT")
})

test_that("linesToSkip", {
  # tests for the property `linesToSkip` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`linesToSkip`, "EXPECTED_RESULT")
})

test_that("csvTableDescriptor", {
  # tests for the property `csvTableDescriptor` (OrgSagebionetworksRepoModelTableCsvTableDescriptor)

  # uncomment below to test the property
  #expect_equal(model.instance$`csvTableDescriptor`, "EXPECTED_RESULT")
})

test_that("columnIds", {
  # tests for the property `columnIds` (array[character])
  # Deprecated.

  # uncomment below to test the property
  #expect_equal(model.instance$`columnIds`, "EXPECTED_RESULT")
})

test_that("changes", {
  # tests for the property `changes` (array[OrgSagebionetworksRepoModelTableColumnChange])
  # List of changes that describes column additions, deletions, and updates

  # uncomment below to test the property
  #expect_equal(model.instance$`changes`, "EXPECTED_RESULT")
})

test_that("orderedColumnIds", {
  # tests for the property `orderedColumnIds` (array[character])
  # Optional: Used to set the order of columns for this table. If this list is provided it must include the IDs of each column that will be in the schema after the changes of this request are applied.

  # uncomment below to test the property
  #expect_equal(model.instance$`orderedColumnIds`, "EXPECTED_RESULT")
})
