# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelOauthOIDCAuthorizationRequestDescription")

model_instance <- OrgSagebionetworksRepoModelOauthOIDCAuthorizationRequestDescription$new()

test_that("clientId", {
  # tests for the property `clientId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`clientId`, "EXPECTED_RESULT")
})

test_that("redirect_uri", {
  # tests for the property `redirect_uri` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`redirect_uri`, "EXPECTED_RESULT")
})

test_that("scope", {
  # tests for the property `scope` (array[character])
  # Scopes and claims requested by client

  # uncomment below to test the property
  #expect_equal(model.instance$`scope`, "EXPECTED_RESULT")
})
