# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelQuizQuiz")

model_instance <- OrgSagebionetworksRepoModelQuizQuiz$new()

test_that("id", {
  # tests for the property `id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("header", {
  # tests for the property `header` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`header`, "EXPECTED_RESULT")
})

test_that("questions", {
  # tests for the property `questions` (array[OrgSagebionetworksRepoModelQuizQuestion])
  # The questions in the Quiz

  # uncomment below to test the property
  #expect_equal(model.instance$`questions`, "EXPECTED_RESULT")
})
