# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelTableDownloadFromTableRequest")

model_instance <- OrgSagebionetworksRepoModelTableDownloadFromTableRequest$new()

test_that("concreteType", {
  # tests for the property `concreteType` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`concreteType`, "EXPECTED_RESULT")
})

test_that("entityId", {
  # tests for the property `entityId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`entityId`, "EXPECTED_RESULT")
})

test_that("writeHeader", {
  # tests for the property `writeHeader` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`writeHeader`, "EXPECTED_RESULT")
})

test_that("includeRowIdAndRowVersion", {
  # tests for the property `includeRowIdAndRowVersion` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`includeRowIdAndRowVersion`, "EXPECTED_RESULT")
})

test_that("csvTableDescriptor", {
  # tests for the property `csvTableDescriptor` (OrgSagebionetworksRepoModelTableCsvTableDescriptor)

  # uncomment below to test the property
  #expect_equal(model.instance$`csvTableDescriptor`, "EXPECTED_RESULT")
})

test_that("fileName", {
  # tests for the property `fileName` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`fileName`, "EXPECTED_RESULT")
})

test_that("sql", {
  # tests for the property `sql` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`sql`, "EXPECTED_RESULT")
})

test_that("additionalFilters", {
  # tests for the property `additionalFilters` (array[OrgSagebionetworksRepoModelTableQueryFilter])
  # Appends additional filters to the SQL query. These are applied before facets. Filters within the list have an AND relationship. If a WHERE clause already exists on the SQL query or facets are selected, it will also be ANDed with the query generated by these additional filters.

  # uncomment below to test the property
  #expect_equal(model.instance$`additionalFilters`, "EXPECTED_RESULT")
})

test_that("selectedFacets", {
  # tests for the property `selectedFacets` (array[OrgSagebionetworksRepoModelTableFacetColumnRequest])
  # The selected facet filters.

  # uncomment below to test the property
  #expect_equal(model.instance$`selectedFacets`, "EXPECTED_RESULT")
})

test_that("includeEntityEtag", {
  # tests for the property `includeEntityEtag` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`includeEntityEtag`, "EXPECTED_RESULT")
})

test_that("selectFileColumn", {
  # tests for the property `selectFileColumn` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`selectFileColumn`, "EXPECTED_RESULT")
})

test_that("offset", {
  # tests for the property `offset` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`offset`, "EXPECTED_RESULT")
})

test_that("limit", {
  # tests for the property `limit` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`limit`, "EXPECTED_RESULT")
})

test_that("sort", {
  # tests for the property `sort` (array[OrgSagebionetworksRepoModelTableSortItem])

  # uncomment below to test the property
  #expect_equal(model.instance$`sort`, "EXPECTED_RESULT")
})
