# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test EntityChildrenRequest")

model.instance <- EntityChildrenRequest$new()

test_that("includeSumFileSizes", {
  # tests for the property `includeSumFileSizes` (character)
  # When true, the sum of the files sizes (bytes) with the given parentId and types will be included. False by default

  # uncomment below to test the property 
  #expect_equal(model.instance$`includeSumFileSizes`, "EXPECTED_RESULT")
})

test_that("includeTotalChildCount", {
  # tests for the property `includeTotalChildCount` (character)
  # When true, the total number of children with the givenparentId and types will be included. False by default

  # uncomment below to test the property 
  #expect_equal(model.instance$`includeTotalChildCount`, "EXPECTED_RESULT")
})

test_that("includeTypes", {
  # tests for the property `includeTypes` (array[EntityType])
  # The types of children to be include. Must include at least one type.

  # uncomment below to test the property 
  #expect_equal(model.instance$`includeTypes`, "EXPECTED_RESULT")
})

test_that("nextPageToken", {
  # tests for the property `nextPageToken` (character)
  # Optional parameter used to fetch the next page of results. When NULL, the first page will be returned. The nextPageToken is provided with the results if there is another page of results.

  # uncomment below to test the property 
  #expect_equal(model.instance$`nextPageToken`, "EXPECTED_RESULT")
})

test_that("parentId", {
  # tests for the property `parentId` (character)
  # The ID of the parent. Set to null to list projects.

  # uncomment below to test the property 
  #expect_equal(model.instance$`parentId`, "EXPECTED_RESULT")
})

test_that("sortBy", {
  # tests for the property `sortBy` (SortBy)

  # uncomment below to test the property 
  #expect_equal(model.instance$`sortBy`, "EXPECTED_RESULT")
})

test_that("sortDirection", {
  # tests for the property `sortDirection` (SortDirection)

  # uncomment below to test the property 
  #expect_equal(model.instance$`sortDirection`, "EXPECTED_RESULT")
})

