# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelOauthOIDCClaimsRequest")

model_instance <- OrgSagebionetworksRepoModelOauthOIDCClaimsRequest$new()

test_that("userinfo", {
  # tests for the property `userinfo` (map(OrgSagebionetworksRepoModelOauthOIDCClaimsRequestDetails))
  # The OIDC Claims that can be accessed by making a request to the userinfo endpoint

  # uncomment below to test the property
  #expect_equal(model.instance$`userinfo`, "EXPECTED_RESULT")
})

test_that("id_token", {
  # tests for the property `id_token` (map(OrgSagebionetworksRepoModelOauthOIDCClaimsRequestDetails))
  # The OIDC Claims that will be provided via an ID token by making a request to the token endpoint.

  # uncomment below to test the property
  #expect_equal(model.instance$`id_token`, "EXPECTED_RESULT")
})
