# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test EntityHeader")

model.instance <- EntityHeader$new()

test_that("benefactorId", {
  # tests for the property `benefactorId` (numeric)
  # The ID of the entity that this Entity&#39;s ACL is inherited from.&#39; 

  # uncomment below to test the property 
  #expect_equal(model.instance$`benefactorId`, "EXPECTED_RESULT")
})

test_that("createdBy", {
  # tests for the property `createdBy` (character)
  # The ID of the user that created this entity.

  # uncomment below to test the property 
  #expect_equal(model.instance$`createdBy`, "EXPECTED_RESULT")
})

test_that("createdOn", {
  # tests for the property `createdOn` (character)
  # The date this entity was created.

  # uncomment below to test the property 
  #expect_equal(model.instance$`createdOn`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (character)
  # The id of the entity

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("modifiedBy", {
  # tests for the property `modifiedBy` (character)
  # The ID of the user that last modified this entity.

  # uncomment below to test the property 
  #expect_equal(model.instance$`modifiedBy`, "EXPECTED_RESULT")
})

test_that("modifiedOn", {
  # tests for the property `modifiedOn` (character)
  # The date this entity was last modified.

  # uncomment below to test the property 
  #expect_equal(model.instance$`modifiedOn`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)
  # The name of the entity

  # uncomment below to test the property 
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (character)
  # The type of the entity

  # uncomment below to test the property 
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("versionLabel", {
  # tests for the property `versionLabel` (character)
  # The user defined version label of the entity

  # uncomment below to test the property 
  #expect_equal(model.instance$`versionLabel`, "EXPECTED_RESULT")
})

test_that("versionNumber", {
  # tests for the property `versionNumber` (numeric)
  # The version number of the entity

  # uncomment below to test the property 
  #expect_equal(model.instance$`versionNumber`, "EXPECTED_RESULT")
})

