# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelDockerRegistryEventTarget")

model_instance <- OrgSagebionetworksRepoModelDockerRegistryEventTarget$new()

test_that("mediaType", {
  # tests for the property `mediaType` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`mediaType`, "EXPECTED_RESULT")
})

test_that("size", {
  # tests for the property `size` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`size`, "EXPECTED_RESULT")
})

test_that("digest", {
  # tests for the property `digest` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`digest`, "EXPECTED_RESULT")
})

test_that("length", {
  # tests for the property `length` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`length`, "EXPECTED_RESULT")
})

test_that("repository", {
  # tests for the property `repository` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`repository`, "EXPECTED_RESULT")
})

test_that("tag", {
  # tests for the property `tag` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`tag`, "EXPECTED_RESULT")
})

test_that("url", {
  # tests for the property `url` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`url`, "EXPECTED_RESULT")
})
