# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelEntityChildrenRequest")

model_instance <- OrgSagebionetworksRepoModelEntityChildrenRequest$new()

test_that("parentId", {
  # tests for the property `parentId` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`parentId`, "EXPECTED_RESULT")
})

test_that("nextPageToken", {
  # tests for the property `nextPageToken` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`nextPageToken`, "EXPECTED_RESULT")
})

test_that("includeTypes", {
  # tests for the property `includeTypes` (array[character])
  # The types of children to be include. Must include at least one type.

  # uncomment below to test the property
  #expect_equal(model.instance$`includeTypes`, "EXPECTED_RESULT")
})

test_that("sortBy", {
  # tests for the property `sortBy` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`sortBy`, "EXPECTED_RESULT")
})

test_that("sortDirection", {
  # tests for the property `sortDirection` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`sortDirection`, "EXPECTED_RESULT")
})

test_that("includeTotalChildCount", {
  # tests for the property `includeTotalChildCount` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`includeTotalChildCount`, "EXPECTED_RESULT")
})

test_that("includeSumFileSizes", {
  # tests for the property `includeSumFileSizes` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`includeSumFileSizes`, "EXPECTED_RESULT")
})
