# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelEntitybundleV2EntityBundleCreate")

model_instance <- OrgSagebionetworksRepoModelEntitybundleV2EntityBundleCreate$new()

test_that("entity", {
  # tests for the property `entity` (OrgSagebionetworksRepoModelEntity)

  # uncomment below to test the property
  #expect_equal(model.instance$`entity`, "EXPECTED_RESULT")
})

test_that("annotations", {
  # tests for the property `annotations` (OrgSagebionetworksRepoModelAnnotationV2Annotations)

  # uncomment below to test the property
  #expect_equal(model.instance$`annotations`, "EXPECTED_RESULT")
})

test_that("accessControlList", {
  # tests for the property `accessControlList` (OrgSagebionetworksRepoModelAccessControlList)

  # uncomment below to test the property
  #expect_equal(model.instance$`accessControlList`, "EXPECTED_RESULT")
})
