# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test RowSet")

model.instance <- RowSet$new()

test_that("concreteType", {
  # tests for the property `concreteType` (character)
  # Concrete Type

  # uncomment below to test the property 
  #expect_equal(model.instance$`concreteType`, "EXPECTED_RESULT")
})

test_that("etag", {
  # tests for the property `etag` (character)
  # Any RowSet returned from Synapse will contain the current etag of the change set. To update any rows from a RowSet the etag must be provided with the POST.

  # uncomment below to test the property 
  #expect_equal(model.instance$`etag`, "EXPECTED_RESULT")
})

test_that("headers", {
  # tests for the property `headers` (array[SelectColumn])
  # The list of SelectColumns that describes the rows of this set.

  # uncomment below to test the property 
  #expect_equal(model.instance$`headers`, "EXPECTED_RESULT")
})

test_that("rows", {
  # tests for the property `rows` (array[RowTable])
  # The Rows of this set. The index of each row value aligns with the index of each header.

  # uncomment below to test the property 
  #expect_equal(model.instance$`rows`, "EXPECTED_RESULT")
})

test_that("tableId", {
  # tests for the property `tableId` (character)
  # The ID of the TableEntity than owns these rows

  # uncomment below to test the property 
  #expect_equal(model.instance$`tableId`, "EXPECTED_RESULT")
})

