# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Used")

model.instance <- Used$new()

test_that("concreteType", {
  # tests for the property `concreteType` (character)
  # Concrete Type

  # uncomment below to test the property 
  #expect_equal(model.instance$`concreteType`, "EXPECTED_RESULT")
})

test_that("wasExecuted", {
  # tests for the property `wasExecuted` (character)
  # The enclosed entity was used and also executed in the Activity

  # uncomment below to test the property 
  #expect_equal(model.instance$`wasExecuted`, "EXPECTED_RESULT")
})

