# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelAuthLoginRequest")

model_instance <- OrgSagebionetworksRepoModelAuthLoginRequest$new()

test_that("username", {
  # tests for the property `username` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`username`, "EXPECTED_RESULT")
})

test_that("password", {
  # tests for the property `password` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`password`, "EXPECTED_RESULT")
})

test_that("authenticationReceipt", {
  # tests for the property `authenticationReceipt` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`authenticationReceipt`, "EXPECTED_RESULT")
})
