# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelOauthOIDCTokenResponse")

model_instance <- OrgSagebionetworksRepoModelOauthOIDCTokenResponse$new()

test_that("access_token", {
  # tests for the property `access_token` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`access_token`, "EXPECTED_RESULT")
})

test_that("refresh_token", {
  # tests for the property `refresh_token` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`refresh_token`, "EXPECTED_RESULT")
})

test_that("id_token", {
  # tests for the property `id_token` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`id_token`, "EXPECTED_RESULT")
})

test_that("token_type", {
  # tests for the property `token_type` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`token_type`, "EXPECTED_RESULT")
})

test_that("expires_in", {
  # tests for the property `expires_in` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`expires_in`, "EXPECTED_RESULT")
})
