# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test EntityServicesApi")

api_instance <- EntityServicesApi$new()

test_that("DeleteRepoV1EntityId", {
  # tests for DeleteRepoV1EntityId
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the Entity to delete.
  # @param skip_trash_can character If true the entity will be flag for priority purge and                      deleted as soon as possible (optional)
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteRepoV1EntityIdAcl", {
  # tests for DeleteRepoV1EntityIdAcl
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the Entity that should have its ACL deleted.
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteRepoV1EntityIdGeneratedBy", {
  # tests for DeleteRepoV1EntityIdGeneratedBy
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character - The ID of the activity to fetch.
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteRepoV1EntityIdSchemaBinding", {
  # tests for DeleteRepoV1EntityIdSchemaBinding
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character 
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DeleteRepoV1EntityIdVersionVersionNumber", {
  # tests for DeleteRepoV1EntityIdVersionVersionNumber
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the Entity
  # @param version_number numeric The version number of the Entity to delete.
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetRepoV1EntityAliasAlias", {
  # tests for GetRepoV1EntityAliasAlias
  # base path: https://repo-prod.prod.sagebase.org
  # @param alias character 
  # @return [OrgSagebionetworksRepoModelEntityId]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetRepoV1EntityDockerRepoId", {
  # tests for GetRepoV1EntityDockerRepoId
  # base path: https://repo-prod.prod.sagebase.org
  # @param repository_name character The name of a managed docker repository
  # @return [OrgSagebionetworksRepoModelEntityId]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetRepoV1EntityId", {
  # tests for GetRepoV1EntityId
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the entity to fetch.
  # @return [OrgSagebionetworksRepoModelEntity]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetRepoV1EntityIdAccess", {
  # tests for GetRepoV1EntityIdAccess
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the Entity to check the permission on.
  # @param access_type character The permission to check. Must be from:                    ,<a href=\"${org.sagebionetworks.repo.model.ACCESS_TYPE}\">,ACCESS_TYPE,</a>
  # @return [character]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetRepoV1EntityIdAcl", {
  # tests for GetRepoV1EntityIdAcl
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the Entity to get the ACL for.
  # @return [OrgSagebionetworksRepoModelAccessControlList]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetRepoV1EntityIdActionsDownload", {
  # tests for GetRepoV1EntityIdActionsDownload
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character 
  # @return [OrgSagebionetworksRepoModelDownloadActionRequiredList]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetRepoV1EntityIdAnnotations2", {
  # tests for GetRepoV1EntityIdAnnotations2
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character - The id of the entity to update.
  # @param include_derived character - When set to 'true', the derived annotations will be                        included in the results. Default value 'false'.
  # @return [OrgSagebionetworksRepoModelAnnotationV2Annotations]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetRepoV1EntityIdBenefactor", {
  # tests for GetRepoV1EntityIdBenefactor
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the entity to get the benefactor for.
  # @return [OrgSagebionetworksRepoModelEntityHeader]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetRepoV1EntityIdDerivedKeys", {
  # tests for GetRepoV1EntityIdDerivedKeys
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character 
  # @return [OrgSagebionetworksRepoModelAnnotationV2Keys]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetRepoV1EntityIdFilehandles", {
  # tests for GetRepoV1EntityIdFilehandles
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the FileEntity to get.
  # @return [OrgSagebionetworksRepoModelFileFileHandleResults]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetRepoV1EntityIdFilepreview", {
  # tests for GetRepoV1EntityIdFilepreview
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the FileEntity to get.
  # @param redirect character When set to false, the URL will be returned as text/plain                  instead of redirecting. (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetRepoV1EntityIdGeneratedBy", {
  # tests for GetRepoV1EntityIdGeneratedBy
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the activity to fetch.
  # @return [OrgSagebionetworksRepoModelProvenanceActivity]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetRepoV1EntityIdJson", {
  # tests for GetRepoV1EntityIdJson
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character 
  # @param include_derived_annotations character true if annotations that are derived from a                                   bound schema should be included in the                                   response, false otherwise (default false)
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetRepoV1EntityIdPath", {
  # tests for GetRepoV1EntityIdPath
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the Entity to get the full path for.
  # @return [OrgSagebionetworksRepoModelEntityPath]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetRepoV1EntityIdPermissions", {
  # tests for GetRepoV1EntityIdPermissions
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the Entity to get permissions for.
  # @return [OrgSagebionetworksRepoModelAuthUserEntityPermissions]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetRepoV1EntityIdSchemaBinding", {
  # tests for GetRepoV1EntityIdSchemaBinding
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the entity.
  # @return [OrgSagebionetworksRepoModelSchemaJsonSchemaObjectBinding]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetRepoV1EntityIdSchemaValidation", {
  # tests for GetRepoV1EntityIdSchemaValidation
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the Entity.
  # @return [OrgSagebionetworksRepoModelSchemaValidationResults]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetRepoV1EntityIdSchemaValidationStatistics", {
  # tests for GetRepoV1EntityIdSchemaValidationStatistics
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the container Entity.
  # @return [OrgSagebionetworksRepoModelSchemaValidationSummaryStatistics]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetRepoV1EntityIdSts", {
  # tests for GetRepoV1EntityIdSts
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the entity to get credentials. This must be a                    folder with an STS-enabled storage location.
  # @param permission OrgSagebionetworksRepoModelStsStsPermission Read-only or read-write permissions. See ,<a href=\"${org.sagebionetworks.repo.model.sts.StsPermission}\">,StsPermission,</a>,.
  # @return [OrgSagebionetworksRepoModelStsStsCredentials]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetRepoV1EntityIdType", {
  # tests for GetRepoV1EntityIdType
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the Entity to get the EntityHeader for.
  # @return [OrgSagebionetworksRepoModelEntityHeader]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetRepoV1EntityIdVersion", {
  # tests for GetRepoV1EntityIdVersion
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the Entity to get all versions for.
  # @param offset integer The offset index determines where this page will start                      from. When null it will default to 0. (optional)
  # @param limit integer Limits the number of entities that will be fetched for                      this page. When null it will default to 10. (optional)
  # @return [PaginatedResultsOfVersionInfo]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetRepoV1EntityIdVersionVersionNumber", {
  # tests for GetRepoV1EntityIdVersionVersionNumber
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the Entity.
  # @param version_number numeric The version number of the Entity to get.
  # @return [OrgSagebionetworksRepoModelEntity]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetRepoV1EntityIdVersionVersionNumberAnnotations2", {
  # tests for GetRepoV1EntityIdVersionVersionNumberAnnotations2
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the Entity.
  # @param version_number numeric The version number of the Entity.
  # @return [OrgSagebionetworksRepoModelAnnotationV2Annotations]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetRepoV1EntityIdVersionVersionNumberFilehandles", {
  # tests for GetRepoV1EntityIdVersionVersionNumberFilehandles
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the FileEntity to get.
  # @param version_number numeric The version number of the FileEntity to get
  # @return [OrgSagebionetworksRepoModelFileFileHandleResults]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetRepoV1EntityIdVersionVersionNumberFilepreview", {
  # tests for GetRepoV1EntityIdVersionVersionNumberFilepreview
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the FileEntity to get.
  # @param version_number numeric The version number of the FileEntity to get.
  # @param redirect character When set to false, the URL will be returned as                       text/plain instead of redirecting. (optional)
  # @return [AnyType]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetRepoV1EntityIdVersionVersionNumberGeneratedBy", {
  # tests for GetRepoV1EntityIdVersionVersionNumberGeneratedBy
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the entity to fetch.
  # @param version_number numeric the version of the entity
  # @return [OrgSagebionetworksRepoModelProvenanceActivity]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetRepoV1EntityIdVersionVersionNumberJson", {
  # tests for GetRepoV1EntityIdVersionVersionNumberJson
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character 
  # @param version_number numeric 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetRepoV1EntityMd5Md5", {
  # tests for GetRepoV1EntityMd5Md5
  # base path: https://repo-prod.prod.sagebase.org
  # @param md5 character 
  # @return [PaginatedResultsOfEntityHeader]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetRepoV1EntityType", {
  # tests for GetRepoV1EntityType
  # base path: https://repo-prod.prod.sagebase.org
  # @param batch character A comma separated list of Entity IDs to get EntityHeaders                      for.
  # @return [PaginatedResultsOfEntityHeader]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetRepoV1RESTResources", {
  # tests for GetRepoV1RESTResources
  # base path: https://repo-prod.prod.sagebase.org
  # @return [OrgSagebionetworksRepoModelRestResourceList]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetRepoV1RESTResourcesEffectiveSchema", {
  # tests for GetRepoV1RESTResourcesEffectiveSchema
  # base path: https://repo-prod.prod.sagebase.org
  # @param resource_id character The full name of the resource (see                    ,<a href=\"${GET.REST.resources}\">,GET /REST/resources,</a>, for                    the full list of names).
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetRepoV1RESTResourcesSchema", {
  # tests for GetRepoV1RESTResourcesSchema
  # base path: https://repo-prod.prod.sagebase.org
  # @param resource_id character The full name of the resource (see                    ,<a href=\"${GET.REST.resources}\">,GET /REST/resources,</a>, for                    the full list of names).
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PostRepoV1Entity", {
  # tests for PostRepoV1Entity
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_entity OrgSagebionetworksRepoModelEntity 
  # @param generated_by character To track the Provenance of an Entity create, include the                     ID of the ,<a href=\"${org.sagebionetworks.repo.model.provenance.Activity}\">,Activity,</a>, that was created to track the change. For                     more information see: ,<a href=\"${POST.activity}\">,POST                     /activity,</a>,. You must be the creator of the ,<a href=\"${org.sagebionetworks.repo.model.provenance.Activity}\">,Activity,</a>, used here. (optional)
  # @return [OrgSagebionetworksRepoModelEntity]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PostRepoV1EntityChild", {
  # tests for PostRepoV1EntityChild
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_entity_entity_lookup_request OrgSagebionetworksRepoModelEntityEntityLookupRequest 
  # @return [OrgSagebionetworksRepoModelEntityId]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PostRepoV1EntityChildren", {
  # tests for PostRepoV1EntityChildren
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_entity_children_request OrgSagebionetworksRepoModelEntityChildrenRequest 
  # @return [OrgSagebionetworksRepoModelEntityChildrenResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PostRepoV1EntityHeader", {
  # tests for PostRepoV1EntityHeader
  # base path: https://repo-prod.prod.sagebase.org
  # @param org_sagebionetworks_repo_model_request_reference_list OrgSagebionetworksRepoModelRequestReferenceList 
  # @return [PaginatedResultsOfEntityHeader]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PostRepoV1EntityIdAcl", {
  # tests for PostRepoV1EntityIdAcl
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the Entity to create an ACL for.
  # @param org_sagebionetworks_repo_model_access_control_list OrgSagebionetworksRepoModelAccessControlList 
  # @return [OrgSagebionetworksRepoModelAccessControlList]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PostRepoV1EntityIdSchemaValidationInvalid", {
  # tests for PostRepoV1EntityIdSchemaValidationInvalid
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the container Entity.
  # @param org_sagebionetworks_repo_model_schema_list_validation_results_request OrgSagebionetworksRepoModelSchemaListValidationResultsRequest 
  # @return [OrgSagebionetworksRepoModelSchemaListValidationResultsResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PutRepoV1EntityId", {
  # tests for PutRepoV1EntityId
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the entity to update. This ID must match the ID                     of the passed Entity in the request body.
  # @param org_sagebionetworks_repo_model_entity OrgSagebionetworksRepoModelEntity 
  # @param generated_by character To track the Provenance of an Entity update, include the                     ID of the ,<a href=\"${org.sagebionetworks.repo.model.provenance.Activity}\">,Activity,</a>, that was created to track the change. For                     more information see: ,<a href=\"${POST.activity}\">,POST                     /activity,</a>,. You must be the creator of the ,<a href=\"${org.sagebionetworks.repo.model.provenance.Activity}\">,Activity,</a>, used here. (optional)
  # @param new_version character To force the creation of a new version for a ,<a href=\"${org.sagebionetworks.repo.model.VersionableEntity}\">,versionable,</a>,                     entity such as a ,<a href=\"${org.sagebionetworks.repo.model.FileEntity}\">,FileEntity,</a>,,                     include this optional parameter with a value set to true                     (i.e. newVersion=true). This parameter is ignored for                     entities of type ,<a href=\"${org.sagebionetworks.repo.model.table.Table}\">,Table,</a>,                     (See ,<a href=\"${POST.entity.id.table.snapshot}\">,POST                     /entity/{id}/table/snapshot,</a>, instead) (optional)
  # @return [OrgSagebionetworksRepoModelEntity]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PutRepoV1EntityIdAcl", {
  # tests for PutRepoV1EntityIdAcl
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the Entity to create an ACL for.
  # @param org_sagebionetworks_repo_model_access_control_list OrgSagebionetworksRepoModelAccessControlList 
  # @return [OrgSagebionetworksRepoModelAccessControlList]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PutRepoV1EntityIdAnnotations2", {
  # tests for PutRepoV1EntityIdAnnotations2
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character - The id of the entity to update.
  # @param org_sagebionetworks_repo_model_annotation_v2_annotations OrgSagebionetworksRepoModelAnnotationV2Annotations 
  # @return [OrgSagebionetworksRepoModelAnnotationV2Annotations]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PutRepoV1EntityIdDatatype", {
  # tests for PutRepoV1EntityIdDatatype
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character 
  # @param type OrgSagebionetworksRepoModelDataType 
  # @return [OrgSagebionetworksRepoModelDataTypeResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PutRepoV1EntityIdGeneratedBy", {
  # tests for PutRepoV1EntityIdGeneratedBy
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The ID of the entity to update.
  # @param generated_by character The id of the activity to connect to the entity. You must                     be the creator of the ,<a href=\"${org.sagebionetworks.repo.model.provenance.Activity}\">,Activity,</a>, used here.
  # @return [OrgSagebionetworksRepoModelProvenanceActivity]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PutRepoV1EntityIdJson", {
  # tests for PutRepoV1EntityIdJson
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character 
  # @param body object 
  # @return [object]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PutRepoV1EntityIdSchemaBinding", {
  # tests for PutRepoV1EntityIdSchemaBinding
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The syn ID of the entity to bind.
  # @param org_sagebionetworks_repo_model_entity_bind_schema_to_entity_request OrgSagebionetworksRepoModelEntityBindSchemaToEntityRequest 
  # @return [OrgSagebionetworksRepoModelSchemaJsonSchemaObjectBinding]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PutRepoV1EntityIdVersionVersionNumberFilehandle", {
  # tests for PutRepoV1EntityIdVersionVersionNumberFilehandle
  # base path: https://repo-prod.prod.sagebase.org
  # @param id character The id of the file entity
  # @param version_number numeric The entity version
  # @param org_sagebionetworks_repo_model_entity_file_handle_update_request OrgSagebionetworksRepoModelEntityFileHandleUpdateRequest 
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
