# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelMigrationIdRange")

model_instance <- OrgSagebionetworksRepoModelMigrationIdRange$new()

test_that("minimumId", {
  # tests for the property `minimumId` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`minimumId`, "EXPECTED_RESULT")
})

test_that("maximumId", {
  # tests for the property `maximumId` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`maximumId`, "EXPECTED_RESULT")
})
