# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelPrincipalAliasList")

model_instance <- OrgSagebionetworksRepoModelPrincipalAliasList$new()

test_that("list", {
  # tests for the property `list` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`list`, "EXPECTED_RESULT")
})
