# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test User38GroupServicesApi")

api_instance <- User38GroupServicesApi$new()

test_that("GetRepoV1UserGroup", {
  # tests for GetRepoV1UserGroup
  # base path: https://repo-prod.prod.sagebase.org
  # @param offset integer  (optional)
  # @param limit integer  (optional)
  # @param sort character  (optional)
  # @param ascending character  (optional)
  # @return [PaginatedResultsOfUserGroup]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
