# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrgSagebionetworksRepoModelFileBaseKeyUploadDestination")

model_instance <- OrgSagebionetworksRepoModelFileBaseKeyUploadDestination$new()

test_that("concreteType", {
  # tests for the property `concreteType` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`concreteType`, "EXPECTED_RESULT")
})

test_that("storageLocationId", {
  # tests for the property `storageLocationId` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`storageLocationId`, "EXPECTED_RESULT")
})

test_that("uploadType", {
  # tests for the property `uploadType` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`uploadType`, "EXPECTED_RESULT")
})

test_that("banner", {
  # tests for the property `banner` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`banner`, "EXPECTED_RESULT")
})

test_that("baseKey", {
  # tests for the property `baseKey` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`baseKey`, "EXPECTED_RESULT")
})

test_that("stsEnabled", {
  # tests for the property `stsEnabled` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`stsEnabled`, "EXPECTED_RESULT")
})

test_that("endpointUrl", {
  # tests for the property `endpointUrl` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`endpointUrl`, "EXPECTED_RESULT")
})

test_that("bucket", {
  # tests for the property `bucket` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`bucket`, "EXPECTED_RESULT")
})
