# Platform Repository Service
#
# Platform Repository Service - Sage Bionetworks Platform 
#
# The version of the OpenAPI document: develop-SNAPSHOT
# Contact: thomas.yu@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title AccessApproval
#'
#' @description AccessApproval Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field accessorId  character [optional]
#'
#' @field createdBy  character [optional]
#'
#' @field createdOn  character [optional]
#'
#' @field etag  character [optional]
#'
#' @field expiredOn  character [optional]
#'
#' @field id  integer [optional]
#'
#' @field modifiedBy  character [optional]
#'
#' @field modifiedOn  character [optional]
#'
#' @field requirementId  integer [optional]
#'
#' @field requirementVersion  integer [optional]
#'
#' @field state  \link{ApprovalState} [optional]
#'
#' @field submitterId  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
AccessApproval <- R6::R6Class(
  'AccessApproval',
  public = list(
    `accessorId` = NULL,
    `createdBy` = NULL,
    `createdOn` = NULL,
    `etag` = NULL,
    `expiredOn` = NULL,
    `id` = NULL,
    `modifiedBy` = NULL,
    `modifiedOn` = NULL,
    `requirementId` = NULL,
    `requirementVersion` = NULL,
    `state` = NULL,
    `submitterId` = NULL,
    initialize = function(
        `accessorId`=NULL, `createdBy`=NULL, `createdOn`=NULL, `etag`=NULL, `expiredOn`=NULL, `id`=NULL, `modifiedBy`=NULL, `modifiedOn`=NULL, `requirementId`=NULL, `requirementVersion`=NULL, `state`=NULL, `submitterId`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`accessorId`)) {
        stopifnot(is.character(`accessorId`), length(`accessorId`) == 1)
        self$`accessorId` <- `accessorId`
      }
      if (!is.null(`createdBy`)) {
        stopifnot(is.character(`createdBy`), length(`createdBy`) == 1)
        self$`createdBy` <- `createdBy`
      }
      if (!is.null(`createdOn`)) {
        stopifnot(is.character(`createdOn`), length(`createdOn`) == 1)
        self$`createdOn` <- `createdOn`
      }
      if (!is.null(`etag`)) {
        stopifnot(is.character(`etag`), length(`etag`) == 1)
        self$`etag` <- `etag`
      }
      if (!is.null(`expiredOn`)) {
        stopifnot(is.character(`expiredOn`), length(`expiredOn`) == 1)
        self$`expiredOn` <- `expiredOn`
      }
      if (!is.null(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`modifiedBy`)) {
        stopifnot(is.character(`modifiedBy`), length(`modifiedBy`) == 1)
        self$`modifiedBy` <- `modifiedBy`
      }
      if (!is.null(`modifiedOn`)) {
        stopifnot(is.character(`modifiedOn`), length(`modifiedOn`) == 1)
        self$`modifiedOn` <- `modifiedOn`
      }
      if (!is.null(`requirementId`)) {
        stopifnot(is.numeric(`requirementId`), length(`requirementId`) == 1)
        self$`requirementId` <- `requirementId`
      }
      if (!is.null(`requirementVersion`)) {
        stopifnot(is.numeric(`requirementVersion`), length(`requirementVersion`) == 1)
        self$`requirementVersion` <- `requirementVersion`
      }
      if (!is.null(`state`)) {
        stopifnot(R6::is.R6(`state`))
        self$`state` <- `state`
      }
      if (!is.null(`submitterId`)) {
        stopifnot(is.character(`submitterId`), length(`submitterId`) == 1)
        self$`submitterId` <- `submitterId`
      }
    },
    toJSON = function() {
      AccessApprovalObject <- list()
      if (!is.null(self$`accessorId`)) {
        AccessApprovalObject[['accessorId']] <-
          self$`accessorId`
      }
      if (!is.null(self$`createdBy`)) {
        AccessApprovalObject[['createdBy']] <-
          self$`createdBy`
      }
      if (!is.null(self$`createdOn`)) {
        AccessApprovalObject[['createdOn']] <-
          self$`createdOn`
      }
      if (!is.null(self$`etag`)) {
        AccessApprovalObject[['etag']] <-
          self$`etag`
      }
      if (!is.null(self$`expiredOn`)) {
        AccessApprovalObject[['expiredOn']] <-
          self$`expiredOn`
      }
      if (!is.null(self$`id`)) {
        AccessApprovalObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`modifiedBy`)) {
        AccessApprovalObject[['modifiedBy']] <-
          self$`modifiedBy`
      }
      if (!is.null(self$`modifiedOn`)) {
        AccessApprovalObject[['modifiedOn']] <-
          self$`modifiedOn`
      }
      if (!is.null(self$`requirementId`)) {
        AccessApprovalObject[['requirementId']] <-
          self$`requirementId`
      }
      if (!is.null(self$`requirementVersion`)) {
        AccessApprovalObject[['requirementVersion']] <-
          self$`requirementVersion`
      }
      if (!is.null(self$`state`)) {
        AccessApprovalObject[['state']] <-
          self$`state`$toJSON()
      }
      if (!is.null(self$`submitterId`)) {
        AccessApprovalObject[['submitterId']] <-
          self$`submitterId`
      }

      AccessApprovalObject
    },
    fromJSON = function(AccessApprovalJson) {
      AccessApprovalObject <- jsonlite::fromJSON(AccessApprovalJson)
      if (!is.null(AccessApprovalObject$`accessorId`)) {
        self$`accessorId` <- AccessApprovalObject$`accessorId`
      }
      if (!is.null(AccessApprovalObject$`createdBy`)) {
        self$`createdBy` <- AccessApprovalObject$`createdBy`
      }
      if (!is.null(AccessApprovalObject$`createdOn`)) {
        self$`createdOn` <- AccessApprovalObject$`createdOn`
      }
      if (!is.null(AccessApprovalObject$`etag`)) {
        self$`etag` <- AccessApprovalObject$`etag`
      }
      if (!is.null(AccessApprovalObject$`expiredOn`)) {
        self$`expiredOn` <- AccessApprovalObject$`expiredOn`
      }
      if (!is.null(AccessApprovalObject$`id`)) {
        self$`id` <- AccessApprovalObject$`id`
      }
      if (!is.null(AccessApprovalObject$`modifiedBy`)) {
        self$`modifiedBy` <- AccessApprovalObject$`modifiedBy`
      }
      if (!is.null(AccessApprovalObject$`modifiedOn`)) {
        self$`modifiedOn` <- AccessApprovalObject$`modifiedOn`
      }
      if (!is.null(AccessApprovalObject$`requirementId`)) {
        self$`requirementId` <- AccessApprovalObject$`requirementId`
      }
      if (!is.null(AccessApprovalObject$`requirementVersion`)) {
        self$`requirementVersion` <- AccessApprovalObject$`requirementVersion`
      }
      if (!is.null(AccessApprovalObject$`state`)) {
        stateObject <- ApprovalState$new()
        stateObject$fromJSON(jsonlite::toJSON(AccessApprovalObject$state, auto_unbox = TRUE, digits = NA))
        self$`state` <- stateObject
      }
      if (!is.null(AccessApprovalObject$`submitterId`)) {
        self$`submitterId` <- AccessApprovalObject$`submitterId`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`accessorId`)) {
        sprintf(
        '"accessorId":
          "%s"
                ',
        self$`accessorId`
        )},
        if (!is.null(self$`createdBy`)) {
        sprintf(
        '"createdBy":
          "%s"
                ',
        self$`createdBy`
        )},
        if (!is.null(self$`createdOn`)) {
        sprintf(
        '"createdOn":
          "%s"
                ',
        self$`createdOn`
        )},
        if (!is.null(self$`etag`)) {
        sprintf(
        '"etag":
          "%s"
                ',
        self$`etag`
        )},
        if (!is.null(self$`expiredOn`)) {
        sprintf(
        '"expiredOn":
          "%s"
                ',
        self$`expiredOn`
        )},
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          %d
                ',
        self$`id`
        )},
        if (!is.null(self$`modifiedBy`)) {
        sprintf(
        '"modifiedBy":
          "%s"
                ',
        self$`modifiedBy`
        )},
        if (!is.null(self$`modifiedOn`)) {
        sprintf(
        '"modifiedOn":
          "%s"
                ',
        self$`modifiedOn`
        )},
        if (!is.null(self$`requirementId`)) {
        sprintf(
        '"requirementId":
          %d
                ',
        self$`requirementId`
        )},
        if (!is.null(self$`requirementVersion`)) {
        sprintf(
        '"requirementVersion":
          %d
                ',
        self$`requirementVersion`
        )},
        if (!is.null(self$`state`)) {
        sprintf(
        '"state":
        %s
        ',
        jsonlite::toJSON(self$`state`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`submitterId`)) {
        sprintf(
        '"submitterId":
          "%s"
                ',
        self$`submitterId`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(AccessApprovalJson) {
      AccessApprovalObject <- jsonlite::fromJSON(AccessApprovalJson)
      self$`accessorId` <- AccessApprovalObject$`accessorId`
      self$`createdBy` <- AccessApprovalObject$`createdBy`
      self$`createdOn` <- AccessApprovalObject$`createdOn`
      self$`etag` <- AccessApprovalObject$`etag`
      self$`expiredOn` <- AccessApprovalObject$`expiredOn`
      self$`id` <- AccessApprovalObject$`id`
      self$`modifiedBy` <- AccessApprovalObject$`modifiedBy`
      self$`modifiedOn` <- AccessApprovalObject$`modifiedOn`
      self$`requirementId` <- AccessApprovalObject$`requirementId`
      self$`requirementVersion` <- AccessApprovalObject$`requirementVersion`
      self$`state` <- ApprovalState$new()$fromJSON(jsonlite::toJSON(AccessApprovalObject$state, auto_unbox = TRUE, digits = NA))
      self$`submitterId` <- AccessApprovalObject$`submitterId`
      self
    }
  )
)

