# Platform Repository Service
#
# Platform Repository Service - Sage Bionetworks Platform 
#
# The version of the OpenAPI document: develop-SNAPSHOT
# Contact: thomas.yu@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title AliasList
#'
#' @description AliasList Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field list  list( character ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
AliasList <- R6::R6Class(
  'AliasList',
  public = list(
    `list` = NULL,
    initialize = function(
        `list`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`list`)) {
        stopifnot(is.vector(`list`), length(`list`) != 0)
        sapply(`list`, function(x) stopifnot(is.character(x)))
        self$`list` <- `list`
      }
    },
    toJSON = function() {
      AliasListObject <- list()
      if (!is.null(self$`list`)) {
        AliasListObject[['list']] <-
          self$`list`
      }

      AliasListObject
    },
    fromJSON = function(AliasListJson) {
      AliasListObject <- jsonlite::fromJSON(AliasListJson)
      if (!is.null(AliasListObject$`list`)) {
        self$`list` <- ApiClient$new()$deserializeObj(AliasListObject$`list`, "array[character]", loadNamespace("synclient"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`list`)) {
        sprintf(
        '"list":
           [%s]
        ',
        paste(unlist(lapply(self$`list`, function(x) paste0('"', x, '"'))), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(AliasListJson) {
      AliasListObject <- jsonlite::fromJSON(AliasListJson)
      self$`list` <- ApiClient$new()$deserializeObj(AliasListObject$`list`, "array[character]", loadNamespace("synclient"))
      self
    }
  )
)

