# Platform Repository Service
#
# Platform Repository Service - Sage Bionetworks Platform 
#
# The version of the OpenAPI document: develop-SNAPSHOT
# Contact: thomas.yu@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title AnnotationsValue
#'
#' @description AnnotationsValue Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field type  \link{AnnotationsValueType} [optional]
#'
#' @field value  list( character ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
AnnotationsValue <- R6::R6Class(
  'AnnotationsValue',
  public = list(
    `type` = NULL,
    `value` = NULL,
    initialize = function(
        `type`=NULL, `value`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`type`)) {
        stopifnot(R6::is.R6(`type`))
        self$`type` <- `type`
      }
      if (!is.null(`value`)) {
        stopifnot(is.vector(`value`), length(`value`) != 0)
        sapply(`value`, function(x) stopifnot(is.character(x)))
        self$`value` <- `value`
      }
    },
    toJSON = function() {
      AnnotationsValueObject <- list()
      if (!is.null(self$`type`)) {
        AnnotationsValueObject[['type']] <-
          self$`type`$toJSON()
      }
      if (!is.null(self$`value`)) {
        AnnotationsValueObject[['value']] <-
          self$`value`
      }

      AnnotationsValueObject
    },
    fromJSON = function(AnnotationsValueJson) {
      AnnotationsValueObject <- jsonlite::fromJSON(AnnotationsValueJson)
      if (!is.null(AnnotationsValueObject$`type`)) {
        typeObject <- AnnotationsValueType$new()
        typeObject$fromJSON(jsonlite::toJSON(AnnotationsValueObject$type, auto_unbox = TRUE, digits = NA))
        self$`type` <- typeObject
      }
      if (!is.null(AnnotationsValueObject$`value`)) {
        self$`value` <- ApiClient$new()$deserializeObj(AnnotationsValueObject$`value`, "array[character]", loadNamespace("synclient"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`type`)) {
        sprintf(
        '"type":
        %s
        ',
        jsonlite::toJSON(self$`type`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`value`)) {
        sprintf(
        '"value":
           [%s]
        ',
        paste(unlist(lapply(self$`value`, function(x) paste0('"', x, '"'))), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(AnnotationsValueJson) {
      AnnotationsValueObject <- jsonlite::fromJSON(AnnotationsValueJson)
      self$`type` <- AnnotationsValueType$new()$fromJSON(jsonlite::toJSON(AnnotationsValueObject$type, auto_unbox = TRUE, digits = NA))
      self$`value` <- ApiClient$new()$deserializeObj(AnnotationsValueObject$`value`, "array[character]", loadNamespace("synclient"))
      self
    }
  )
)

