# Platform Repository Service
#
# Platform Repository Service - Sage Bionetworks Platform 
#
# The version of the OpenAPI document: develop-SNAPSHOT
# Contact: thomas.yu@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title BatchAccessApprovalInfoRequest
#'
#' @description BatchAccessApprovalInfoRequest Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field accessRequirementIds  list( character ) [optional]
#'
#' @field userId  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
BatchAccessApprovalInfoRequest <- R6::R6Class(
  'BatchAccessApprovalInfoRequest',
  public = list(
    `accessRequirementIds` = NULL,
    `userId` = NULL,
    initialize = function(
        `accessRequirementIds`=NULL, `userId`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`accessRequirementIds`)) {
        stopifnot(is.vector(`accessRequirementIds`), length(`accessRequirementIds`) != 0)
        sapply(`accessRequirementIds`, function(x) stopifnot(is.character(x)))
        self$`accessRequirementIds` <- `accessRequirementIds`
      }
      if (!is.null(`userId`)) {
        stopifnot(is.character(`userId`), length(`userId`) == 1)
        self$`userId` <- `userId`
      }
    },
    toJSON = function() {
      BatchAccessApprovalInfoRequestObject <- list()
      if (!is.null(self$`accessRequirementIds`)) {
        BatchAccessApprovalInfoRequestObject[['accessRequirementIds']] <-
          self$`accessRequirementIds`
      }
      if (!is.null(self$`userId`)) {
        BatchAccessApprovalInfoRequestObject[['userId']] <-
          self$`userId`
      }

      BatchAccessApprovalInfoRequestObject
    },
    fromJSON = function(BatchAccessApprovalInfoRequestJson) {
      BatchAccessApprovalInfoRequestObject <- jsonlite::fromJSON(BatchAccessApprovalInfoRequestJson)
      if (!is.null(BatchAccessApprovalInfoRequestObject$`accessRequirementIds`)) {
        self$`accessRequirementIds` <- ApiClient$new()$deserializeObj(BatchAccessApprovalInfoRequestObject$`accessRequirementIds`, "array[character]", loadNamespace("synclient"))
      }
      if (!is.null(BatchAccessApprovalInfoRequestObject$`userId`)) {
        self$`userId` <- BatchAccessApprovalInfoRequestObject$`userId`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`accessRequirementIds`)) {
        sprintf(
        '"accessRequirementIds":
           [%s]
        ',
        paste(unlist(lapply(self$`accessRequirementIds`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`userId`)) {
        sprintf(
        '"userId":
          "%s"
                ',
        self$`userId`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(BatchAccessApprovalInfoRequestJson) {
      BatchAccessApprovalInfoRequestObject <- jsonlite::fromJSON(BatchAccessApprovalInfoRequestJson)
      self$`accessRequirementIds` <- ApiClient$new()$deserializeObj(BatchAccessApprovalInfoRequestObject$`accessRequirementIds`, "array[character]", loadNamespace("synclient"))
      self$`userId` <- BatchAccessApprovalInfoRequestObject$`userId`
      self
    }
  )
)

