# Platform Repository Service
#
# Platform Repository Service - Sage Bionetworks Platform 
#
# The version of the OpenAPI document: develop-SNAPSHOT
# Contact: thomas.yu@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title BoundObjectType
#' @description BoundObjectType Class
#' @format An \code{R6Class} generator object
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
BoundObjectType <- R6::R6Class(
  'BoundObjectType',
  public = list(
    initialize = function(...){
      local.optional.var <- list(...)
    },
    toJSON = function() {
      BoundObjectTypeObject <- list()

      BoundObjectTypeObject
    },
    fromJSON = function(BoundObjectTypeJson) {
      BoundObjectTypeObject <- jsonlite::fromJSON(BoundObjectTypeJson)
    },
    toJSONString = function() {
      jsoncontent <- c(
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(BoundObjectTypeJson) {
      BoundObjectTypeObject <- jsonlite::fromJSON(BoundObjectTypeJson)
      self
    }
  )
)
