# Platform Repository Service
#
# Platform Repository Service - Sage Bionetworks Platform 
#
# The version of the OpenAPI document: develop-SNAPSHOT
# Contact: thomas.yu@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Challenge
#' @description Challenge Class
#' @format An \code{R6Class} generator object
#' @field etag  character [optional]
#'
#' @field projectId  character [optional]
#'
#' @field participantTeamId  character [optional]
#'
#' @field id  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Challenge <- R6::R6Class(
  'Challenge',
  public = list(
    `etag` = NULL,
    `projectId` = NULL,
    `participantTeamId` = NULL,
    `id` = NULL,
    initialize = function(`etag`=NULL, `projectId`=NULL, `participantTeamId`=NULL, `id`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`etag`)) {
        stopifnot(is.character(`etag`), length(`etag`) == 1)
        self$`etag` <- `etag`
      }
      if (!is.null(`projectId`)) {
        stopifnot(is.character(`projectId`), length(`projectId`) == 1)
        self$`projectId` <- `projectId`
      }
      if (!is.null(`participantTeamId`)) {
        stopifnot(is.character(`participantTeamId`), length(`participantTeamId`) == 1)
        self$`participantTeamId` <- `participantTeamId`
      }
      if (!is.null(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
    },
    toJSON = function() {
      ChallengeObject <- list()
      if (!is.null(self$`etag`)) {
        ChallengeObject[['etag']] <-
          self$`etag`
      }
      if (!is.null(self$`projectId`)) {
        ChallengeObject[['projectId']] <-
          self$`projectId`
      }
      if (!is.null(self$`participantTeamId`)) {
        ChallengeObject[['participantTeamId']] <-
          self$`participantTeamId`
      }
      if (!is.null(self$`id`)) {
        ChallengeObject[['id']] <-
          self$`id`
      }

      ChallengeObject
    },
    fromJSON = function(ChallengeJson) {
      ChallengeObject <- jsonlite::fromJSON(ChallengeJson)
      if (!is.null(ChallengeObject$`etag`)) {
        self$`etag` <- ChallengeObject$`etag`
      }
      if (!is.null(ChallengeObject$`projectId`)) {
        self$`projectId` <- ChallengeObject$`projectId`
      }
      if (!is.null(ChallengeObject$`participantTeamId`)) {
        self$`participantTeamId` <- ChallengeObject$`participantTeamId`
      }
      if (!is.null(ChallengeObject$`id`)) {
        self$`id` <- ChallengeObject$`id`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`etag`)) {
        sprintf(
        '"etag":
          "%s"
                ',
        self$`etag`
        )},
        if (!is.null(self$`projectId`)) {
        sprintf(
        '"projectId":
          "%s"
                ',
        self$`projectId`
        )},
        if (!is.null(self$`participantTeamId`)) {
        sprintf(
        '"participantTeamId":
          "%s"
                ',
        self$`participantTeamId`
        )},
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ChallengeJson) {
      ChallengeObject <- jsonlite::fromJSON(ChallengeJson)
      self$`etag` <- ChallengeObject$`etag`
      self$`projectId` <- ChallengeObject$`projectId`
      self$`participantTeamId` <- ChallengeObject$`participantTeamId`
      self$`id` <- ChallengeObject$`id`
      self
    }
  )
)
