# Platform Repository Service
#
# Platform Repository Service - Sage Bionetworks Platform 
#
# The version of the OpenAPI document: develop-SNAPSHOT
# Contact: thomas.yu@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title DoiAllOf
#' @description DoiAllOf Class
#' @format An \code{R6Class} generator object
#' @field creators  list( \link{DoiCreator} ) [optional]
#'
#' @field publicationYear  integer [optional]
#'
#' @field resourceType  \link{DoiResourceType} [optional]
#'
#' @field titles  list( \link{DoiTitle} ) [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
DoiAllOf <- R6::R6Class(
  'DoiAllOf',
  public = list(
    `creators` = NULL,
    `publicationYear` = NULL,
    `resourceType` = NULL,
    `titles` = NULL,
    initialize = function(`creators`=NULL, `publicationYear`=NULL, `resourceType`=NULL, `titles`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`creators`)) {
        stopifnot(is.vector(`creators`), length(`creators`) != 0)
        sapply(`creators`, function(x) stopifnot(R6::is.R6(x)))
        self$`creators` <- `creators`
      }
      if (!is.null(`publicationYear`)) {
        stopifnot(is.numeric(`publicationYear`), length(`publicationYear`) == 1)
        self$`publicationYear` <- `publicationYear`
      }
      if (!is.null(`resourceType`)) {
        stopifnot(R6::is.R6(`resourceType`))
        self$`resourceType` <- `resourceType`
      }
      if (!is.null(`titles`)) {
        stopifnot(is.vector(`titles`), length(`titles`) != 0)
        sapply(`titles`, function(x) stopifnot(R6::is.R6(x)))
        self$`titles` <- `titles`
      }
    },
    toJSON = function() {
      DoiAllOfObject <- list()
      if (!is.null(self$`creators`)) {
        DoiAllOfObject[['creators']] <-
          lapply(self$`creators`, function(x) x$toJSON())
      }
      if (!is.null(self$`publicationYear`)) {
        DoiAllOfObject[['publicationYear']] <-
          self$`publicationYear`
      }
      if (!is.null(self$`resourceType`)) {
        DoiAllOfObject[['resourceType']] <-
          self$`resourceType`$toJSON()
      }
      if (!is.null(self$`titles`)) {
        DoiAllOfObject[['titles']] <-
          lapply(self$`titles`, function(x) x$toJSON())
      }

      DoiAllOfObject
    },
    fromJSON = function(DoiAllOfJson) {
      DoiAllOfObject <- jsonlite::fromJSON(DoiAllOfJson)
      if (!is.null(DoiAllOfObject$`creators`)) {
        self$`creators` <- ApiClient$new()$deserializeObj(DoiAllOfObject$`creators`, "array[DoiCreator]", loadNamespace("synclient"))
      }
      if (!is.null(DoiAllOfObject$`publicationYear`)) {
        self$`publicationYear` <- DoiAllOfObject$`publicationYear`
      }
      if (!is.null(DoiAllOfObject$`resourceType`)) {
        resourceTypeObject <- DoiResourceType$new()
        resourceTypeObject$fromJSON(jsonlite::toJSON(DoiAllOfObject$resourceType, auto_unbox = TRUE, digits = NA))
        self$`resourceType` <- resourceTypeObject
      }
      if (!is.null(DoiAllOfObject$`titles`)) {
        self$`titles` <- ApiClient$new()$deserializeObj(DoiAllOfObject$`titles`, "array[DoiTitle]", loadNamespace("synclient"))
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`creators`)) {
        sprintf(
        '"creators":
        [%s]
',
        paste(sapply(self$`creators`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`publicationYear`)) {
        sprintf(
        '"publicationYear":
          %d
                ',
        self$`publicationYear`
        )},
        if (!is.null(self$`resourceType`)) {
        sprintf(
        '"resourceType":
        %s
        ',
        jsonlite::toJSON(self$`resourceType`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`titles`)) {
        sprintf(
        '"titles":
        [%s]
',
        paste(sapply(self$`titles`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(DoiAllOfJson) {
      DoiAllOfObject <- jsonlite::fromJSON(DoiAllOfJson)
      self$`creators` <- ApiClient$new()$deserializeObj(DoiAllOfObject$`creators`, "array[DoiCreator]", loadNamespace("synclient"))
      self$`publicationYear` <- DoiAllOfObject$`publicationYear`
      self$`resourceType` <- DoiResourceType$new()$fromJSON(jsonlite::toJSON(DoiAllOfObject$resourceType, auto_unbox = TRUE, digits = NA))
      self$`titles` <- ApiClient$new()$deserializeObj(DoiAllOfObject$`titles`, "array[DoiTitle]", loadNamespace("synclient"))
      self
    }
  )
)
