# Platform Repository Service
#
# Platform Repository Service - Sage Bionetworks Platform 
#
# The version of the OpenAPI document: develop-SNAPSHOT
# Contact: thomas.yu@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title DownloadFromTableRequest
#' @description DownloadFromTableRequest Class
#' @format An \code{R6Class} generator object
#' @field additionalFilters  list( object ) [optional]
#'
#' @field includeEntityEtag  character [optional]
#'
#' @field limit  integer [optional]
#'
#' @field offset  integer [optional]
#'
#' @field selectedFacets  list( \link{FacetColumnRequest} ) [optional]
#'
#' @field sort  list( \link{SortItem} ) [optional]
#'
#' @field sql  character [optional]
#'
#' @field concreteType  character [optional]
#'
#' @field csvTableDescriptor  \link{CsvTableDescriptor} [optional]
#'
#' @field entityId  character [optional]
#'
#' @field includeRowIdAndRowVersion  character [optional]
#'
#' @field writeHeader  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
DownloadFromTableRequest <- R6::R6Class(
  'DownloadFromTableRequest',
  public = list(
    `additionalFilters` = NULL,
    `includeEntityEtag` = NULL,
    `limit` = NULL,
    `offset` = NULL,
    `selectedFacets` = NULL,
    `sort` = NULL,
    `sql` = NULL,
    `concreteType` = NULL,
    `csvTableDescriptor` = NULL,
    `entityId` = NULL,
    `includeRowIdAndRowVersion` = NULL,
    `writeHeader` = NULL,
    initialize = function(`additionalFilters`=NULL, `includeEntityEtag`=NULL, `limit`=NULL, `offset`=NULL, `selectedFacets`=NULL, `sort`=NULL, `sql`=NULL, `concreteType`=NULL, `csvTableDescriptor`=NULL, `entityId`=NULL, `includeRowIdAndRowVersion`=TRUE, `writeHeader`=TRUE, ...){
      local.optional.var <- list(...)
      if (!is.null(`additionalFilters`)) {
        stopifnot(is.vector(`additionalFilters`), length(`additionalFilters`) != 0)
        sapply(`additionalFilters`, function(x) stopifnot(is.character(x)))
        self$`additionalFilters` <- `additionalFilters`
      }
      if (!is.null(`includeEntityEtag`)) {
        self$`includeEntityEtag` <- `includeEntityEtag`
      }
      if (!is.null(`limit`)) {
        stopifnot(is.numeric(`limit`), length(`limit`) == 1)
        self$`limit` <- `limit`
      }
      if (!is.null(`offset`)) {
        stopifnot(is.numeric(`offset`), length(`offset`) == 1)
        self$`offset` <- `offset`
      }
      if (!is.null(`selectedFacets`)) {
        stopifnot(is.vector(`selectedFacets`), length(`selectedFacets`) != 0)
        sapply(`selectedFacets`, function(x) stopifnot(R6::is.R6(x)))
        self$`selectedFacets` <- `selectedFacets`
      }
      if (!is.null(`sort`)) {
        stopifnot(is.vector(`sort`), length(`sort`) != 0)
        sapply(`sort`, function(x) stopifnot(R6::is.R6(x)))
        self$`sort` <- `sort`
      }
      if (!is.null(`sql`)) {
        stopifnot(is.character(`sql`), length(`sql`) == 1)
        self$`sql` <- `sql`
      }
      if (!is.null(`concreteType`)) {
        stopifnot(is.character(`concreteType`), length(`concreteType`) == 1)
        self$`concreteType` <- `concreteType`
      }
      if (!is.null(`csvTableDescriptor`)) {
        stopifnot(R6::is.R6(`csvTableDescriptor`))
        self$`csvTableDescriptor` <- `csvTableDescriptor`
      }
      if (!is.null(`entityId`)) {
        stopifnot(is.character(`entityId`), length(`entityId`) == 1)
        self$`entityId` <- `entityId`
      }
      if (!is.null(`includeRowIdAndRowVersion`)) {
        self$`includeRowIdAndRowVersion` <- `includeRowIdAndRowVersion`
      }
      if (!is.null(`writeHeader`)) {
        self$`writeHeader` <- `writeHeader`
      }
    },
    toJSON = function() {
      DownloadFromTableRequestObject <- list()
      if (!is.null(self$`additionalFilters`)) {
        DownloadFromTableRequestObject[['additionalFilters']] <-
          self$`additionalFilters`
      }
      if (!is.null(self$`includeEntityEtag`)) {
        DownloadFromTableRequestObject[['includeEntityEtag']] <-
          self$`includeEntityEtag`
      }
      if (!is.null(self$`limit`)) {
        DownloadFromTableRequestObject[['limit']] <-
          self$`limit`
      }
      if (!is.null(self$`offset`)) {
        DownloadFromTableRequestObject[['offset']] <-
          self$`offset`
      }
      if (!is.null(self$`selectedFacets`)) {
        DownloadFromTableRequestObject[['selectedFacets']] <-
          lapply(self$`selectedFacets`, function(x) x$toJSON())
      }
      if (!is.null(self$`sort`)) {
        DownloadFromTableRequestObject[['sort']] <-
          lapply(self$`sort`, function(x) x$toJSON())
      }
      if (!is.null(self$`sql`)) {
        DownloadFromTableRequestObject[['sql']] <-
          self$`sql`
      }
      if (!is.null(self$`concreteType`)) {
        DownloadFromTableRequestObject[['concreteType']] <-
          self$`concreteType`
      }
      if (!is.null(self$`csvTableDescriptor`)) {
        DownloadFromTableRequestObject[['csvTableDescriptor']] <-
          self$`csvTableDescriptor`$toJSON()
      }
      if (!is.null(self$`entityId`)) {
        DownloadFromTableRequestObject[['entityId']] <-
          self$`entityId`
      }
      if (!is.null(self$`includeRowIdAndRowVersion`)) {
        DownloadFromTableRequestObject[['includeRowIdAndRowVersion']] <-
          self$`includeRowIdAndRowVersion`
      }
      if (!is.null(self$`writeHeader`)) {
        DownloadFromTableRequestObject[['writeHeader']] <-
          self$`writeHeader`
      }

      DownloadFromTableRequestObject
    },
    fromJSON = function(DownloadFromTableRequestJson) {
      DownloadFromTableRequestObject <- jsonlite::fromJSON(DownloadFromTableRequestJson)
      if (!is.null(DownloadFromTableRequestObject$`additionalFilters`)) {
        self$`additionalFilters` <- ApiClient$new()$deserializeObj(DownloadFromTableRequestObject$`additionalFilters`, "array[object]", loadNamespace("synclient"))
      }
      if (!is.null(DownloadFromTableRequestObject$`includeEntityEtag`)) {
        self$`includeEntityEtag` <- DownloadFromTableRequestObject$`includeEntityEtag`
      }
      if (!is.null(DownloadFromTableRequestObject$`limit`)) {
        self$`limit` <- DownloadFromTableRequestObject$`limit`
      }
      if (!is.null(DownloadFromTableRequestObject$`offset`)) {
        self$`offset` <- DownloadFromTableRequestObject$`offset`
      }
      if (!is.null(DownloadFromTableRequestObject$`selectedFacets`)) {
        self$`selectedFacets` <- ApiClient$new()$deserializeObj(DownloadFromTableRequestObject$`selectedFacets`, "array[FacetColumnRequest]", loadNamespace("synclient"))
      }
      if (!is.null(DownloadFromTableRequestObject$`sort`)) {
        self$`sort` <- ApiClient$new()$deserializeObj(DownloadFromTableRequestObject$`sort`, "array[SortItem]", loadNamespace("synclient"))
      }
      if (!is.null(DownloadFromTableRequestObject$`sql`)) {
        self$`sql` <- DownloadFromTableRequestObject$`sql`
      }
      if (!is.null(DownloadFromTableRequestObject$`concreteType`)) {
        self$`concreteType` <- DownloadFromTableRequestObject$`concreteType`
      }
      if (!is.null(DownloadFromTableRequestObject$`csvTableDescriptor`)) {
        csvTableDescriptorObject <- CsvTableDescriptor$new()
        csvTableDescriptorObject$fromJSON(jsonlite::toJSON(DownloadFromTableRequestObject$csvTableDescriptor, auto_unbox = TRUE, digits = NA))
        self$`csvTableDescriptor` <- csvTableDescriptorObject
      }
      if (!is.null(DownloadFromTableRequestObject$`entityId`)) {
        self$`entityId` <- DownloadFromTableRequestObject$`entityId`
      }
      if (!is.null(DownloadFromTableRequestObject$`includeRowIdAndRowVersion`)) {
        self$`includeRowIdAndRowVersion` <- DownloadFromTableRequestObject$`includeRowIdAndRowVersion`
      }
      if (!is.null(DownloadFromTableRequestObject$`writeHeader`)) {
        self$`writeHeader` <- DownloadFromTableRequestObject$`writeHeader`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`additionalFilters`)) {
        sprintf(
        '"additionalFilters":
           [%s]
        ',
        paste(unlist(lapply(self$`additionalFilters`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`includeEntityEtag`)) {
        sprintf(
        '"includeEntityEtag":
          "%s"
                ',
        self$`includeEntityEtag`
        )},
        if (!is.null(self$`limit`)) {
        sprintf(
        '"limit":
          %d
                ',
        self$`limit`
        )},
        if (!is.null(self$`offset`)) {
        sprintf(
        '"offset":
          %d
                ',
        self$`offset`
        )},
        if (!is.null(self$`selectedFacets`)) {
        sprintf(
        '"selectedFacets":
        [%s]
',
        paste(sapply(self$`selectedFacets`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`sort`)) {
        sprintf(
        '"sort":
        [%s]
',
        paste(sapply(self$`sort`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`sql`)) {
        sprintf(
        '"sql":
          "%s"
                ',
        self$`sql`
        )},
        if (!is.null(self$`concreteType`)) {
        sprintf(
        '"concreteType":
          "%s"
                ',
        self$`concreteType`
        )},
        if (!is.null(self$`csvTableDescriptor`)) {
        sprintf(
        '"csvTableDescriptor":
        %s
        ',
        jsonlite::toJSON(self$`csvTableDescriptor`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`entityId`)) {
        sprintf(
        '"entityId":
          "%s"
                ',
        self$`entityId`
        )},
        if (!is.null(self$`includeRowIdAndRowVersion`)) {
        sprintf(
        '"includeRowIdAndRowVersion":
          "%s"
                ',
        self$`includeRowIdAndRowVersion`
        )},
        if (!is.null(self$`writeHeader`)) {
        sprintf(
        '"writeHeader":
          "%s"
                ',
        self$`writeHeader`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(DownloadFromTableRequestJson) {
      DownloadFromTableRequestObject <- jsonlite::fromJSON(DownloadFromTableRequestJson)
      self$`additionalFilters` <- ApiClient$new()$deserializeObj(DownloadFromTableRequestObject$`additionalFilters`, "array[object]", loadNamespace("synclient"))
      self$`includeEntityEtag` <- DownloadFromTableRequestObject$`includeEntityEtag`
      self$`limit` <- DownloadFromTableRequestObject$`limit`
      self$`offset` <- DownloadFromTableRequestObject$`offset`
      self$`selectedFacets` <- ApiClient$new()$deserializeObj(DownloadFromTableRequestObject$`selectedFacets`, "array[FacetColumnRequest]", loadNamespace("synclient"))
      self$`sort` <- ApiClient$new()$deserializeObj(DownloadFromTableRequestObject$`sort`, "array[SortItem]", loadNamespace("synclient"))
      self$`sql` <- DownloadFromTableRequestObject$`sql`
      self$`concreteType` <- DownloadFromTableRequestObject$`concreteType`
      self$`csvTableDescriptor` <- CsvTableDescriptor$new()$fromJSON(jsonlite::toJSON(DownloadFromTableRequestObject$csvTableDescriptor, auto_unbox = TRUE, digits = NA))
      self$`entityId` <- DownloadFromTableRequestObject$`entityId`
      self$`includeRowIdAndRowVersion` <- DownloadFromTableRequestObject$`includeRowIdAndRowVersion`
      self$`writeHeader` <- DownloadFromTableRequestObject$`writeHeader`
      self
    }
  )
)
