# Platform Repository Service
#
# Platform Repository Service - Sage Bionetworks Platform 
#
# The version of the OpenAPI document: develop-SNAPSHOT
# Contact: thomas.yu@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title EntityPath
#' @description EntityPath Class
#' @format An \code{R6Class} generator object
#' @field path  list( \link{EntityHeader} ) [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EntityPath <- R6::R6Class(
  'EntityPath',
  public = list(
    `path` = NULL,
    initialize = function(`path`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`path`)) {
        stopifnot(is.vector(`path`), length(`path`) != 0)
        sapply(`path`, function(x) stopifnot(R6::is.R6(x)))
        self$`path` <- `path`
      }
    },
    toJSON = function() {
      EntityPathObject <- list()
      if (!is.null(self$`path`)) {
        EntityPathObject[['path']] <-
          lapply(self$`path`, function(x) x$toJSON())
      }

      EntityPathObject
    },
    fromJSON = function(EntityPathJson) {
      EntityPathObject <- jsonlite::fromJSON(EntityPathJson)
      if (!is.null(EntityPathObject$`path`)) {
        self$`path` <- ApiClient$new()$deserializeObj(EntityPathObject$`path`, "array[EntityHeader]", loadNamespace("synclient"))
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`path`)) {
        sprintf(
        '"path":
        [%s]
',
        paste(sapply(self$`path`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(EntityPathJson) {
      EntityPathObject <- jsonlite::fromJSON(EntityPathJson)
      self$`path` <- ApiClient$new()$deserializeObj(EntityPathObject$`path`, "array[EntityHeader]", loadNamespace("synclient"))
      self
    }
  )
)
