# Platform Repository Service
#
# Platform Repository Service - Sage Bionetworks Platform 
#
# The version of the OpenAPI document: develop-SNAPSHOT
# Contact: thomas.yu@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title EntityThreadCounts
#'
#' @description EntityThreadCounts Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field list  list( \link{EntityThreadCount} ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
EntityThreadCounts <- R6::R6Class(
  'EntityThreadCounts',
  public = list(
    `list` = NULL,
    initialize = function(
        `list`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`list`)) {
        stopifnot(is.vector(`list`), length(`list`) != 0)
        sapply(`list`, function(x) stopifnot(R6::is.R6(x)))
        self$`list` <- `list`
      }
    },
    toJSON = function() {
      EntityThreadCountsObject <- list()
      if (!is.null(self$`list`)) {
        EntityThreadCountsObject[['list']] <-
          lapply(self$`list`, function(x) x$toJSON())
      }

      EntityThreadCountsObject
    },
    fromJSON = function(EntityThreadCountsJson) {
      EntityThreadCountsObject <- jsonlite::fromJSON(EntityThreadCountsJson)
      if (!is.null(EntityThreadCountsObject$`list`)) {
        self$`list` <- ApiClient$new()$deserializeObj(EntityThreadCountsObject$`list`, "array[EntityThreadCount]", loadNamespace("synclient"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`list`)) {
        sprintf(
        '"list":
        [%s]
',
        paste(sapply(self$`list`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(EntityThreadCountsJson) {
      EntityThreadCountsObject <- jsonlite::fromJSON(EntityThreadCountsJson)
      self$`list` <- ApiClient$new()$deserializeObj(EntityThreadCountsObject$`list`, "array[EntityThreadCount]", loadNamespace("synclient"))
      self
    }
  )
)

