# Platform Repository Service
#
# Platform Repository Service - Sage Bionetworks Platform 
#
# The version of the OpenAPI document: develop-SNAPSHOT
# Contact: thomas.yu@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title FacetColumnRequest
#'
#' @description FacetColumnRequest Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field columnName  character [optional]
#'
#' @field concreteType  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
FacetColumnRequest <- R6::R6Class(
  'FacetColumnRequest',
  public = list(
    `columnName` = NULL,
    `concreteType` = NULL,
    initialize = function(
        `columnName`=NULL, `concreteType`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`columnName`)) {
        stopifnot(is.character(`columnName`), length(`columnName`) == 1)
        self$`columnName` <- `columnName`
      }
      if (!is.null(`concreteType`)) {
        stopifnot(is.character(`concreteType`), length(`concreteType`) == 1)
        self$`concreteType` <- `concreteType`
      }
    },
    toJSON = function() {
      FacetColumnRequestObject <- list()
      if (!is.null(self$`columnName`)) {
        FacetColumnRequestObject[['columnName']] <-
          self$`columnName`
      }
      if (!is.null(self$`concreteType`)) {
        FacetColumnRequestObject[['concreteType']] <-
          self$`concreteType`
      }

      FacetColumnRequestObject
    },
    fromJSON = function(FacetColumnRequestJson) {
      FacetColumnRequestObject <- jsonlite::fromJSON(FacetColumnRequestJson)
      if (!is.null(FacetColumnRequestObject$`columnName`)) {
        self$`columnName` <- FacetColumnRequestObject$`columnName`
      }
      if (!is.null(FacetColumnRequestObject$`concreteType`)) {
        self$`concreteType` <- FacetColumnRequestObject$`concreteType`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`columnName`)) {
        sprintf(
        '"columnName":
          "%s"
                ',
        self$`columnName`
        )},
        if (!is.null(self$`concreteType`)) {
        sprintf(
        '"concreteType":
          "%s"
                ',
        self$`concreteType`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(FacetColumnRequestJson) {
      FacetColumnRequestObject <- jsonlite::fromJSON(FacetColumnRequestJson)
      self$`columnName` <- FacetColumnRequestObject$`columnName`
      self$`concreteType` <- FacetColumnRequestObject$`concreteType`
      self
    }
  )
)

