# Platform Repository Service
#
# Platform Repository Service - Sage Bionetworks Platform 
#
# The version of the OpenAPI document: develop-SNAPSHOT
# Contact: thomas.yu@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title FormData
#' @description FormData Class
#' @format An \code{R6Class} generator object
#' @field createdBy  character [optional]
#'
#' @field createdOn  character [optional]
#'
#' @field dataFileHandleId  character [optional]
#'
#' @field etag  character [optional]
#'
#' @field formDataId  character [optional]
#'
#' @field groupId  character [optional]
#'
#' @field modifiedOn  character [optional]
#'
#' @field name  character [optional]
#'
#' @field submissionStatus  \link{SubmissionStatusForm} [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
FormData <- R6::R6Class(
  'FormData',
  public = list(
    `createdBy` = NULL,
    `createdOn` = NULL,
    `dataFileHandleId` = NULL,
    `etag` = NULL,
    `formDataId` = NULL,
    `groupId` = NULL,
    `modifiedOn` = NULL,
    `name` = NULL,
    `submissionStatus` = NULL,
    initialize = function(`createdBy`=NULL, `createdOn`=NULL, `dataFileHandleId`=NULL, `etag`=NULL, `formDataId`=NULL, `groupId`=NULL, `modifiedOn`=NULL, `name`=NULL, `submissionStatus`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`createdBy`)) {
        stopifnot(is.character(`createdBy`), length(`createdBy`) == 1)
        self$`createdBy` <- `createdBy`
      }
      if (!is.null(`createdOn`)) {
        stopifnot(is.character(`createdOn`), length(`createdOn`) == 1)
        self$`createdOn` <- `createdOn`
      }
      if (!is.null(`dataFileHandleId`)) {
        stopifnot(is.character(`dataFileHandleId`), length(`dataFileHandleId`) == 1)
        self$`dataFileHandleId` <- `dataFileHandleId`
      }
      if (!is.null(`etag`)) {
        stopifnot(is.character(`etag`), length(`etag`) == 1)
        self$`etag` <- `etag`
      }
      if (!is.null(`formDataId`)) {
        stopifnot(is.character(`formDataId`), length(`formDataId`) == 1)
        self$`formDataId` <- `formDataId`
      }
      if (!is.null(`groupId`)) {
        stopifnot(is.character(`groupId`), length(`groupId`) == 1)
        self$`groupId` <- `groupId`
      }
      if (!is.null(`modifiedOn`)) {
        stopifnot(is.character(`modifiedOn`), length(`modifiedOn`) == 1)
        self$`modifiedOn` <- `modifiedOn`
      }
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!is.null(`submissionStatus`)) {
        stopifnot(R6::is.R6(`submissionStatus`))
        self$`submissionStatus` <- `submissionStatus`
      }
    },
    toJSON = function() {
      FormDataObject <- list()
      if (!is.null(self$`createdBy`)) {
        FormDataObject[['createdBy']] <-
          self$`createdBy`
      }
      if (!is.null(self$`createdOn`)) {
        FormDataObject[['createdOn']] <-
          self$`createdOn`
      }
      if (!is.null(self$`dataFileHandleId`)) {
        FormDataObject[['dataFileHandleId']] <-
          self$`dataFileHandleId`
      }
      if (!is.null(self$`etag`)) {
        FormDataObject[['etag']] <-
          self$`etag`
      }
      if (!is.null(self$`formDataId`)) {
        FormDataObject[['formDataId']] <-
          self$`formDataId`
      }
      if (!is.null(self$`groupId`)) {
        FormDataObject[['groupId']] <-
          self$`groupId`
      }
      if (!is.null(self$`modifiedOn`)) {
        FormDataObject[['modifiedOn']] <-
          self$`modifiedOn`
      }
      if (!is.null(self$`name`)) {
        FormDataObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`submissionStatus`)) {
        FormDataObject[['submissionStatus']] <-
          self$`submissionStatus`$toJSON()
      }

      FormDataObject
    },
    fromJSON = function(FormDataJson) {
      FormDataObject <- jsonlite::fromJSON(FormDataJson)
      if (!is.null(FormDataObject$`createdBy`)) {
        self$`createdBy` <- FormDataObject$`createdBy`
      }
      if (!is.null(FormDataObject$`createdOn`)) {
        self$`createdOn` <- FormDataObject$`createdOn`
      }
      if (!is.null(FormDataObject$`dataFileHandleId`)) {
        self$`dataFileHandleId` <- FormDataObject$`dataFileHandleId`
      }
      if (!is.null(FormDataObject$`etag`)) {
        self$`etag` <- FormDataObject$`etag`
      }
      if (!is.null(FormDataObject$`formDataId`)) {
        self$`formDataId` <- FormDataObject$`formDataId`
      }
      if (!is.null(FormDataObject$`groupId`)) {
        self$`groupId` <- FormDataObject$`groupId`
      }
      if (!is.null(FormDataObject$`modifiedOn`)) {
        self$`modifiedOn` <- FormDataObject$`modifiedOn`
      }
      if (!is.null(FormDataObject$`name`)) {
        self$`name` <- FormDataObject$`name`
      }
      if (!is.null(FormDataObject$`submissionStatus`)) {
        submissionStatusObject <- SubmissionStatusForm$new()
        submissionStatusObject$fromJSON(jsonlite::toJSON(FormDataObject$submissionStatus, auto_unbox = TRUE, digits = NA))
        self$`submissionStatus` <- submissionStatusObject
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`createdBy`)) {
        sprintf(
        '"createdBy":
          "%s"
                ',
        self$`createdBy`
        )},
        if (!is.null(self$`createdOn`)) {
        sprintf(
        '"createdOn":
          "%s"
                ',
        self$`createdOn`
        )},
        if (!is.null(self$`dataFileHandleId`)) {
        sprintf(
        '"dataFileHandleId":
          "%s"
                ',
        self$`dataFileHandleId`
        )},
        if (!is.null(self$`etag`)) {
        sprintf(
        '"etag":
          "%s"
                ',
        self$`etag`
        )},
        if (!is.null(self$`formDataId`)) {
        sprintf(
        '"formDataId":
          "%s"
                ',
        self$`formDataId`
        )},
        if (!is.null(self$`groupId`)) {
        sprintf(
        '"groupId":
          "%s"
                ',
        self$`groupId`
        )},
        if (!is.null(self$`modifiedOn`)) {
        sprintf(
        '"modifiedOn":
          "%s"
                ',
        self$`modifiedOn`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`submissionStatus`)) {
        sprintf(
        '"submissionStatus":
        %s
        ',
        jsonlite::toJSON(self$`submissionStatus`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(FormDataJson) {
      FormDataObject <- jsonlite::fromJSON(FormDataJson)
      self$`createdBy` <- FormDataObject$`createdBy`
      self$`createdOn` <- FormDataObject$`createdOn`
      self$`dataFileHandleId` <- FormDataObject$`dataFileHandleId`
      self$`etag` <- FormDataObject$`etag`
      self$`formDataId` <- FormDataObject$`formDataId`
      self$`groupId` <- FormDataObject$`groupId`
      self$`modifiedOn` <- FormDataObject$`modifiedOn`
      self$`name` <- FormDataObject$`name`
      self$`submissionStatus` <- SubmissionStatusForm$new()$fromJSON(jsonlite::toJSON(FormDataObject$submissionStatus, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)
