# Platform Repository Service
#
# Platform Repository Service - Sage Bionetworks Platform 
#
# The version of the OpenAPI document: develop-SNAPSHOT
# Contact: thomas.yu@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title JsonSchema
#'
#' @description JsonSchema Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field $id  character [optional]
#'
#' @field $ref  character [optional]
#'
#' @field $schema  character [optional]
#'
#' @field _const  character [optional]
#'
#' @field _else  \link{JsonSchema} [optional]
#'
#' @field _enum  list( character ) [optional]
#'
#' @field _if  \link{JsonSchema} [optional]
#'
#' @field allOf  list( \link{JsonSchema} ) [optional]
#'
#' @field anyOf  list( \link{JsonSchema} ) [optional]
#'
#' @field definitions  named list( \link{JsonSchema} ) [optional]
#'
#' @field description  character [optional]
#'
#' @field format  character [optional]
#'
#' @field items  \link{JsonSchema} [optional]
#'
#' @field maxLength  integer [optional]
#'
#' @field minLength  integer [optional]
#'
#' @field oneOf  list( \link{JsonSchema} ) [optional]
#'
#' @field pattern  character [optional]
#'
#' @field properties  named list( \link{JsonSchema} ) [optional]
#'
#' @field required  list( character ) [optional]
#'
#' @field source  character [optional]
#'
#' @field then  \link{JsonSchema} [optional]
#'
#' @field title  character [optional]
#'
#' @field type  \link{TYPE} [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
JsonSchema <- R6::R6Class(
  'JsonSchema',
  public = list(
    `$id` = NULL,
    `$ref` = NULL,
    `$schema` = NULL,
    `_const` = NULL,
    `_else` = NULL,
    `_enum` = NULL,
    `_if` = NULL,
    `allOf` = NULL,
    `anyOf` = NULL,
    `definitions` = NULL,
    `description` = NULL,
    `format` = NULL,
    `items` = NULL,
    `maxLength` = NULL,
    `minLength` = NULL,
    `oneOf` = NULL,
    `pattern` = NULL,
    `properties` = NULL,
    `required` = NULL,
    `source` = NULL,
    `then` = NULL,
    `title` = NULL,
    `type` = NULL,
    initialize = function(
        `$id`=NULL, `$ref`=NULL, `$schema`=NULL, `_const`=NULL, `_else`=NULL, `_enum`=NULL, `_if`=NULL, `allOf`=NULL, `anyOf`=NULL, `definitions`=NULL, `description`=NULL, `format`=NULL, `items`=NULL, `maxLength`=NULL, `minLength`=NULL, `oneOf`=NULL, `pattern`=NULL, `properties`=NULL, `required`=NULL, `source`=NULL, `then`=NULL, `title`=NULL, `type`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`$id`)) {
        stopifnot(is.character(`$id`), length(`$id`) == 1)
        self$`$id` <- `$id`
      }
      if (!is.null(`$ref`)) {
        stopifnot(is.character(`$ref`), length(`$ref`) == 1)
        self$`$ref` <- `$ref`
      }
      if (!is.null(`$schema`)) {
        stopifnot(is.character(`$schema`), length(`$schema`) == 1)
        self$`$schema` <- `$schema`
      }
      if (!is.null(`_const`)) {
        stopifnot(is.character(`_const`), length(`_const`) == 1)
        self$`_const` <- `_const`
      }
      if (!is.null(`_else`)) {
        stopifnot(R6::is.R6(`_else`))
        self$`_else` <- `_else`
      }
      if (!is.null(`_enum`)) {
        stopifnot(is.vector(`_enum`), length(`_enum`) != 0)
        sapply(`_enum`, function(x) stopifnot(is.character(x)))
        self$`_enum` <- `_enum`
      }
      if (!is.null(`_if`)) {
        stopifnot(R6::is.R6(`_if`))
        self$`_if` <- `_if`
      }
      if (!is.null(`allOf`)) {
        stopifnot(is.vector(`allOf`), length(`allOf`) != 0)
        sapply(`allOf`, function(x) stopifnot(R6::is.R6(x)))
        self$`allOf` <- `allOf`
      }
      if (!is.null(`anyOf`)) {
        stopifnot(is.vector(`anyOf`), length(`anyOf`) != 0)
        sapply(`anyOf`, function(x) stopifnot(R6::is.R6(x)))
        self$`anyOf` <- `anyOf`
      }
      if (!is.null(`definitions`)) {
        stopifnot(is.vector(`definitions`), length(`definitions`) != 0)
        sapply(`definitions`, function(x) stopifnot(R6::is.R6(x)))
        self$`definitions` <- `definitions`
      }
      if (!is.null(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!is.null(`format`)) {
        stopifnot(is.character(`format`), length(`format`) == 1)
        self$`format` <- `format`
      }
      if (!is.null(`items`)) {
        stopifnot(R6::is.R6(`items`))
        self$`items` <- `items`
      }
      if (!is.null(`maxLength`)) {
        stopifnot(is.numeric(`maxLength`), length(`maxLength`) == 1)
        self$`maxLength` <- `maxLength`
      }
      if (!is.null(`minLength`)) {
        stopifnot(is.numeric(`minLength`), length(`minLength`) == 1)
        self$`minLength` <- `minLength`
      }
      if (!is.null(`oneOf`)) {
        stopifnot(is.vector(`oneOf`), length(`oneOf`) != 0)
        sapply(`oneOf`, function(x) stopifnot(R6::is.R6(x)))
        self$`oneOf` <- `oneOf`
      }
      if (!is.null(`pattern`)) {
        stopifnot(is.character(`pattern`), length(`pattern`) == 1)
        self$`pattern` <- `pattern`
      }
      if (!is.null(`properties`)) {
        stopifnot(is.vector(`properties`), length(`properties`) != 0)
        sapply(`properties`, function(x) stopifnot(R6::is.R6(x)))
        self$`properties` <- `properties`
      }
      if (!is.null(`required`)) {
        stopifnot(is.vector(`required`), length(`required`) != 0)
        sapply(`required`, function(x) stopifnot(is.character(x)))
        self$`required` <- `required`
      }
      if (!is.null(`source`)) {
        stopifnot(is.character(`source`), length(`source`) == 1)
        self$`source` <- `source`
      }
      if (!is.null(`then`)) {
        stopifnot(R6::is.R6(`then`))
        self$`then` <- `then`
      }
      if (!is.null(`title`)) {
        stopifnot(is.character(`title`), length(`title`) == 1)
        self$`title` <- `title`
      }
      if (!is.null(`type`)) {
        stopifnot(R6::is.R6(`type`))
        self$`type` <- `type`
      }
    },
    toJSON = function() {
      JsonSchemaObject <- list()
      if (!is.null(self$`$id`)) {
        JsonSchemaObject[['$id']] <-
          self$`$id`
      }
      if (!is.null(self$`$ref`)) {
        JsonSchemaObject[['$ref']] <-
          self$`$ref`
      }
      if (!is.null(self$`$schema`)) {
        JsonSchemaObject[['$schema']] <-
          self$`$schema`
      }
      if (!is.null(self$`_const`)) {
        JsonSchemaObject[['_const']] <-
          self$`_const`
      }
      if (!is.null(self$`_else`)) {
        JsonSchemaObject[['_else']] <-
          self$`_else`$toJSON()
      }
      if (!is.null(self$`_enum`)) {
        JsonSchemaObject[['_enum']] <-
          self$`_enum`
      }
      if (!is.null(self$`_if`)) {
        JsonSchemaObject[['_if']] <-
          self$`_if`$toJSON()
      }
      if (!is.null(self$`allOf`)) {
        JsonSchemaObject[['allOf']] <-
          lapply(self$`allOf`, function(x) x$toJSON())
      }
      if (!is.null(self$`anyOf`)) {
        JsonSchemaObject[['anyOf']] <-
          lapply(self$`anyOf`, function(x) x$toJSON())
      }
      if (!is.null(self$`definitions`)) {
        JsonSchemaObject[['definitions']] <-
          lapply(self$`definitions`, function(x) x$toJSON())
      }
      if (!is.null(self$`description`)) {
        JsonSchemaObject[['description']] <-
          self$`description`
      }
      if (!is.null(self$`format`)) {
        JsonSchemaObject[['format']] <-
          self$`format`
      }
      if (!is.null(self$`items`)) {
        JsonSchemaObject[['items']] <-
          self$`items`$toJSON()
      }
      if (!is.null(self$`maxLength`)) {
        JsonSchemaObject[['maxLength']] <-
          self$`maxLength`
      }
      if (!is.null(self$`minLength`)) {
        JsonSchemaObject[['minLength']] <-
          self$`minLength`
      }
      if (!is.null(self$`oneOf`)) {
        JsonSchemaObject[['oneOf']] <-
          lapply(self$`oneOf`, function(x) x$toJSON())
      }
      if (!is.null(self$`pattern`)) {
        JsonSchemaObject[['pattern']] <-
          self$`pattern`
      }
      if (!is.null(self$`properties`)) {
        JsonSchemaObject[['properties']] <-
          lapply(self$`properties`, function(x) x$toJSON())
      }
      if (!is.null(self$`required`)) {
        JsonSchemaObject[['required']] <-
          self$`required`
      }
      if (!is.null(self$`source`)) {
        JsonSchemaObject[['source']] <-
          self$`source`
      }
      if (!is.null(self$`then`)) {
        JsonSchemaObject[['then']] <-
          self$`then`$toJSON()
      }
      if (!is.null(self$`title`)) {
        JsonSchemaObject[['title']] <-
          self$`title`
      }
      if (!is.null(self$`type`)) {
        JsonSchemaObject[['type']] <-
          self$`type`$toJSON()
      }

      JsonSchemaObject
    },
    fromJSON = function(JsonSchemaJson) {
      JsonSchemaObject <- jsonlite::fromJSON(JsonSchemaJson)
      if (!is.null(JsonSchemaObject$`$id`)) {
        self$`$id` <- JsonSchemaObject$`$id`
      }
      if (!is.null(JsonSchemaObject$`$ref`)) {
        self$`$ref` <- JsonSchemaObject$`$ref`
      }
      if (!is.null(JsonSchemaObject$`$schema`)) {
        self$`$schema` <- JsonSchemaObject$`$schema`
      }
      if (!is.null(JsonSchemaObject$`_const`)) {
        self$`_const` <- JsonSchemaObject$`_const`
      }
      if (!is.null(JsonSchemaObject$`_else`)) {
        _elseObject <- JsonSchema$new()
        _elseObject$fromJSON(jsonlite::toJSON(JsonSchemaObject$_else, auto_unbox = TRUE, digits = NA))
        self$`_else` <- _elseObject
      }
      if (!is.null(JsonSchemaObject$`_enum`)) {
        self$`_enum` <- ApiClient$new()$deserializeObj(JsonSchemaObject$`_enum`, "array[character]", loadNamespace("synclient"))
      }
      if (!is.null(JsonSchemaObject$`_if`)) {
        _ifObject <- JsonSchema$new()
        _ifObject$fromJSON(jsonlite::toJSON(JsonSchemaObject$_if, auto_unbox = TRUE, digits = NA))
        self$`_if` <- _ifObject
      }
      if (!is.null(JsonSchemaObject$`allOf`)) {
        self$`allOf` <- ApiClient$new()$deserializeObj(JsonSchemaObject$`allOf`, "array[JsonSchema]", loadNamespace("synclient"))
      }
      if (!is.null(JsonSchemaObject$`anyOf`)) {
        self$`anyOf` <- ApiClient$new()$deserializeObj(JsonSchemaObject$`anyOf`, "array[JsonSchema]", loadNamespace("synclient"))
      }
      if (!is.null(JsonSchemaObject$`definitions`)) {
        self$`definitions` <- ApiClient$new()$deserializeObj(JsonSchemaObject$`definitions`, "map(JsonSchema)", loadNamespace("synclient"))
      }
      if (!is.null(JsonSchemaObject$`description`)) {
        self$`description` <- JsonSchemaObject$`description`
      }
      if (!is.null(JsonSchemaObject$`format`)) {
        self$`format` <- JsonSchemaObject$`format`
      }
      if (!is.null(JsonSchemaObject$`items`)) {
        itemsObject <- JsonSchema$new()
        itemsObject$fromJSON(jsonlite::toJSON(JsonSchemaObject$items, auto_unbox = TRUE, digits = NA))
        self$`items` <- itemsObject
      }
      if (!is.null(JsonSchemaObject$`maxLength`)) {
        self$`maxLength` <- JsonSchemaObject$`maxLength`
      }
      if (!is.null(JsonSchemaObject$`minLength`)) {
        self$`minLength` <- JsonSchemaObject$`minLength`
      }
      if (!is.null(JsonSchemaObject$`oneOf`)) {
        self$`oneOf` <- ApiClient$new()$deserializeObj(JsonSchemaObject$`oneOf`, "array[JsonSchema]", loadNamespace("synclient"))
      }
      if (!is.null(JsonSchemaObject$`pattern`)) {
        self$`pattern` <- JsonSchemaObject$`pattern`
      }
      if (!is.null(JsonSchemaObject$`properties`)) {
        self$`properties` <- ApiClient$new()$deserializeObj(JsonSchemaObject$`properties`, "map(JsonSchema)", loadNamespace("synclient"))
      }
      if (!is.null(JsonSchemaObject$`required`)) {
        self$`required` <- ApiClient$new()$deserializeObj(JsonSchemaObject$`required`, "array[character]", loadNamespace("synclient"))
      }
      if (!is.null(JsonSchemaObject$`source`)) {
        self$`source` <- JsonSchemaObject$`source`
      }
      if (!is.null(JsonSchemaObject$`then`)) {
        thenObject <- JsonSchema$new()
        thenObject$fromJSON(jsonlite::toJSON(JsonSchemaObject$then, auto_unbox = TRUE, digits = NA))
        self$`then` <- thenObject
      }
      if (!is.null(JsonSchemaObject$`title`)) {
        self$`title` <- JsonSchemaObject$`title`
      }
      if (!is.null(JsonSchemaObject$`type`)) {
        typeObject <- TYPE$new()
        typeObject$fromJSON(jsonlite::toJSON(JsonSchemaObject$type, auto_unbox = TRUE, digits = NA))
        self$`type` <- typeObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`$id`)) {
        sprintf(
        '"$id":
          "%s"
                ',
        self$`$id`
        )},
        if (!is.null(self$`$ref`)) {
        sprintf(
        '"$ref":
          "%s"
                ',
        self$`$ref`
        )},
        if (!is.null(self$`$schema`)) {
        sprintf(
        '"$schema":
          "%s"
                ',
        self$`$schema`
        )},
        if (!is.null(self$`_const`)) {
        sprintf(
        '"_const":
          "%s"
                ',
        self$`_const`
        )},
        if (!is.null(self$`_else`)) {
        sprintf(
        '"_else":
        %s
        ',
        jsonlite::toJSON(self$`_else`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`_enum`)) {
        sprintf(
        '"_enum":
           [%s]
        ',
        paste(unlist(lapply(self$`_enum`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`_if`)) {
        sprintf(
        '"_if":
        %s
        ',
        jsonlite::toJSON(self$`_if`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`allOf`)) {
        sprintf(
        '"allOf":
        [%s]
',
        paste(sapply(self$`allOf`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`anyOf`)) {
        sprintf(
        '"anyOf":
        [%s]
',
        paste(sapply(self$`anyOf`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`definitions`)) {
        sprintf(
        '"definitions":
        %s
',
        jsonlite::toJSON(lapply(self$`definitions`, function(x){ x$toJSON() }), auto_unbox = TRUE, digits=NA)
        )},
        if (!is.null(self$`description`)) {
        sprintf(
        '"description":
          "%s"
                ',
        self$`description`
        )},
        if (!is.null(self$`format`)) {
        sprintf(
        '"format":
          "%s"
                ',
        self$`format`
        )},
        if (!is.null(self$`items`)) {
        sprintf(
        '"items":
        %s
        ',
        jsonlite::toJSON(self$`items`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`maxLength`)) {
        sprintf(
        '"maxLength":
          %d
                ',
        self$`maxLength`
        )},
        if (!is.null(self$`minLength`)) {
        sprintf(
        '"minLength":
          %d
                ',
        self$`minLength`
        )},
        if (!is.null(self$`oneOf`)) {
        sprintf(
        '"oneOf":
        [%s]
',
        paste(sapply(self$`oneOf`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`pattern`)) {
        sprintf(
        '"pattern":
          "%s"
                ',
        self$`pattern`
        )},
        if (!is.null(self$`properties`)) {
        sprintf(
        '"properties":
        %s
',
        jsonlite::toJSON(lapply(self$`properties`, function(x){ x$toJSON() }), auto_unbox = TRUE, digits=NA)
        )},
        if (!is.null(self$`required`)) {
        sprintf(
        '"required":
           [%s]
        ',
        paste(unlist(lapply(self$`required`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`source`)) {
        sprintf(
        '"source":
          "%s"
                ',
        self$`source`
        )},
        if (!is.null(self$`then`)) {
        sprintf(
        '"then":
        %s
        ',
        jsonlite::toJSON(self$`then`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`title`)) {
        sprintf(
        '"title":
          "%s"
                ',
        self$`title`
        )},
        if (!is.null(self$`type`)) {
        sprintf(
        '"type":
        %s
        ',
        jsonlite::toJSON(self$`type`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(JsonSchemaJson) {
      JsonSchemaObject <- jsonlite::fromJSON(JsonSchemaJson)
      self$`$id` <- JsonSchemaObject$`$id`
      self$`$ref` <- JsonSchemaObject$`$ref`
      self$`$schema` <- JsonSchemaObject$`$schema`
      self$`_const` <- JsonSchemaObject$`_const`
      self$`_else` <- JsonSchema$new()$fromJSON(jsonlite::toJSON(JsonSchemaObject$_else, auto_unbox = TRUE, digits = NA))
      self$`_enum` <- ApiClient$new()$deserializeObj(JsonSchemaObject$`_enum`, "array[character]", loadNamespace("synclient"))
      self$`_if` <- JsonSchema$new()$fromJSON(jsonlite::toJSON(JsonSchemaObject$_if, auto_unbox = TRUE, digits = NA))
      self$`allOf` <- ApiClient$new()$deserializeObj(JsonSchemaObject$`allOf`, "array[JsonSchema]", loadNamespace("synclient"))
      self$`anyOf` <- ApiClient$new()$deserializeObj(JsonSchemaObject$`anyOf`, "array[JsonSchema]", loadNamespace("synclient"))
      self$`definitions` <- ApiClient$new()$deserializeObj(JsonSchemaObject$`definitions`, "map(JsonSchema)", loadNamespace("synclient"))
      self$`description` <- JsonSchemaObject$`description`
      self$`format` <- JsonSchemaObject$`format`
      self$`items` <- JsonSchema$new()$fromJSON(jsonlite::toJSON(JsonSchemaObject$items, auto_unbox = TRUE, digits = NA))
      self$`maxLength` <- JsonSchemaObject$`maxLength`
      self$`minLength` <- JsonSchemaObject$`minLength`
      self$`oneOf` <- ApiClient$new()$deserializeObj(JsonSchemaObject$`oneOf`, "array[JsonSchema]", loadNamespace("synclient"))
      self$`pattern` <- JsonSchemaObject$`pattern`
      self$`properties` <- ApiClient$new()$deserializeObj(JsonSchemaObject$`properties`, "map(JsonSchema)", loadNamespace("synclient"))
      self$`required` <- ApiClient$new()$deserializeObj(JsonSchemaObject$`required`, "array[character]", loadNamespace("synclient"))
      self$`source` <- JsonSchemaObject$`source`
      self$`then` <- JsonSchema$new()$fromJSON(jsonlite::toJSON(JsonSchemaObject$then, auto_unbox = TRUE, digits = NA))
      self$`title` <- JsonSchemaObject$`title`
      self$`type` <- TYPE$new()$fromJSON(jsonlite::toJSON(JsonSchemaObject$type, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)

