# Platform Repository Service
#
# Platform Repository Service - Sage Bionetworks Platform 
#
# The version of the OpenAPI document: develop-SNAPSHOT
# Contact: thomas.yu@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ListRequest
#' @description ListRequest Class
#' @format An \code{R6Class} generator object
#' @field filterByState  list( \link{StateEnum} ) [optional]
#'
#' @field groupId  character [optional]
#'
#' @field nextPageToken  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ListRequest <- R6::R6Class(
  'ListRequest',
  public = list(
    `filterByState` = NULL,
    `groupId` = NULL,
    `nextPageToken` = NULL,
    initialize = function(`filterByState`=NULL, `groupId`=NULL, `nextPageToken`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`filterByState`)) {
        stopifnot(is.vector(`filterByState`), length(`filterByState`) != 0)
        sapply(`filterByState`, function(x) stopifnot(R6::is.R6(x)))
        self$`filterByState` <- `filterByState`
      }
      if (!is.null(`groupId`)) {
        stopifnot(is.character(`groupId`), length(`groupId`) == 1)
        self$`groupId` <- `groupId`
      }
      if (!is.null(`nextPageToken`)) {
        stopifnot(is.character(`nextPageToken`), length(`nextPageToken`) == 1)
        self$`nextPageToken` <- `nextPageToken`
      }
    },
    toJSON = function() {
      ListRequestObject <- list()
      if (!is.null(self$`filterByState`)) {
        ListRequestObject[['filterByState']] <-
          lapply(self$`filterByState`, function(x) x$toJSON())
      }
      if (!is.null(self$`groupId`)) {
        ListRequestObject[['groupId']] <-
          self$`groupId`
      }
      if (!is.null(self$`nextPageToken`)) {
        ListRequestObject[['nextPageToken']] <-
          self$`nextPageToken`
      }

      ListRequestObject
    },
    fromJSON = function(ListRequestJson) {
      ListRequestObject <- jsonlite::fromJSON(ListRequestJson)
      if (!is.null(ListRequestObject$`filterByState`)) {
        self$`filterByState` <- ApiClient$new()$deserializeObj(ListRequestObject$`filterByState`, "array[StateEnum]", loadNamespace("synclient"))
      }
      if (!is.null(ListRequestObject$`groupId`)) {
        self$`groupId` <- ListRequestObject$`groupId`
      }
      if (!is.null(ListRequestObject$`nextPageToken`)) {
        self$`nextPageToken` <- ListRequestObject$`nextPageToken`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`filterByState`)) {
        sprintf(
        '"filterByState":
        [%s]
',
        paste(sapply(self$`filterByState`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`groupId`)) {
        sprintf(
        '"groupId":
          "%s"
                ',
        self$`groupId`
        )},
        if (!is.null(self$`nextPageToken`)) {
        sprintf(
        '"nextPageToken":
          "%s"
                ',
        self$`nextPageToken`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ListRequestJson) {
      ListRequestObject <- jsonlite::fromJSON(ListRequestJson)
      self$`filterByState` <- ApiClient$new()$deserializeObj(ListRequestObject$`filterByState`, "array[StateEnum]", loadNamespace("synclient"))
      self$`groupId` <- ListRequestObject$`groupId`
      self$`nextPageToken` <- ListRequestObject$`nextPageToken`
      self
    }
  )
)
