# Platform Repository Service
#
# Platform Repository Service - Sage Bionetworks Platform 
#
# The version of the OpenAPI document: develop-SNAPSHOT
# Contact: thomas.yu@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ListOrganizationsRequest
#'
#' @description ListOrganizationsRequest Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field nextPageToken  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ListOrganizationsRequest <- R6::R6Class(
  'ListOrganizationsRequest',
  public = list(
    `nextPageToken` = NULL,
    initialize = function(
        `nextPageToken`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`nextPageToken`)) {
        stopifnot(is.character(`nextPageToken`), length(`nextPageToken`) == 1)
        self$`nextPageToken` <- `nextPageToken`
      }
    },
    toJSON = function() {
      ListOrganizationsRequestObject <- list()
      if (!is.null(self$`nextPageToken`)) {
        ListOrganizationsRequestObject[['nextPageToken']] <-
          self$`nextPageToken`
      }

      ListOrganizationsRequestObject
    },
    fromJSON = function(ListOrganizationsRequestJson) {
      ListOrganizationsRequestObject <- jsonlite::fromJSON(ListOrganizationsRequestJson)
      if (!is.null(ListOrganizationsRequestObject$`nextPageToken`)) {
        self$`nextPageToken` <- ListOrganizationsRequestObject$`nextPageToken`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`nextPageToken`)) {
        sprintf(
        '"nextPageToken":
          "%s"
                ',
        self$`nextPageToken`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ListOrganizationsRequestJson) {
      ListOrganizationsRequestObject <- jsonlite::fromJSON(ListOrganizationsRequestJson)
      self$`nextPageToken` <- ListOrganizationsRequestObject$`nextPageToken`
      self
    }
  )
)

