#' Create a new OrgSagebionetworksRepoModelTableQuery
#'
#' @description
#' OrgSagebionetworksRepoModelTableQuery Class
#'
#' @docType class
#' @title OrgSagebionetworksRepoModelTableQuery
#' @description OrgSagebionetworksRepoModelTableQuery Class
#' @format An \code{R6Class} generator object
#' @field sql  character [optional]
#' @field additionalFilters Appends additional filters to the SQL query. These are applied before facets. Filters within the list have an AND relationship. If a WHERE clause already exists on the SQL query or facets are selected, it will also be ANDed with the query generated by these additional filters. list(\link{OrgSagebionetworksRepoModelTableQueryFilter}) [optional]
#' @field selectedFacets The selected facet filters. list(\link{OrgSagebionetworksRepoModelTableFacetColumnRequest}) [optional]
#' @field includeEntityEtag  character [optional]
#' @field selectFileColumn  integer [optional]
#' @field offset  integer [optional]
#' @field limit  integer [optional]
#' @field sort  list(\link{OrgSagebionetworksRepoModelTableSortItem}) [optional]
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
OrgSagebionetworksRepoModelTableQuery <- R6::R6Class(
  "OrgSagebionetworksRepoModelTableQuery",
  public = list(
    `sql` = NULL,
    `additionalFilters` = NULL,
    `selectedFacets` = NULL,
    `includeEntityEtag` = NULL,
    `selectFileColumn` = NULL,
    `offset` = NULL,
    `limit` = NULL,
    `sort` = NULL,
    #' Initialize a new OrgSagebionetworksRepoModelTableQuery class.
    #'
    #' @description
    #' Initialize a new OrgSagebionetworksRepoModelTableQuery class.
    #'
    #' @param sql sql
    #' @param additionalFilters Appends additional filters to the SQL query. These are applied before facets. Filters within the list have an AND relationship. If a WHERE clause already exists on the SQL query or facets are selected, it will also be ANDed with the query generated by these additional filters.
    #' @param selectedFacets The selected facet filters.
    #' @param includeEntityEtag includeEntityEtag
    #' @param selectFileColumn selectFileColumn
    #' @param offset offset
    #' @param limit limit
    #' @param sort sort
    #' @param ... Other optional arguments.
    #' @export
    initialize = function(`sql` = NULL, `additionalFilters` = NULL, `selectedFacets` = NULL, `includeEntityEtag` = NULL, `selectFileColumn` = NULL, `offset` = NULL, `limit` = NULL, `sort` = NULL, ...) {
      if (!is.null(`sql`)) {
        if (!(is.character(`sql`) && length(`sql`) == 1)) {
          stop(paste("Error! Invalid data for `sql`. Must be a string:", `sql`))
        }
        self$`sql` <- `sql`
      }
      if (!is.null(`additionalFilters`)) {
        stopifnot(is.vector(`additionalFilters`), length(`additionalFilters`) != 0)
        sapply(`additionalFilters`, function(x) stopifnot(R6::is.R6(x)))
        self$`additionalFilters` <- `additionalFilters`
      }
      if (!is.null(`selectedFacets`)) {
        stopifnot(is.vector(`selectedFacets`), length(`selectedFacets`) != 0)
        sapply(`selectedFacets`, function(x) stopifnot(R6::is.R6(x)))
        self$`selectedFacets` <- `selectedFacets`
      }
      if (!is.null(`includeEntityEtag`)) {
        if (!(is.logical(`includeEntityEtag`) && length(`includeEntityEtag`) == 1)) {
          stop(paste("Error! Invalid data for `includeEntityEtag`. Must be a boolean:", `includeEntityEtag`))
        }
        self$`includeEntityEtag` <- `includeEntityEtag`
      }
      if (!is.null(`selectFileColumn`)) {
        if (!(is.numeric(`selectFileColumn`) && length(`selectFileColumn`) == 1)) {
          stop(paste("Error! Invalid data for `selectFileColumn`. Must be an integer:", `selectFileColumn`))
        }
        self$`selectFileColumn` <- `selectFileColumn`
      }
      if (!is.null(`offset`)) {
        if (!(is.numeric(`offset`) && length(`offset`) == 1)) {
          stop(paste("Error! Invalid data for `offset`. Must be an integer:", `offset`))
        }
        self$`offset` <- `offset`
      }
      if (!is.null(`limit`)) {
        if (!(is.numeric(`limit`) && length(`limit`) == 1)) {
          stop(paste("Error! Invalid data for `limit`. Must be an integer:", `limit`))
        }
        self$`limit` <- `limit`
      }
      if (!is.null(`sort`)) {
        stopifnot(is.vector(`sort`), length(`sort`) != 0)
        sapply(`sort`, function(x) stopifnot(R6::is.R6(x)))
        self$`sort` <- `sort`
      }
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return OrgSagebionetworksRepoModelTableQuery in JSON format
    #' @export
    toJSON = function() {
      OrgSagebionetworksRepoModelTableQueryObject <- list()
      if (!is.null(self$`sql`)) {
        OrgSagebionetworksRepoModelTableQueryObject[["sql"]] <-
          self$`sql`
      }
      if (!is.null(self$`additionalFilters`)) {
        OrgSagebionetworksRepoModelTableQueryObject[["additionalFilters"]] <-
          lapply(self$`additionalFilters`, function(x) x$toJSON())
      }
      if (!is.null(self$`selectedFacets`)) {
        OrgSagebionetworksRepoModelTableQueryObject[["selectedFacets"]] <-
          lapply(self$`selectedFacets`, function(x) x$toJSON())
      }
      if (!is.null(self$`includeEntityEtag`)) {
        OrgSagebionetworksRepoModelTableQueryObject[["includeEntityEtag"]] <-
          self$`includeEntityEtag`
      }
      if (!is.null(self$`selectFileColumn`)) {
        OrgSagebionetworksRepoModelTableQueryObject[["selectFileColumn"]] <-
          self$`selectFileColumn`
      }
      if (!is.null(self$`offset`)) {
        OrgSagebionetworksRepoModelTableQueryObject[["offset"]] <-
          self$`offset`
      }
      if (!is.null(self$`limit`)) {
        OrgSagebionetworksRepoModelTableQueryObject[["limit"]] <-
          self$`limit`
      }
      if (!is.null(self$`sort`)) {
        OrgSagebionetworksRepoModelTableQueryObject[["sort"]] <-
          lapply(self$`sort`, function(x) x$toJSON())
      }
      OrgSagebionetworksRepoModelTableQueryObject
    },
    #' Deserialize JSON string into an instance of OrgSagebionetworksRepoModelTableQuery
    #'
    #' @description
    #' Deserialize JSON string into an instance of OrgSagebionetworksRepoModelTableQuery
    #'
    #' @param input_json the JSON input
    #' @return the instance of OrgSagebionetworksRepoModelTableQuery
    #' @export
    fromJSON = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      if (!is.null(this_object$`sql`)) {
        self$`sql` <- this_object$`sql`
      }
      if (!is.null(this_object$`additionalFilters`)) {
        self$`additionalFilters` <- ApiClient$new()$deserializeObj(this_object$`additionalFilters`, "array[OrgSagebionetworksRepoModelTableQueryFilter]", loadNamespace("synclient"))
      }
      if (!is.null(this_object$`selectedFacets`)) {
        self$`selectedFacets` <- ApiClient$new()$deserializeObj(this_object$`selectedFacets`, "array[OrgSagebionetworksRepoModelTableFacetColumnRequest]", loadNamespace("synclient"))
      }
      if (!is.null(this_object$`includeEntityEtag`)) {
        self$`includeEntityEtag` <- this_object$`includeEntityEtag`
      }
      if (!is.null(this_object$`selectFileColumn`)) {
        self$`selectFileColumn` <- this_object$`selectFileColumn`
      }
      if (!is.null(this_object$`offset`)) {
        self$`offset` <- this_object$`offset`
      }
      if (!is.null(this_object$`limit`)) {
        self$`limit` <- this_object$`limit`
      }
      if (!is.null(this_object$`sort`)) {
        self$`sort` <- ApiClient$new()$deserializeObj(this_object$`sort`, "array[OrgSagebionetworksRepoModelTableSortItem]", loadNamespace("synclient"))
      }
      self
    },
    #' To JSON string
    #'
    #' @description
    #' To JSON String
    #'
    #' @return OrgSagebionetworksRepoModelTableQuery in JSON format
    #' @export
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`sql`)) {
          sprintf(
          '"sql":
            "%s"
                    ',
          self$`sql`
          )
        },
        if (!is.null(self$`additionalFilters`)) {
          sprintf(
          '"additionalFilters":
          [%s]
',
          paste(sapply(self$`additionalFilters`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox = TRUE, digits = NA)), collapse = ",")
          )
        },
        if (!is.null(self$`selectedFacets`)) {
          sprintf(
          '"selectedFacets":
          [%s]
',
          paste(sapply(self$`selectedFacets`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox = TRUE, digits = NA)), collapse = ",")
          )
        },
        if (!is.null(self$`includeEntityEtag`)) {
          sprintf(
          '"includeEntityEtag":
            %s
                    ',
          tolower(self$`includeEntityEtag`)
          )
        },
        if (!is.null(self$`selectFileColumn`)) {
          sprintf(
          '"selectFileColumn":
            %d
                    ',
          self$`selectFileColumn`
          )
        },
        if (!is.null(self$`offset`)) {
          sprintf(
          '"offset":
            %d
                    ',
          self$`offset`
          )
        },
        if (!is.null(self$`limit`)) {
          sprintf(
          '"limit":
            %d
                    ',
          self$`limit`
          )
        },
        if (!is.null(self$`sort`)) {
          sprintf(
          '"sort":
          [%s]
',
          paste(sapply(self$`sort`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox = TRUE, digits = NA)), collapse = ",")
          )
        }
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      json_string <- as.character(jsonlite::minify(paste("{", jsoncontent, "}", sep = "")))
    },
    #' Deserialize JSON string into an instance of OrgSagebionetworksRepoModelTableQuery
    #'
    #' @description
    #' Deserialize JSON string into an instance of OrgSagebionetworksRepoModelTableQuery
    #'
    #' @param input_json the JSON input
    #' @return the instance of OrgSagebionetworksRepoModelTableQuery
    #' @export
    fromJSONString = function(input_json) {
      this_object <- jsonlite::fromJSON(input_json)
      self$`sql` <- this_object$`sql`
      self$`additionalFilters` <- ApiClient$new()$deserializeObj(this_object$`additionalFilters`, "array[OrgSagebionetworksRepoModelTableQueryFilter]", loadNamespace("synclient"))
      self$`selectedFacets` <- ApiClient$new()$deserializeObj(this_object$`selectedFacets`, "array[OrgSagebionetworksRepoModelTableFacetColumnRequest]", loadNamespace("synclient"))
      self$`includeEntityEtag` <- this_object$`includeEntityEtag`
      self$`selectFileColumn` <- this_object$`selectFileColumn`
      self$`offset` <- this_object$`offset`
      self$`limit` <- this_object$`limit`
      self$`sort` <- ApiClient$new()$deserializeObj(this_object$`sort`, "array[OrgSagebionetworksRepoModelTableSortItem]", loadNamespace("synclient"))
      self
    },
    #' Validate JSON input with respect to OrgSagebionetworksRepoModelTableQuery
    #'
    #' @description
    #' Validate JSON input with respect to OrgSagebionetworksRepoModelTableQuery and throw an exception if invalid
    #'
    #' @param input the JSON input
    #' @export
    validateJSON = function(input) {
      input_json <- jsonlite::fromJSON(input)
    },
    #' To string (JSON format)
    #'
    #' @description
    #' To string (JSON format)
    #'
    #' @return String representation of OrgSagebionetworksRepoModelTableQuery
    #' @export
    toString = function() {
      self$toJSONString()
    },
    #' Return true if the values in all fields are valid.
    #'
    #' @description
    #' Return true if the values in all fields are valid.
    #'
    #' @return true if the values in all fields are valid.
    #' @export
    isValid = function() {
      TRUE
    },
    #' Return a list of invalid fields (if any).
    #'
    #' @description
    #' Return a list of invalid fields (if any).
    #'
    #' @return A list of invalid fields (if any).
    #' @export
    getInvalidFields = function() {
      invalid_fields <- list()
      invalid_fields
    },
    #' Print the object
    #'
    #' @description
    #' Print the object
    #'
    #' @export
    print = function() {
      print(jsonlite::prettify(self$toJSONString()))
      invisible(self)
    }
  ),
  # Lock the class to prevent modifications to the method or field
  lock_class = TRUE
)
## Uncomment below to unlock the class to allow modifications of the method or field
# OrgSagebionetworksRepoModelTableQuery$unlock()
#
## Below is an example to define the print function
# OrgSagebionetworksRepoModelTableQuery$set("public", "print", function(...) {
#   print(jsonlite::prettify(self$toJSONString()))
#   invisible(self)
# })
## Uncomment below to lock the class to prevent modifications to the method or field
# OrgSagebionetworksRepoModelTableQuery$lock()

