# Platform Repository Service
#
# Platform Repository Service - Sage Bionetworks Platform 
#
# The version of the OpenAPI document: develop-SNAPSHOT
# Contact: thomas.yu@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Organization
#'
#' @description Organization Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field createdBy  character [optional]
#'
#' @field createdOn  character [optional]
#'
#' @field id  character [optional]
#'
#' @field name  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Organization <- R6::R6Class(
  'Organization',
  public = list(
    `createdBy` = NULL,
    `createdOn` = NULL,
    `id` = NULL,
    `name` = NULL,
    initialize = function(
        `createdBy`=NULL, `createdOn`=NULL, `id`=NULL, `name`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`createdBy`)) {
        stopifnot(is.character(`createdBy`), length(`createdBy`) == 1)
        self$`createdBy` <- `createdBy`
      }
      if (!is.null(`createdOn`)) {
        stopifnot(is.character(`createdOn`), length(`createdOn`) == 1)
        self$`createdOn` <- `createdOn`
      }
      if (!is.null(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
    },
    toJSON = function() {
      OrganizationObject <- list()
      if (!is.null(self$`createdBy`)) {
        OrganizationObject[['createdBy']] <-
          self$`createdBy`
      }
      if (!is.null(self$`createdOn`)) {
        OrganizationObject[['createdOn']] <-
          self$`createdOn`
      }
      if (!is.null(self$`id`)) {
        OrganizationObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`name`)) {
        OrganizationObject[['name']] <-
          self$`name`
      }

      OrganizationObject
    },
    fromJSON = function(OrganizationJson) {
      OrganizationObject <- jsonlite::fromJSON(OrganizationJson)
      if (!is.null(OrganizationObject$`createdBy`)) {
        self$`createdBy` <- OrganizationObject$`createdBy`
      }
      if (!is.null(OrganizationObject$`createdOn`)) {
        self$`createdOn` <- OrganizationObject$`createdOn`
      }
      if (!is.null(OrganizationObject$`id`)) {
        self$`id` <- OrganizationObject$`id`
      }
      if (!is.null(OrganizationObject$`name`)) {
        self$`name` <- OrganizationObject$`name`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`createdBy`)) {
        sprintf(
        '"createdBy":
          "%s"
                ',
        self$`createdBy`
        )},
        if (!is.null(self$`createdOn`)) {
        sprintf(
        '"createdOn":
          "%s"
                ',
        self$`createdOn`
        )},
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(OrganizationJson) {
      OrganizationObject <- jsonlite::fromJSON(OrganizationJson)
      self$`createdBy` <- OrganizationObject$`createdBy`
      self$`createdOn` <- OrganizationObject$`createdOn`
      self$`id` <- OrganizationObject$`id`
      self$`name` <- OrganizationObject$`name`
      self
    }
  )
)

