# Platform Repository Service
#
# Platform Repository Service - Sage Bionetworks Platform 
#
# The version of the OpenAPI document: develop-SNAPSHOT
# Contact: thomas.yu@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Query
#' @description Query Class
#' @format An \code{R6Class} generator object
#' @field additionalFilters  list( object ) [optional]
#'
#' @field includeEntityEtag  character [optional]
#'
#' @field limit  integer [optional]
#'
#' @field offset  integer [optional]
#'
#' @field selectedFacets  list( \link{FacetColumnRequest} ) [optional]
#'
#' @field sort  list( \link{SortItem} ) [optional]
#'
#' @field sql  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Query <- R6::R6Class(
  'Query',
  public = list(
    `additionalFilters` = NULL,
    `includeEntityEtag` = NULL,
    `limit` = NULL,
    `offset` = NULL,
    `selectedFacets` = NULL,
    `sort` = NULL,
    `sql` = NULL,
    initialize = function(`additionalFilters`=NULL, `includeEntityEtag`=NULL, `limit`=NULL, `offset`=NULL, `selectedFacets`=NULL, `sort`=NULL, `sql`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`additionalFilters`)) {
        stopifnot(is.vector(`additionalFilters`), length(`additionalFilters`) != 0)
        sapply(`additionalFilters`, function(x) stopifnot(is.character(x)))
        self$`additionalFilters` <- `additionalFilters`
      }
      if (!is.null(`includeEntityEtag`)) {
        self$`includeEntityEtag` <- `includeEntityEtag`
      }
      if (!is.null(`limit`)) {
        stopifnot(is.numeric(`limit`), length(`limit`) == 1)
        self$`limit` <- `limit`
      }
      if (!is.null(`offset`)) {
        stopifnot(is.numeric(`offset`), length(`offset`) == 1)
        self$`offset` <- `offset`
      }
      if (!is.null(`selectedFacets`)) {
        stopifnot(is.vector(`selectedFacets`), length(`selectedFacets`) != 0)
        sapply(`selectedFacets`, function(x) stopifnot(R6::is.R6(x)))
        self$`selectedFacets` <- `selectedFacets`
      }
      if (!is.null(`sort`)) {
        stopifnot(is.vector(`sort`), length(`sort`) != 0)
        sapply(`sort`, function(x) stopifnot(R6::is.R6(x)))
        self$`sort` <- `sort`
      }
      if (!is.null(`sql`)) {
        stopifnot(is.character(`sql`), length(`sql`) == 1)
        self$`sql` <- `sql`
      }
    },
    toJSON = function() {
      QueryObject <- list()
      if (!is.null(self$`additionalFilters`)) {
        QueryObject[['additionalFilters']] <-
          self$`additionalFilters`
      }
      if (!is.null(self$`includeEntityEtag`)) {
        QueryObject[['includeEntityEtag']] <-
          self$`includeEntityEtag`
      }
      if (!is.null(self$`limit`)) {
        QueryObject[['limit']] <-
          self$`limit`
      }
      if (!is.null(self$`offset`)) {
        QueryObject[['offset']] <-
          self$`offset`
      }
      if (!is.null(self$`selectedFacets`)) {
        QueryObject[['selectedFacets']] <-
          lapply(self$`selectedFacets`, function(x) x$toJSON())
      }
      if (!is.null(self$`sort`)) {
        QueryObject[['sort']] <-
          lapply(self$`sort`, function(x) x$toJSON())
      }
      if (!is.null(self$`sql`)) {
        QueryObject[['sql']] <-
          self$`sql`
      }

      QueryObject
    },
    fromJSON = function(QueryJson) {
      QueryObject <- jsonlite::fromJSON(QueryJson)
      if (!is.null(QueryObject$`additionalFilters`)) {
        self$`additionalFilters` <- ApiClient$new()$deserializeObj(QueryObject$`additionalFilters`, "array[object]", loadNamespace("synclient"))
      }
      if (!is.null(QueryObject$`includeEntityEtag`)) {
        self$`includeEntityEtag` <- QueryObject$`includeEntityEtag`
      }
      if (!is.null(QueryObject$`limit`)) {
        self$`limit` <- QueryObject$`limit`
      }
      if (!is.null(QueryObject$`offset`)) {
        self$`offset` <- QueryObject$`offset`
      }
      if (!is.null(QueryObject$`selectedFacets`)) {
        self$`selectedFacets` <- ApiClient$new()$deserializeObj(QueryObject$`selectedFacets`, "array[FacetColumnRequest]", loadNamespace("synclient"))
      }
      if (!is.null(QueryObject$`sort`)) {
        self$`sort` <- ApiClient$new()$deserializeObj(QueryObject$`sort`, "array[SortItem]", loadNamespace("synclient"))
      }
      if (!is.null(QueryObject$`sql`)) {
        self$`sql` <- QueryObject$`sql`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`additionalFilters`)) {
        sprintf(
        '"additionalFilters":
           [%s]
        ',
        paste(unlist(lapply(self$`additionalFilters`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`includeEntityEtag`)) {
        sprintf(
        '"includeEntityEtag":
          "%s"
                ',
        self$`includeEntityEtag`
        )},
        if (!is.null(self$`limit`)) {
        sprintf(
        '"limit":
          %d
                ',
        self$`limit`
        )},
        if (!is.null(self$`offset`)) {
        sprintf(
        '"offset":
          %d
                ',
        self$`offset`
        )},
        if (!is.null(self$`selectedFacets`)) {
        sprintf(
        '"selectedFacets":
        [%s]
',
        paste(sapply(self$`selectedFacets`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`sort`)) {
        sprintf(
        '"sort":
        [%s]
',
        paste(sapply(self$`sort`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`sql`)) {
        sprintf(
        '"sql":
          "%s"
                ',
        self$`sql`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(QueryJson) {
      QueryObject <- jsonlite::fromJSON(QueryJson)
      self$`additionalFilters` <- ApiClient$new()$deserializeObj(QueryObject$`additionalFilters`, "array[object]", loadNamespace("synclient"))
      self$`includeEntityEtag` <- QueryObject$`includeEntityEtag`
      self$`limit` <- QueryObject$`limit`
      self$`offset` <- QueryObject$`offset`
      self$`selectedFacets` <- ApiClient$new()$deserializeObj(QueryObject$`selectedFacets`, "array[FacetColumnRequest]", loadNamespace("synclient"))
      self$`sort` <- ApiClient$new()$deserializeObj(QueryObject$`sort`, "array[SortItem]", loadNamespace("synclient"))
      self$`sql` <- QueryObject$`sql`
      self
    }
  )
)
