# Platform Repository Service
#
# Platform Repository Service - Sage Bionetworks Platform 
#
# The version of the OpenAPI document: develop-SNAPSHOT
# Contact: thomas.yu@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title QuestionResponse
#'
#' @description QuestionResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field concreteType  character [optional]
#'
#' @field questionIndex  integer [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
QuestionResponse <- R6::R6Class(
  'QuestionResponse',
  public = list(
    `concreteType` = NULL,
    `questionIndex` = NULL,
    initialize = function(
        `concreteType`=NULL, `questionIndex`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`concreteType`)) {
        stopifnot(is.character(`concreteType`), length(`concreteType`) == 1)
        self$`concreteType` <- `concreteType`
      }
      if (!is.null(`questionIndex`)) {
        stopifnot(is.numeric(`questionIndex`), length(`questionIndex`) == 1)
        self$`questionIndex` <- `questionIndex`
      }
    },
    toJSON = function() {
      QuestionResponseObject <- list()
      if (!is.null(self$`concreteType`)) {
        QuestionResponseObject[['concreteType']] <-
          self$`concreteType`
      }
      if (!is.null(self$`questionIndex`)) {
        QuestionResponseObject[['questionIndex']] <-
          self$`questionIndex`
      }

      QuestionResponseObject
    },
    fromJSON = function(QuestionResponseJson) {
      QuestionResponseObject <- jsonlite::fromJSON(QuestionResponseJson)
      if (!is.null(QuestionResponseObject$`concreteType`)) {
        self$`concreteType` <- QuestionResponseObject$`concreteType`
      }
      if (!is.null(QuestionResponseObject$`questionIndex`)) {
        self$`questionIndex` <- QuestionResponseObject$`questionIndex`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`concreteType`)) {
        sprintf(
        '"concreteType":
          "%s"
                ',
        self$`concreteType`
        )},
        if (!is.null(self$`questionIndex`)) {
        sprintf(
        '"questionIndex":
          %d
                ',
        self$`questionIndex`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(QuestionResponseJson) {
      QuestionResponseObject <- jsonlite::fromJSON(QuestionResponseJson)
      self$`concreteType` <- QuestionResponseObject$`concreteType`
      self$`questionIndex` <- QuestionResponseObject$`questionIndex`
      self
    }
  )
)

