# Platform Repository Service
#
# Platform Repository Service - Sage Bionetworks Platform 
#
# The version of the OpenAPI document: develop-SNAPSHOT
# Contact: thomas.yu@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ResponseCorrectness
#' @description ResponseCorrectness Class
#' @format An \code{R6Class} generator object
#' @field isCorrect  character [optional]
#'
#' @field question  \link{Question} [optional]
#'
#' @field response  \link{QuestionResponse} [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ResponseCorrectness <- R6::R6Class(
  'ResponseCorrectness',
  public = list(
    `isCorrect` = NULL,
    `question` = NULL,
    `response` = NULL,
    initialize = function(`isCorrect`=NULL, `question`=NULL, `response`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`isCorrect`)) {
        self$`isCorrect` <- `isCorrect`
      }
      if (!is.null(`question`)) {
        stopifnot(R6::is.R6(`question`))
        self$`question` <- `question`
      }
      if (!is.null(`response`)) {
        stopifnot(R6::is.R6(`response`))
        self$`response` <- `response`
      }
    },
    toJSON = function() {
      ResponseCorrectnessObject <- list()
      if (!is.null(self$`isCorrect`)) {
        ResponseCorrectnessObject[['isCorrect']] <-
          self$`isCorrect`
      }
      if (!is.null(self$`question`)) {
        ResponseCorrectnessObject[['question']] <-
          self$`question`$toJSON()
      }
      if (!is.null(self$`response`)) {
        ResponseCorrectnessObject[['response']] <-
          self$`response`$toJSON()
      }

      ResponseCorrectnessObject
    },
    fromJSON = function(ResponseCorrectnessJson) {
      ResponseCorrectnessObject <- jsonlite::fromJSON(ResponseCorrectnessJson)
      if (!is.null(ResponseCorrectnessObject$`isCorrect`)) {
        self$`isCorrect` <- ResponseCorrectnessObject$`isCorrect`
      }
      if (!is.null(ResponseCorrectnessObject$`question`)) {
        questionObject <- Question$new()
        questionObject$fromJSON(jsonlite::toJSON(ResponseCorrectnessObject$question, auto_unbox = TRUE, digits = NA))
        self$`question` <- questionObject
      }
      if (!is.null(ResponseCorrectnessObject$`response`)) {
        responseObject <- QuestionResponse$new()
        responseObject$fromJSON(jsonlite::toJSON(ResponseCorrectnessObject$response, auto_unbox = TRUE, digits = NA))
        self$`response` <- responseObject
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`isCorrect`)) {
        sprintf(
        '"isCorrect":
          "%s"
                ',
        self$`isCorrect`
        )},
        if (!is.null(self$`question`)) {
        sprintf(
        '"question":
        %s
        ',
        jsonlite::toJSON(self$`question`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`response`)) {
        sprintf(
        '"response":
        %s
        ',
        jsonlite::toJSON(self$`response`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ResponseCorrectnessJson) {
      ResponseCorrectnessObject <- jsonlite::fromJSON(ResponseCorrectnessJson)
      self$`isCorrect` <- ResponseCorrectnessObject$`isCorrect`
      self$`question` <- Question$new()$fromJSON(jsonlite::toJSON(ResponseCorrectnessObject$question, auto_unbox = TRUE, digits = NA))
      self$`response` <- QuestionResponse$new()$fromJSON(jsonlite::toJSON(ResponseCorrectnessObject$response, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)
