# Platform Repository Service
#
# Platform Repository Service - Sage Bionetworks Platform 
#
# The version of the OpenAPI document: develop-SNAPSHOT
# Contact: thomas.yu@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Settings
#' @description Settings Class
#' @format An \code{R6Class} generator object
#' @field markEmailedMessagesAsRead  character [optional]
#'
#' @field sendEmailNotifications  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Settings <- R6::R6Class(
  'Settings',
  public = list(
    `markEmailedMessagesAsRead` = NULL,
    `sendEmailNotifications` = NULL,
    initialize = function(`markEmailedMessagesAsRead`=FALSE, `sendEmailNotifications`=TRUE, ...){
      local.optional.var <- list(...)
      if (!is.null(`markEmailedMessagesAsRead`)) {
        self$`markEmailedMessagesAsRead` <- `markEmailedMessagesAsRead`
      }
      if (!is.null(`sendEmailNotifications`)) {
        self$`sendEmailNotifications` <- `sendEmailNotifications`
      }
    },
    toJSON = function() {
      SettingsObject <- list()
      if (!is.null(self$`markEmailedMessagesAsRead`)) {
        SettingsObject[['markEmailedMessagesAsRead']] <-
          self$`markEmailedMessagesAsRead`
      }
      if (!is.null(self$`sendEmailNotifications`)) {
        SettingsObject[['sendEmailNotifications']] <-
          self$`sendEmailNotifications`
      }

      SettingsObject
    },
    fromJSON = function(SettingsJson) {
      SettingsObject <- jsonlite::fromJSON(SettingsJson)
      if (!is.null(SettingsObject$`markEmailedMessagesAsRead`)) {
        self$`markEmailedMessagesAsRead` <- SettingsObject$`markEmailedMessagesAsRead`
      }
      if (!is.null(SettingsObject$`sendEmailNotifications`)) {
        self$`sendEmailNotifications` <- SettingsObject$`sendEmailNotifications`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`markEmailedMessagesAsRead`)) {
        sprintf(
        '"markEmailedMessagesAsRead":
          "%s"
                ',
        self$`markEmailedMessagesAsRead`
        )},
        if (!is.null(self$`sendEmailNotifications`)) {
        sprintf(
        '"sendEmailNotifications":
          "%s"
                ',
        self$`sendEmailNotifications`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(SettingsJson) {
      SettingsObject <- jsonlite::fromJSON(SettingsJson)
      self$`markEmailedMessagesAsRead` <- SettingsObject$`markEmailedMessagesAsRead`
      self$`sendEmailNotifications` <- SettingsObject$`sendEmailNotifications`
      self
    }
  )
)
