#' Synapse REST API
#'
#' No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#'
#' The version of the OpenAPI document: v1
#' Generated by: https://openapi-generator.tech
#'
#' @docType class
#' @title StorageReportServices operations
#' @description StorageReportServicesApi
#' @format An \code{R6Class} generator object
#' @field api_client Handles the client-server communication.
#'
#' @section Methods:
#' \describe{
#' \strong{ GetRepoV1StorageReportAsyncGetAsyncToken } \emph{  }
#'
#' \itemize{
#' \item \emph{ @param } async_token character
#' \item \emph{ @returnType } \link{OrgSagebionetworksRepoModelReportDownloadStorageReportResponse} \cr
#'
#'
#' \item status code : 200 | The results of the call, including a pre-signed URL to download the report.
#'
#' \item return type : OrgSagebionetworksRepoModelReportDownloadStorageReportResponse
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ PostRepoV1StorageReportAsyncStart } \emph{  }
#'
#' \itemize{
#' \item \emph{ @param } org_sagebionetworks_repo_model_report_download_storage_report_request \link{OrgSagebionetworksRepoModelReportDownloadStorageReportRequest}
#' \item \emph{ @returnType } \link{OrgSagebionetworksRepoModelAsynchAsyncJobId} \cr
#'
#'
#' \item status code : 202 | The asynchronous job ID
#'
#' \item return type : OrgSagebionetworksRepoModelAsynchAsyncJobId
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' }
#'
#'
#' @examples
#' \dontrun{
#' ####################  GetRepoV1StorageReportAsyncGetAsyncToken  ####################
#'
#' library(synclient)
#' var_async_token <- "async_token_example" # character | The async job token from the create/update call
#'
#' api_instance <- StorageReportServicesApi$new()
#'
#' # Configure HTTP bearer authorization: bearerAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$GetRepoV1StorageReportAsyncGetAsyncToken(var_async_tokendata_file = "result.txt")
#' result <- api_instance$GetRepoV1StorageReportAsyncGetAsyncToken(var_async_token)
#' dput(result)
#'
#'
#' ####################  PostRepoV1StorageReportAsyncStart  ####################
#'
#' library(synclient)
#' var_org_sagebionetworks_repo_model_report_download_storage_report_request <- org.sagebionetworks.repo.model.report.DownloadStorageReportRequest$new("concreteType_example", "reportType_example") # OrgSagebionetworksRepoModelReportDownloadStorageReportRequest | 
#'
#' api_instance <- StorageReportServicesApi$new()
#'
#' # Configure HTTP bearer authorization: bearerAuth
#' api_instance$api_client$bearer_token <- Sys.getenv("BEARER_TOKEN")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$PostRepoV1StorageReportAsyncStart(var_org_sagebionetworks_repo_model_report_download_storage_report_requestdata_file = "result.txt")
#' result <- api_instance$PostRepoV1StorageReportAsyncStart(var_org_sagebionetworks_repo_model_report_download_storage_report_request)
#' dput(result)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
StorageReportServicesApi <- R6::R6Class(
  "StorageReportServicesApi",
  public = list(
    api_client = NULL,
    #' Initialize a new StorageReportServicesApi.
    #'
    #' @description
    #' Initialize a new StorageReportServicesApi.
    #'
    #' @param api_client An instance of API client.
    #' @export
    initialize = function(api_client) {
      if (!missing(api_client)) {
        self$api_client <- api_client
      } else {
        self$api_client <- ApiClient$new()
      }
    },
    #' 
    #'
    #' @description
    #' 
    #'
    #' @param async_token The async job token from the create/update call
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return OrgSagebionetworksRepoModelReportDownloadStorageReportResponse
    #' @export
    GetRepoV1StorageReportAsyncGetAsyncToken = function(async_token, data_file = NULL, ...) {
      local_var_response <- self$GetRepoV1StorageReportAsyncGetAsyncTokenWithHttpInfo(async_token, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' 
    #'
    #' @description
    #' 
    #'
    #' @param async_token The async job token from the create/update call
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (OrgSagebionetworksRepoModelReportDownloadStorageReportResponse) with additional information such as HTTP status code, headers
    #' @export
    GetRepoV1StorageReportAsyncGetAsyncTokenWithHttpInfo = function(async_token, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`async_token`)) {
        stop("Missing required parameter `async_token`.")
      }


      local_var_url_path <- "/repo/v1/storageReport/async/get/{asyncToken}"
      if (!missing(`async_token`)) {
        local_var_url_path <- gsub("\\{asyncToken\\}", URLencode(as.character(`async_token`), reserved = TRUE), local_var_url_path)
      }

      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response_as_text(), "OrgSagebionetworksRepoModelReportDownloadStorageReportResponse", loadNamespace("synclient")),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    },
    #' 
    #'
    #' @description
    #' 
    #'
    #' @param org_sagebionetworks_repo_model_report_download_storage_report_request 
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return OrgSagebionetworksRepoModelAsynchAsyncJobId
    #' @export
    PostRepoV1StorageReportAsyncStart = function(org_sagebionetworks_repo_model_report_download_storage_report_request, data_file = NULL, ...) {
      local_var_response <- self$PostRepoV1StorageReportAsyncStartWithHttpInfo(org_sagebionetworks_repo_model_report_download_storage_report_request, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' 
    #'
    #' @description
    #' 
    #'
    #' @param org_sagebionetworks_repo_model_report_download_storage_report_request 
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (OrgSagebionetworksRepoModelAsynchAsyncJobId) with additional information such as HTTP status code, headers
    #' @export
    PostRepoV1StorageReportAsyncStartWithHttpInfo = function(org_sagebionetworks_repo_model_report_download_storage_report_request, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`org_sagebionetworks_repo_model_report_download_storage_report_request`)) {
        stop("Missing required parameter `org_sagebionetworks_repo_model_report_download_storage_report_request`.")
      }


      if (!is.null(`org_sagebionetworks_repo_model_report_download_storage_report_request`)) {
        local_var_body <- `org_sagebionetworks_repo_model_report_download_storage_report_request`$toJSONString()
      } else {
        body <- NULL
      }

      local_var_url_path <- "/repo/v1/storageReport/async/start"
      # Bearer token
      if (!is.null(self$api_client$bearer_token)) {
        header_params["Authorization"] <- paste("Bearer", self$api_client$bearer_token, sep = " ")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list("application/json")

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "POST",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response_as_text(), "OrgSagebionetworksRepoModelAsynchAsyncJobId", loadNamespace("synclient")),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        local_var_resp
      }
    }
  )
)
