# Platform Repository Service
#
# Platform Repository Service - Sage Bionetworks Platform 
#
# The version of the OpenAPI document: develop-SNAPSHOT
# Contact: thomas.yu@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title StringAnnotation
#' @description StringAnnotation Class
#' @format An \code{R6Class} generator object
#' @field isPrivate  character [optional]
#'
#' @field key  character [optional]
#'
#' @field value  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
StringAnnotation <- R6::R6Class(
  'StringAnnotation',
  public = list(
    `isPrivate` = NULL,
    `key` = NULL,
    `value` = NULL,
    initialize = function(`isPrivate`=NULL, `key`=NULL, `value`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`isPrivate`)) {
        self$`isPrivate` <- `isPrivate`
      }
      if (!is.null(`key`)) {
        stopifnot(is.character(`key`), length(`key`) == 1)
        self$`key` <- `key`
      }
      if (!is.null(`value`)) {
        stopifnot(is.character(`value`), length(`value`) == 1)
        self$`value` <- `value`
      }
    },
    toJSON = function() {
      StringAnnotationObject <- list()
      if (!is.null(self$`isPrivate`)) {
        StringAnnotationObject[['isPrivate']] <-
          self$`isPrivate`
      }
      if (!is.null(self$`key`)) {
        StringAnnotationObject[['key']] <-
          self$`key`
      }
      if (!is.null(self$`value`)) {
        StringAnnotationObject[['value']] <-
          self$`value`
      }

      StringAnnotationObject
    },
    fromJSON = function(StringAnnotationJson) {
      StringAnnotationObject <- jsonlite::fromJSON(StringAnnotationJson)
      if (!is.null(StringAnnotationObject$`isPrivate`)) {
        self$`isPrivate` <- StringAnnotationObject$`isPrivate`
      }
      if (!is.null(StringAnnotationObject$`key`)) {
        self$`key` <- StringAnnotationObject$`key`
      }
      if (!is.null(StringAnnotationObject$`value`)) {
        self$`value` <- StringAnnotationObject$`value`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`isPrivate`)) {
        sprintf(
        '"isPrivate":
          "%s"
                ',
        self$`isPrivate`
        )},
        if (!is.null(self$`key`)) {
        sprintf(
        '"key":
          "%s"
                ',
        self$`key`
        )},
        if (!is.null(self$`value`)) {
        sprintf(
        '"value":
          "%s"
                ',
        self$`value`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(StringAnnotationJson) {
      StringAnnotationObject <- jsonlite::fromJSON(StringAnnotationJson)
      self$`isPrivate` <- StringAnnotationObject$`isPrivate`
      self$`key` <- StringAnnotationObject$`key`
      self$`value` <- StringAnnotationObject$`value`
      self
    }
  )
)
