# Platform Repository Service
#
# Platform Repository Service - Sage Bionetworks Platform 
#
# The version of the OpenAPI document: develop-SNAPSHOT
# Contact: thomas.yu@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title SubmissionStatusBatch
#' @description SubmissionStatusBatch Class
#' @format An \code{R6Class} generator object
#' @field batchToken  character [optional]
#'
#' @field isFirstBatch  character [optional]
#'
#' @field isLastBatch  character [optional]
#'
#' @field statuses  list( \link{SubmissionStatusModel} ) [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
SubmissionStatusBatch <- R6::R6Class(
  'SubmissionStatusBatch',
  public = list(
    `batchToken` = NULL,
    `isFirstBatch` = NULL,
    `isLastBatch` = NULL,
    `statuses` = NULL,
    initialize = function(`batchToken`=NULL, `isFirstBatch`=NULL, `isLastBatch`=NULL, `statuses`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`batchToken`)) {
        stopifnot(is.character(`batchToken`), length(`batchToken`) == 1)
        self$`batchToken` <- `batchToken`
      }
      if (!is.null(`isFirstBatch`)) {
        self$`isFirstBatch` <- `isFirstBatch`
      }
      if (!is.null(`isLastBatch`)) {
        self$`isLastBatch` <- `isLastBatch`
      }
      if (!is.null(`statuses`)) {
        stopifnot(is.vector(`statuses`), length(`statuses`) != 0)
        sapply(`statuses`, function(x) stopifnot(R6::is.R6(x)))
        self$`statuses` <- `statuses`
      }
    },
    toJSON = function() {
      SubmissionStatusBatchObject <- list()
      if (!is.null(self$`batchToken`)) {
        SubmissionStatusBatchObject[['batchToken']] <-
          self$`batchToken`
      }
      if (!is.null(self$`isFirstBatch`)) {
        SubmissionStatusBatchObject[['isFirstBatch']] <-
          self$`isFirstBatch`
      }
      if (!is.null(self$`isLastBatch`)) {
        SubmissionStatusBatchObject[['isLastBatch']] <-
          self$`isLastBatch`
      }
      if (!is.null(self$`statuses`)) {
        SubmissionStatusBatchObject[['statuses']] <-
          lapply(self$`statuses`, function(x) x$toJSON())
      }

      SubmissionStatusBatchObject
    },
    fromJSON = function(SubmissionStatusBatchJson) {
      SubmissionStatusBatchObject <- jsonlite::fromJSON(SubmissionStatusBatchJson)
      if (!is.null(SubmissionStatusBatchObject$`batchToken`)) {
        self$`batchToken` <- SubmissionStatusBatchObject$`batchToken`
      }
      if (!is.null(SubmissionStatusBatchObject$`isFirstBatch`)) {
        self$`isFirstBatch` <- SubmissionStatusBatchObject$`isFirstBatch`
      }
      if (!is.null(SubmissionStatusBatchObject$`isLastBatch`)) {
        self$`isLastBatch` <- SubmissionStatusBatchObject$`isLastBatch`
      }
      if (!is.null(SubmissionStatusBatchObject$`statuses`)) {
        self$`statuses` <- ApiClient$new()$deserializeObj(SubmissionStatusBatchObject$`statuses`, "array[SubmissionStatusModel]", loadNamespace("synclient"))
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`batchToken`)) {
        sprintf(
        '"batchToken":
          "%s"
                ',
        self$`batchToken`
        )},
        if (!is.null(self$`isFirstBatch`)) {
        sprintf(
        '"isFirstBatch":
          "%s"
                ',
        self$`isFirstBatch`
        )},
        if (!is.null(self$`isLastBatch`)) {
        sprintf(
        '"isLastBatch":
          "%s"
                ',
        self$`isLastBatch`
        )},
        if (!is.null(self$`statuses`)) {
        sprintf(
        '"statuses":
        [%s]
',
        paste(sapply(self$`statuses`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(SubmissionStatusBatchJson) {
      SubmissionStatusBatchObject <- jsonlite::fromJSON(SubmissionStatusBatchJson)
      self$`batchToken` <- SubmissionStatusBatchObject$`batchToken`
      self$`isFirstBatch` <- SubmissionStatusBatchObject$`isFirstBatch`
      self$`isLastBatch` <- SubmissionStatusBatchObject$`isLastBatch`
      self$`statuses` <- ApiClient$new()$deserializeObj(SubmissionStatusBatchObject$`statuses`, "array[SubmissionStatusModel]", loadNamespace("synclient"))
      self
    }
  )
)
