# Platform Repository Service
#
# Platform Repository Service - Sage Bionetworks Platform 
#
# The version of the OpenAPI document: develop-SNAPSHOT
# Contact: thomas.yu@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title TableUpdateTransactionRequest
#'
#' @description TableUpdateTransactionRequest Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field changes  list( \link{TableUpdateRequest} ) [optional]
#'
#' @field concreteType  character [optional]
#'
#' @field createSnapshot  character [optional]
#'
#' @field entityId  character [optional]
#'
#' @field snapshotOptions  \link{SnapshotRequest} [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
TableUpdateTransactionRequest <- R6::R6Class(
  'TableUpdateTransactionRequest',
  public = list(
    `changes` = NULL,
    `concreteType` = NULL,
    `createSnapshot` = NULL,
    `entityId` = NULL,
    `snapshotOptions` = NULL,
    initialize = function(
        `changes`=NULL, `concreteType`=NULL, `createSnapshot`=NULL, `entityId`=NULL, `snapshotOptions`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`changes`)) {
        stopifnot(is.vector(`changes`), length(`changes`) != 0)
        sapply(`changes`, function(x) stopifnot(R6::is.R6(x)))
        self$`changes` <- `changes`
      }
      if (!is.null(`concreteType`)) {
        stopifnot(is.character(`concreteType`), length(`concreteType`) == 1)
        self$`concreteType` <- `concreteType`
      }
      if (!is.null(`createSnapshot`)) {
        self$`createSnapshot` <- `createSnapshot`
      }
      if (!is.null(`entityId`)) {
        stopifnot(is.character(`entityId`), length(`entityId`) == 1)
        self$`entityId` <- `entityId`
      }
      if (!is.null(`snapshotOptions`)) {
        stopifnot(R6::is.R6(`snapshotOptions`))
        self$`snapshotOptions` <- `snapshotOptions`
      }
    },
    toJSON = function() {
      TableUpdateTransactionRequestObject <- list()
      if (!is.null(self$`changes`)) {
        TableUpdateTransactionRequestObject[['changes']] <-
          lapply(self$`changes`, function(x) x$toJSON())
      }
      if (!is.null(self$`concreteType`)) {
        TableUpdateTransactionRequestObject[['concreteType']] <-
          self$`concreteType`
      }
      if (!is.null(self$`createSnapshot`)) {
        TableUpdateTransactionRequestObject[['createSnapshot']] <-
          self$`createSnapshot`
      }
      if (!is.null(self$`entityId`)) {
        TableUpdateTransactionRequestObject[['entityId']] <-
          self$`entityId`
      }
      if (!is.null(self$`snapshotOptions`)) {
        TableUpdateTransactionRequestObject[['snapshotOptions']] <-
          self$`snapshotOptions`$toJSON()
      }

      TableUpdateTransactionRequestObject
    },
    fromJSON = function(TableUpdateTransactionRequestJson) {
      TableUpdateTransactionRequestObject <- jsonlite::fromJSON(TableUpdateTransactionRequestJson)
      if (!is.null(TableUpdateTransactionRequestObject$`changes`)) {
        self$`changes` <- ApiClient$new()$deserializeObj(TableUpdateTransactionRequestObject$`changes`, "array[TableUpdateRequest]", loadNamespace("synclient"))
      }
      if (!is.null(TableUpdateTransactionRequestObject$`concreteType`)) {
        self$`concreteType` <- TableUpdateTransactionRequestObject$`concreteType`
      }
      if (!is.null(TableUpdateTransactionRequestObject$`createSnapshot`)) {
        self$`createSnapshot` <- TableUpdateTransactionRequestObject$`createSnapshot`
      }
      if (!is.null(TableUpdateTransactionRequestObject$`entityId`)) {
        self$`entityId` <- TableUpdateTransactionRequestObject$`entityId`
      }
      if (!is.null(TableUpdateTransactionRequestObject$`snapshotOptions`)) {
        snapshotOptionsObject <- SnapshotRequest$new()
        snapshotOptionsObject$fromJSON(jsonlite::toJSON(TableUpdateTransactionRequestObject$snapshotOptions, auto_unbox = TRUE, digits = NA))
        self$`snapshotOptions` <- snapshotOptionsObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`changes`)) {
        sprintf(
        '"changes":
        [%s]
',
        paste(sapply(self$`changes`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`concreteType`)) {
        sprintf(
        '"concreteType":
          "%s"
                ',
        self$`concreteType`
        )},
        if (!is.null(self$`createSnapshot`)) {
        sprintf(
        '"createSnapshot":
          "%s"
                ',
        self$`createSnapshot`
        )},
        if (!is.null(self$`entityId`)) {
        sprintf(
        '"entityId":
          "%s"
                ',
        self$`entityId`
        )},
        if (!is.null(self$`snapshotOptions`)) {
        sprintf(
        '"snapshotOptions":
        %s
        ',
        jsonlite::toJSON(self$`snapshotOptions`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(TableUpdateTransactionRequestJson) {
      TableUpdateTransactionRequestObject <- jsonlite::fromJSON(TableUpdateTransactionRequestJson)
      self$`changes` <- ApiClient$new()$deserializeObj(TableUpdateTransactionRequestObject$`changes`, "array[TableUpdateRequest]", loadNamespace("synclient"))
      self$`concreteType` <- TableUpdateTransactionRequestObject$`concreteType`
      self$`createSnapshot` <- TableUpdateTransactionRequestObject$`createSnapshot`
      self$`entityId` <- TableUpdateTransactionRequestObject$`entityId`
      self$`snapshotOptions` <- SnapshotRequest$new()$fromJSON(jsonlite::toJSON(TableUpdateTransactionRequestObject$snapshotOptions, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)

