# Platform Repository Service
#
# Platform Repository Service - Sage Bionetworks Platform 
#
# The version of the OpenAPI document: develop-SNAPSHOT
# Contact: thomas.yu@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title TeamServices operations
#' @description synclient.TeamServices
#' @format An \code{R6Class} generator object
#' @field apiClient Handles the client-server communication.
#'
#' @section Methods:
#' \describe{
#' \strong{ AddTeamMember } \emph{ Add a member to the Team. }
#' Add a member to the Team.  If the one making the request is the user to be added, then the user must have an open invitation from the Team.  If the one making the request is an administrator on the Team, then there must be a pending request from the user to the Team, asking to be added. If both teamEndpoint and notificationUnsubscribeEndpoint are provided, notification email(s) will be sent to the appropriate parties. 
#'
#' \itemize{
#' \item \emph{ @param } id character
#' \item \emph{ @param } principal.id character
#' \item \emph{ @param } notification.unsubscribe.endpoint character
#' \item \emph{ @param } team.endpoint character
#'
#'
#' \item status code : 204 | The resource has been added.
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ AddTeamMemberViaSignedToken } \emph{ Add a member to the Team. }
#' Add a member to the Team.  Note: The request is authenticated by a hash message authentication code in the request body, generated by Synapse.  The intended use of this service is by the portal, completing a round trip with a &#39;one-click join-team&#39; link provided to the user by Synapse via email. If both teamEndpoint and notificationUnsubscribeEndpoint are provided, notification email(s) will be sent to the appropriate parties. 
#'
#' \itemize{
#' \item \emph{ @param } notification.unsubscribe.endpoint character
#' \item \emph{ @param } team.endpoint character
#' \item \emph{ @param } join.team.signed.token \link{JoinTeamSignedToken}
#' \item \emph{ @returnType } \link{ResponseMessage} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : ResponseMessage 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ CreateTeam } \emph{ Create a new Team. }
#' Create a new Team. The passed request body may contain the following fields:  &lt;ul&gt;  &lt;li&gt;name - Give your new Team a name.  The name must be unique, not used by an existing Team (required).&lt;/li&gt;  &lt;li&gt;description - a short text description of the Team&#39;&#39;s purpose (optional).&lt;/li&gt;  &lt;li&gt;icon - a fileHandle ID for an icon image file previously uploaded to Synapse (optional).&lt;/li&gt;  &lt;/ul&gt;  &lt;p&gt;  To specify a Team icon, the icon file must first be uploaded to Synapse as &lt;a href&#x3D;\&quot;${org.sagebionetworks.repo.model.file.FileHandle}\&quot;&gt;FileHandle&lt;/a&gt; (see &lt;a href&#x3D;\&quot;${org.sagebionetworks.file.controller.UploadController}\&quot;&gt;File Services&lt;/a&gt;). The FileHandle ID can then be put into the Team&#39;&#39;s icon field. 
#'
#' \itemize{
#' \item \emph{ @param } team \link{Team}
#' \item \emph{ @returnType } \link{Team} \cr
#'
#'
#' \item status code : 201 | Success
#'
#' \item return type : Team 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ DeleteTeam } \emph{ Delete the Team. }
#' Delete the Team. Note: The client must be a Team administrator to make this request. 
#'
#' \itemize{
#' \item \emph{ @param } id character
#'
#'
#' \item status code : 204 | The resource has been deleted.
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ FilePreviewRedirectUrlForTeamIcon } \emph{ Retrieve the download URL for the Team icon preview, or receive a redirect response to said URL.  }
#' Retrieve the download URL for the Team icon preview, or receive a redirect response to said URL. 
#'
#' \itemize{
#' \item \emph{ @param } id character
#' \item \emph{ @param } redirect character
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : character 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ FileRedirectUrlForTeamIcon } \emph{ Retrieve the download URL for the Team icon, or receive a redirect response to said URL  }
#' Retrieve the download URL for the Team icon, or receive a redirect response to said URL.
#'
#' \itemize{
#' \item \emph{ @param } id character
#' \item \emph{ @param } redirect character
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : character 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ GetTeam } \emph{ Retrieve the metadata for a specified Team. }
#' Retrieve the metadata for a specified Team.  &lt;p&gt;  &lt;b&gt;Service Limits&lt;/b&gt;  &lt;table border&#x3D;\&quot;1\&quot;&gt;  &lt;tr&gt;  &lt;th&gt;resource&lt;/th&gt;  &lt;th&gt;limit&lt;/th&gt;  &lt;/tr&gt;  &lt;tr&gt;  &lt;td&gt;The maximum frequency this method can be called&lt;/td&gt;  &lt;td&gt;1 calls per second&lt;/td&gt;  &lt;/tr&gt;  &lt;/table&gt;  &lt;/p&gt; 
#'
#' \itemize{
#' \item \emph{ @param } id character
#' \item \emph{ @returnType } \link{Team} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : Team 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ GetTeamAcl } \emph{ Retrieve the AccessControlList for a specified Team. }
#' Retrieve the AccessControlList for a specified Team.
#'
#' \itemize{
#' \item \emph{ @param } id character
#' \item \emph{ @returnType } \link{AccessControlList} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : AccessControlList 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ GetTeamIdsByMember } \emph{ Retrieve a paginated list of IDs of Teams to which the given user belongs. }
#' Retrieve a paginated list of IDs of Teams to which the given user belongs. If sorting is desired, both sort and ascending must be specified. If they are omitted, results are not sorted. 
#'
#' \itemize{
#' \item \emph{ @param } id character
#' \item \emph{ @param } ascending character
#' \item \emph{ @param } next.page.token character
#' \item \emph{ @param } sort Enum < [TEAM_NAME] > 
#' \item \emph{ @returnType } \link{PaginatedTeamIds} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : PaginatedTeamIds 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ GetTeamMember } \emph{ . }
#' &#39;&lt;p&gt;  &lt;b&gt;Service Limits&lt;/b&gt;  &lt;table border&#x3D;\&quot;1\&quot;&gt;  &lt;tr&gt;  &lt;th&gt;resource&lt;/th&gt;  &lt;th&gt;limit&lt;/th&gt;  &lt;/tr&gt;  &lt;tr&gt;  &lt;td&gt;The maximum frequency this method can be called&lt;/td&gt;  &lt;td&gt;1 calls per second&lt;/td&gt;  &lt;/tr&gt;  &lt;/table&gt;  &lt;/p&gt;&#39; 
#'
#' \itemize{
#' \item \emph{ @param } id character
#' \item \emph{ @param } principal.id character
#' \item \emph{ @returnType } \link{TeamMember} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : TeamMember 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ GetTeamMemberCount } \emph{ Retrieve the number of Team members matching the supplied name prefix. }
#' Retrieve the number of Team members matching the supplied name prefix.  If the prefix is omitted then the number of members in the team is returned.  &lt;br&gt;  Note:  This service has JSONP support:  If the request parameter \&quot;callback&#x3D;jsMethod\&quot; is included (where &#39;jsMethod&#39; is any function name you wish), then the response body will be wrapped in \&quot;jsMethod(...);\&quot;. 
#'
#' \itemize{
#' \item \emph{ @param } id character
#' \item \emph{ @param } fragment character
#' \item \emph{ @returnType } \link{Count} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : Count 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ GetTeamMembers } \emph{ Retrieve a paginated list of Team members matching the supplied name prefix. }
#' Retrieve a paginated list of Team members matching the supplied name prefix.  If the prefix is omitted then all members are returned.  &lt;br&gt;  Note:  This service has JSONP support:  If the request parameter \&quot;callback&#x3D;jsMethod\&quot; is included (where &#39;jsMethod&#39; is any function name you wish), then the response body will be wrapped in \&quot;jsMethod(...);\&quot;. 
#'
#' \itemize{
#' \item \emph{ @param } id character
#' \item \emph{ @param } fragment character
#' \item \emph{ @param } limit integer
#' \item \emph{ @param } member.type Enum < [ADMIN, ALL, MEMBER] > 
#' \item \emph{ @param } offset integer
#' \item \emph{ @returnType } \link{PaginatedResultsOfTeamMember} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : PaginatedResultsOfTeamMember 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ GetTeamMembershipStatus } \emph{ Retrieve the Team Membership Status bundle for a team and user. }
#' Retrieve the Team Membership Status bundle for a team and user.  This says whether a user is a member of a Team, whether there are outstanding membership requests or invitations, and whether the client making the request can add the given user to the given Team. 
#'
#' \itemize{
#' \item \emph{ @param } id character
#' \item \emph{ @param } principal.id character
#' \item \emph{ @returnType } \link{TeamMembershipStatus} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : TeamMembershipStatus 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ GetTeamsByMember } \emph{ Retrieve a paginated list of Teams to which the given user belongs. }
#' Retrieve a paginated list of Teams to which the given user belongs.
#'
#' \itemize{
#' \item \emph{ @param } id character
#' \item \emph{ @param } limit integer
#' \item \emph{ @param } offset integer
#' \item \emph{ @returnType } \link{PaginatedResultsOfTeam} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : PaginatedResultsOfTeam 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ GetTeamsByNameFragment } \emph{ Retrieve a paginated list of Teams in alphabetical order by Team name. }
#' Retrieve a paginated list of Teams matching the supplied name fragment (optional), in alphabetical order by Team name.  &lt;br&gt;  Note:  This service has JSONP support:  If the request parameter \&quot;callback&#x3D;jsMethod\&quot; is included (where &#39;jsMethod&#39; is any function name you wish), then the response body will be wrapped in \&quot;jsMethod(...);\&quot;. 
#'
#' \itemize{
#' \item \emph{ @param } fragment character
#' \item \emph{ @param } limit integer
#' \item \emph{ @param } offset integer
#' \item \emph{ @returnType } \link{PaginatedResultsOfTeam} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : PaginatedResultsOfTeam 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ListTeamMembersGivenTeamandUserList } \emph{ Returns the TeamMember info for a team and a given list of members&#39; principal IDs.  }
#' Returns the TeamMember info for a team and a given list of members&#39; principal IDs. Invalid IDs in the list are ignored:  The results list is simply smaller than the list of IDs passed in. 
#'
#' \itemize{
#' \item \emph{ @param } id character
#' \item \emph{ @param } id.list \link{IdList}
#' \item \emph{ @returnType } \link{ListWrapperOfTeamMember} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : ListWrapperOfTeamMember 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ListTeamMembersGivenUserandTeamList } \emph{ Returns the TeamMember info for a user and a given list of Team IDs. }
#' Returns the TeamMember info for a user and a given list of Team IDs. Not Found status is returned if the user ID is invalid, any of the Team IDs are invalid, or the user is not in any of the given teams. 
#'
#' \itemize{
#' \item \emph{ @param } id character
#' \item \emph{ @param } id.list \link{IdList}
#' \item \emph{ @returnType } \link{ListWrapperOfTeamMember} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : ListWrapperOfTeamMember 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ ListTeams } \emph{ Retrieve a list of Teams given their IDs. }
#' Retrieve a list of Teams given their IDs. Invalid IDs in the list are ignored:  The results list is simply smaller than the list of IDs passed in. 
#'
#' \itemize{
#' \item \emph{ @param } id.list \link{IdList}
#' \item \emph{ @returnType } \link{ListWrapperOfTeam} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : ListWrapperOfTeam 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ RemoveTeamMember } \emph{ Remove the given member from the specified Team. }
#' Remove the given member from the specified Team. Note:  The client must either be a Team administrator or the member being removed. 
#'
#' \itemize{
#' \item \emph{ @param } id character
#' \item \emph{ @param } principal.id character
#'
#'
#' \item status code : 204 | The resource has been deleted.
#'
#'
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ UpdateTeam } \emph{ Update the Team metadata for the specified Team. }
#' Update the Team metadata for the specified Team. Note: The client must be a Team administrator to make this request. 
#'
#' \itemize{
#' \item \emph{ @param } team \link{Team}
#' \item \emph{ @returnType } \link{Team} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : Team 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ UpdateTeamAcl } \emph{ Update the Access Control List for the specified Team. }
#' Update the Access Control List for the specified Team.
#'
#' \itemize{
#' \item \emph{ @param } access.control.list \link{AccessControlList}
#' \item \emph{ @returnType } \link{AccessControlList} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : AccessControlList 
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' }
#'
#'
#' @examples
#' \dontrun{
#' ####################  AddTeamMember  ####################
#'
#' library(synclient)
#' var.id <- 'id_example' # character | the ID of the Team.
#' var.principal.id <- 'principal.id_example' # character | the member's principal ID
#' var.notification.unsubscribe.endpoint <- 'notification.unsubscribe.endpoint_example' # character | the portal prefix for one-click email unsubscription. A signed, serialized token is appended to create the complete URL: <ahref=\"${org.sagebionetworks.repo.model.message.NotificationSettingsSignedToken}\">NotificationSettingsSignedToken</a>' 
#' var.team.endpoint <- 'team.endpoint_example' # character | the portal prefix for the Team URL. The team ID is appended to create the complete URL. 
#'
#' #Add a member to the Team.
#' api.instance <- TeamServicesApi$new()
#'
#' #Configure HTTP basic authorization: bearerAuth
#' # provide your username in the user-serial format
#' api.instance$apiClient$username <- '<user-serial>'; 
#' # provide your api key generated using the developer portal
#' api.instance$apiClient$password <- '<api_key>';
#'
#' result <- api.instance$AddTeamMember(var.id, var.principal.id, notification.unsubscribe.endpoint=var.notification.unsubscribe.endpoint, team.endpoint=var.team.endpoint)
#'
#'
#' ####################  AddTeamMemberViaSignedToken  ####################
#'
#' library(synclient)
#' var.notification.unsubscribe.endpoint <- 'notification.unsubscribe.endpoint_example' # character | notification unsubscribe endpoint
#' var.team.endpoint <- 'team.endpoint_example' # character | Team end point
#' var.join.team.signed.token <- JoinTeamSignedToken$new() # JoinTeamSignedToken | 
#'
#' #Add a member to the Team.
#' api.instance <- TeamServicesApi$new()
#'
#' #Configure HTTP basic authorization: bearerAuth
#' # provide your username in the user-serial format
#' api.instance$apiClient$username <- '<user-serial>'; 
#' # provide your api key generated using the developer portal
#' api.instance$apiClient$password <- '<api_key>';
#'
#' result <- api.instance$AddTeamMemberViaSignedToken(notification.unsubscribe.endpoint=var.notification.unsubscribe.endpoint, team.endpoint=var.team.endpoint, join.team.signed.token=var.join.team.signed.token)
#'
#'
#' ####################  CreateTeam  ####################
#'
#' library(synclient)
#' var.team <- Team$new() # Team | 
#'
#' #Create a new Team.
#' api.instance <- TeamServicesApi$new()
#'
#' #Configure HTTP basic authorization: bearerAuth
#' # provide your username in the user-serial format
#' api.instance$apiClient$username <- '<user-serial>'; 
#' # provide your api key generated using the developer portal
#' api.instance$apiClient$password <- '<api_key>';
#'
#' result <- api.instance$CreateTeam(team=var.team)
#'
#'
#' ####################  DeleteTeam  ####################
#'
#' library(synclient)
#' var.id <- 'id_example' # character | the ID of the Team.
#'
#' #Delete the Team.
#' api.instance <- TeamServicesApi$new()
#'
#' #Configure HTTP basic authorization: bearerAuth
#' # provide your username in the user-serial format
#' api.instance$apiClient$username <- '<user-serial>'; 
#' # provide your api key generated using the developer portal
#' api.instance$apiClient$password <- '<api_key>';
#'
#' result <- api.instance$DeleteTeam(var.id)
#'
#'
#' ####################  FilePreviewRedirectUrlForTeamIcon  ####################
#'
#' library(synclient)
#' var.id <- 'id_example' # character | the ID of the Team.
#' var.redirect <- 'redirect_example' # character | if true or omitted, then redirect to the URL.  If false then simply return the URL. 
#'
#' #Retrieve the download URL for the Team icon preview, or receive a redirect response to said URL. 
#' api.instance <- TeamServicesApi$new()
#'
#' #Configure HTTP basic authorization: bearerAuth
#' # provide your username in the user-serial format
#' api.instance$apiClient$username <- '<user-serial>'; 
#' # provide your api key generated using the developer portal
#' api.instance$apiClient$password <- '<api_key>';
#'
#' result <- api.instance$FilePreviewRedirectUrlForTeamIcon(var.id, redirect=var.redirect)
#'
#'
#' ####################  FileRedirectUrlForTeamIcon  ####################
#'
#' library(synclient)
#' var.id <- 'id_example' # character | the ID of the Team.
#' var.redirect <- 'redirect_example' # character | if true or omitted, then redirect to the URL.  If false then simply return the URL. 
#'
#' #Retrieve the download URL for the Team icon, or receive a redirect response to said URL 
#' api.instance <- TeamServicesApi$new()
#'
#' #Configure HTTP basic authorization: bearerAuth
#' # provide your username in the user-serial format
#' api.instance$apiClient$username <- '<user-serial>'; 
#' # provide your api key generated using the developer portal
#' api.instance$apiClient$password <- '<api_key>';
#'
#' result <- api.instance$FileRedirectUrlForTeamIcon(var.id, redirect=var.redirect)
#'
#'
#' ####################  GetTeam  ####################
#'
#' library(synclient)
#' var.id <- 'id_example' # character | the ID of the Team.
#'
#' #Retrieve the metadata for a specified Team.
#' api.instance <- TeamServicesApi$new()
#'
#' #Configure HTTP basic authorization: bearerAuth
#' # provide your username in the user-serial format
#' api.instance$apiClient$username <- '<user-serial>'; 
#' # provide your api key generated using the developer portal
#' api.instance$apiClient$password <- '<api_key>';
#'
#' result <- api.instance$GetTeam(var.id)
#'
#'
#' ####################  GetTeamAcl  ####################
#'
#' library(synclient)
#' var.id <- 'id_example' # character | the ID of the Team.
#'
#' #Retrieve the AccessControlList for a specified Team.
#' api.instance <- TeamServicesApi$new()
#'
#' #Configure HTTP basic authorization: bearerAuth
#' # provide your username in the user-serial format
#' api.instance$apiClient$username <- '<user-serial>'; 
#' # provide your api key generated using the developer portal
#' api.instance$apiClient$password <- '<api_key>';
#'
#' result <- api.instance$GetTeamAcl(var.id)
#'
#'
#' ####################  GetTeamIdsByMember  ####################
#'
#' library(synclient)
#' var.id <- 'id_example' # character | The ID of the Synapse user.
#' var.ascending <- 'ascending_example' # character | the direction of sort: true for ascending, and false for descending
#' var.next.page.token <- 'next.page.token_example' # character | controls pagination
#' var.sort <- 'sort_example' # character | the field to sort the team IDs on. Available options <a href=\"${org.sagebionetworks.repo.model.TeamSortOrder}\">TeamSortOrder</a> 
#'
#' #Retrieve a paginated list of IDs of Teams to which the given user belongs.
#' api.instance <- TeamServicesApi$new()
#'
#' #Configure HTTP basic authorization: bearerAuth
#' # provide your username in the user-serial format
#' api.instance$apiClient$username <- '<user-serial>'; 
#' # provide your api key generated using the developer portal
#' api.instance$apiClient$password <- '<api_key>';
#'
#' result <- api.instance$GetTeamIdsByMember(var.id, ascending=var.ascending, next.page.token=var.next.page.token, sort=var.sort)
#'
#'
#' ####################  GetTeamMember  ####################
#'
#' library(synclient)
#' var.id <- 'id_example' # character | the ID of the Team.
#' var.principal.id <- 'principal.id_example' # character | the member's principal ID
#'
#' #.
#' api.instance <- TeamServicesApi$new()
#'
#' #Configure HTTP basic authorization: bearerAuth
#' # provide your username in the user-serial format
#' api.instance$apiClient$username <- '<user-serial>'; 
#' # provide your api key generated using the developer portal
#' api.instance$apiClient$password <- '<api_key>';
#'
#' result <- api.instance$GetTeamMember(var.id, var.principal.id)
#'
#'
#' ####################  GetTeamMemberCount  ####################
#'
#' library(synclient)
#' var.id <- 'id_example' # character | the ID of the Team.
#' var.fragment <- 'fragment_example' # character | a prefix of the user's first or last name or email address 
#'
#' #Retrieve the number of Team members matching the supplied name prefix.
#' api.instance <- TeamServicesApi$new()
#'
#' #Configure HTTP basic authorization: bearerAuth
#' # provide your username in the user-serial format
#' api.instance$apiClient$username <- '<user-serial>'; 
#' # provide your api key generated using the developer portal
#' api.instance$apiClient$password <- '<api_key>';
#'
#' result <- api.instance$GetTeamMemberCount(var.id, fragment=var.fragment)
#'
#'
#' ####################  GetTeamMembers  ####################
#'
#' library(synclient)
#' var.id <- 'id_example' # character | the ID of the Team.
#' var.fragment <- 'fragment_example' # character | a prefix of the user's first or last name or email address
#' var.limit <- 10 # integer | the maximum number of members to return.
#' var.member.type <- 'ALL' # character | the type of team user to retrieve
#' var.offset <- 0 # integer | the starting index of the returned results
#'
#' #Retrieve a paginated list of Team members matching the supplied name prefix.
#' api.instance <- TeamServicesApi$new()
#'
#' #Configure HTTP basic authorization: bearerAuth
#' # provide your username in the user-serial format
#' api.instance$apiClient$username <- '<user-serial>'; 
#' # provide your api key generated using the developer portal
#' api.instance$apiClient$password <- '<api_key>';
#'
#' result <- api.instance$GetTeamMembers(var.id, fragment=var.fragment, limit=var.limit, member.type=var.member.type, offset=var.offset)
#'
#'
#' ####################  GetTeamMembershipStatus  ####################
#'
#' library(synclient)
#' var.id <- 'id_example' # character | the ID of the Team.
#' var.principal.id <- 'principal.id_example' # character | the member's principal ID
#'
#' #Retrieve the Team Membership Status bundle for a team and user.
#' api.instance <- TeamServicesApi$new()
#'
#' #Configure HTTP basic authorization: bearerAuth
#' # provide your username in the user-serial format
#' api.instance$apiClient$username <- '<user-serial>'; 
#' # provide your api key generated using the developer portal
#' api.instance$apiClient$password <- '<api_key>';
#'
#' result <- api.instance$GetTeamMembershipStatus(var.id, var.principal.id)
#'
#'
#' ####################  GetTeamsByMember  ####################
#'
#' library(synclient)
#' var.id <- 'id_example' # character | The ID of the Synapse user.
#' var.limit <- 10 # integer | the maximum number of Teams to return (default 10)
#' var.offset <- 0 # integer | the starting index of the returned results (default 0)
#'
#' #Retrieve a paginated list of Teams to which the given user belongs.
#' api.instance <- TeamServicesApi$new()
#'
#' #Configure HTTP basic authorization: bearerAuth
#' # provide your username in the user-serial format
#' api.instance$apiClient$username <- '<user-serial>'; 
#' # provide your api key generated using the developer portal
#' api.instance$apiClient$password <- '<api_key>';
#'
#' result <- api.instance$GetTeamsByMember(var.id, limit=var.limit, offset=var.offset)
#'
#'
#' ####################  GetTeamsByNameFragment  ####################
#'
#' library(synclient)
#' var.fragment <- 'fragment_example' # character | a prefix of the Team name, or a prefix of any sub-string in the name preceded by a space. If omitted, all Teams are returned. 
#' var.limit <- 10 # integer | the maximum number of Teams to return.
#' var.offset <- 0 # integer | the starting index of the returned results (default 0)
#'
#' #Retrieve a paginated list of Teams in alphabetical order by Team name.
#' api.instance <- TeamServicesApi$new()
#'
#' #Configure HTTP basic authorization: bearerAuth
#' # provide your username in the user-serial format
#' api.instance$apiClient$username <- '<user-serial>'; 
#' # provide your api key generated using the developer portal
#' api.instance$apiClient$password <- '<api_key>';
#'
#' result <- api.instance$GetTeamsByNameFragment(fragment=var.fragment, limit=var.limit, offset=var.offset)
#'
#'
#' ####################  ListTeamMembersGivenTeamandUserList  ####################
#'
#' library(synclient)
#' var.id <- 'id_example' # character | the ID of the Team.
#' var.id.list <- IdList$new() # IdList | 
#'
#' #Returns the TeamMember info for a team and a given list of members' principal IDs. 
#' api.instance <- TeamServicesApi$new()
#'
#' #Configure HTTP basic authorization: bearerAuth
#' # provide your username in the user-serial format
#' api.instance$apiClient$username <- '<user-serial>'; 
#' # provide your api key generated using the developer portal
#' api.instance$apiClient$password <- '<api_key>';
#'
#' result <- api.instance$ListTeamMembersGivenTeamandUserList(var.id, id.list=var.id.list)
#'
#'
#' ####################  ListTeamMembersGivenUserandTeamList  ####################
#'
#' library(synclient)
#' var.id <- 'id_example' # character | The ID of the Synapse user.
#' var.id.list <- IdList$new() # IdList | Team IDs
#'
#' #Returns the TeamMember info for a user and a given list of Team IDs.
#' api.instance <- TeamServicesApi$new()
#'
#' #Configure HTTP basic authorization: bearerAuth
#' # provide your username in the user-serial format
#' api.instance$apiClient$username <- '<user-serial>'; 
#' # provide your api key generated using the developer portal
#' api.instance$apiClient$password <- '<api_key>';
#'
#' result <- api.instance$ListTeamMembersGivenUserandTeamList(var.id, id.list=var.id.list)
#'
#'
#' ####################  ListTeams  ####################
#'
#' library(synclient)
#' var.id.list <- IdList$new() # IdList | 
#'
#' #Retrieve a list of Teams given their IDs.
#' api.instance <- TeamServicesApi$new()
#'
#' #Configure HTTP basic authorization: bearerAuth
#' # provide your username in the user-serial format
#' api.instance$apiClient$username <- '<user-serial>'; 
#' # provide your api key generated using the developer portal
#' api.instance$apiClient$password <- '<api_key>';
#'
#' result <- api.instance$ListTeams(id.list=var.id.list)
#'
#'
#' ####################  RemoveTeamMember  ####################
#'
#' library(synclient)
#' var.id <- 'id_example' # character | the ID of the Team.
#' var.principal.id <- 'principal.id_example' # character | the member's principal ID
#'
#' #Remove the given member from the specified Team.
#' api.instance <- TeamServicesApi$new()
#'
#' #Configure HTTP basic authorization: bearerAuth
#' # provide your username in the user-serial format
#' api.instance$apiClient$username <- '<user-serial>'; 
#' # provide your api key generated using the developer portal
#' api.instance$apiClient$password <- '<api_key>';
#'
#' result <- api.instance$RemoveTeamMember(var.id, var.principal.id)
#'
#'
#' ####################  UpdateTeam  ####################
#'
#' library(synclient)
#' var.team <- Team$new() # Team | the new metadata for the Team
#'
#' #Update the Team metadata for the specified Team.
#' api.instance <- TeamServicesApi$new()
#'
#' #Configure HTTP basic authorization: bearerAuth
#' # provide your username in the user-serial format
#' api.instance$apiClient$username <- '<user-serial>'; 
#' # provide your api key generated using the developer portal
#' api.instance$apiClient$password <- '<api_key>';
#'
#' result <- api.instance$UpdateTeam(team=var.team)
#'
#'
#' ####################  UpdateTeamAcl  ####################
#'
#' library(synclient)
#' var.access.control.list <- AccessControlList$new() # AccessControlList | the updated Access Control List
#'
#' #Update the Access Control List for the specified Team.
#' api.instance <- TeamServicesApi$new()
#'
#' #Configure HTTP basic authorization: bearerAuth
#' # provide your username in the user-serial format
#' api.instance$apiClient$username <- '<user-serial>'; 
#' # provide your api key generated using the developer portal
#' api.instance$apiClient$password <- '<api_key>';
#'
#' result <- api.instance$UpdateTeamAcl(access.control.list=var.access.control.list)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom caTools base64encode
#' @export
TeamServicesApi <- R6::R6Class(
  'TeamServicesApi',
  public = list(
    apiClient = NULL,
    initialize = function(apiClient){
      if (!missing(apiClient)) {
        self$apiClient <- apiClient
      }
      else {
        self$apiClient <- ApiClient$new()
      }
    },
    AddTeamMember = function(id, principal.id, notification.unsubscribe.endpoint=NULL, team.endpoint=NULL, ...){
      apiResponse <- self$AddTeamMemberWithHttpInfo(id, principal.id, notification.unsubscribe.endpoint, team.endpoint, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    AddTeamMemberWithHttpInfo = function(id, principal.id, notification.unsubscribe.endpoint=NULL, team.endpoint=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`id`)) {
        stop("Missing required parameter `id`.")
      }

      if (missing(`principal.id`)) {
        stop("Missing required parameter `principal.id`.")
      }

      queryParams['notificationUnsubscribeEndpoint'] <- notification.unsubscribe.endpoint

      queryParams['teamEndpoint'] <- team.endpoint

      urlPath <- "/team/{id}/member/{principalId}"
      if (!missing(`id`)) {
        urlPath <- gsub(paste0("\\{", "id", "\\}"), URLencode(as.character(`id`), reserved = TRUE), urlPath)
      }

      if (!missing(`principal.id`)) {
        urlPath <- gsub(paste0("\\{", "principalId", "\\}"), URLencode(as.character(`principal.id`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "PUT",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        ApiResponse$new(NULL, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    AddTeamMemberViaSignedToken = function(notification.unsubscribe.endpoint=NULL, team.endpoint=NULL, join.team.signed.token=NULL, ...){
      apiResponse <- self$AddTeamMemberViaSignedTokenWithHttpInfo(notification.unsubscribe.endpoint, team.endpoint, join.team.signed.token, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    AddTeamMemberViaSignedTokenWithHttpInfo = function(notification.unsubscribe.endpoint=NULL, team.endpoint=NULL, join.team.signed.token=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      queryParams['notificationUnsubscribeEndpoint'] <- notification.unsubscribe.endpoint

      queryParams['teamEndpoint'] <- team.endpoint

      if (!missing(`join.team.signed.token`)) {
        body <- `join.team.signed.token`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/teamMember"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "PUT",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "ResponseMessage", loadNamespace("synclient")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    CreateTeam = function(team=NULL, ...){
      apiResponse <- self$CreateTeamWithHttpInfo(team, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    CreateTeamWithHttpInfo = function(team=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (!missing(`team`)) {
        body <- `team`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/team"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "Team", loadNamespace("synclient")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    DeleteTeam = function(id, ...){
      apiResponse <- self$DeleteTeamWithHttpInfo(id, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    DeleteTeamWithHttpInfo = function(id, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`id`)) {
        stop("Missing required parameter `id`.")
      }

      urlPath <- "/team/{id}"
      if (!missing(`id`)) {
        urlPath <- gsub(paste0("\\{", "id", "\\}"), URLencode(as.character(`id`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "DELETE",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        ApiResponse$new(NULL, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    FilePreviewRedirectUrlForTeamIcon = function(id, redirect=NULL, ...){
      apiResponse <- self$FilePreviewRedirectUrlForTeamIconWithHttpInfo(id, redirect, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    FilePreviewRedirectUrlForTeamIconWithHttpInfo = function(id, redirect=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`id`)) {
        stop("Missing required parameter `id`.")
      }

      queryParams['redirect'] <- redirect

      urlPath <- "/team/{id}/icon/preview"
      if (!missing(`id`)) {
        urlPath <- gsub(paste0("\\{", "id", "\\}"), URLencode(as.character(`id`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "character", loadNamespace("synclient")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    FileRedirectUrlForTeamIcon = function(id, redirect=NULL, ...){
      apiResponse <- self$FileRedirectUrlForTeamIconWithHttpInfo(id, redirect, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    FileRedirectUrlForTeamIconWithHttpInfo = function(id, redirect=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`id`)) {
        stop("Missing required parameter `id`.")
      }

      queryParams['redirect'] <- redirect

      urlPath <- "/team/{id}/icon"
      if (!missing(`id`)) {
        urlPath <- gsub(paste0("\\{", "id", "\\}"), URLencode(as.character(`id`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "character", loadNamespace("synclient")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    GetTeam = function(id, ...){
      apiResponse <- self$GetTeamWithHttpInfo(id, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    GetTeamWithHttpInfo = function(id, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`id`)) {
        stop("Missing required parameter `id`.")
      }

      urlPath <- "/team/{id}"
      if (!missing(`id`)) {
        urlPath <- gsub(paste0("\\{", "id", "\\}"), URLencode(as.character(`id`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "Team", loadNamespace("synclient")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    GetTeamAcl = function(id, ...){
      apiResponse <- self$GetTeamAclWithHttpInfo(id, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    GetTeamAclWithHttpInfo = function(id, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`id`)) {
        stop("Missing required parameter `id`.")
      }

      urlPath <- "/team/{id}/acl"
      if (!missing(`id`)) {
        urlPath <- gsub(paste0("\\{", "id", "\\}"), URLencode(as.character(`id`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "AccessControlList", loadNamespace("synclient")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    GetTeamIdsByMember = function(id, ascending=NULL, next.page.token=NULL, sort=NULL, ...){
      apiResponse <- self$GetTeamIdsByMemberWithHttpInfo(id, ascending, next.page.token, sort, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    GetTeamIdsByMemberWithHttpInfo = function(id, ascending=NULL, next.page.token=NULL, sort=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`id`)) {
        stop("Missing required parameter `id`.")
      }

      queryParams['ascending'] <- ascending

      queryParams['nextPageToken'] <- next.page.token

      queryParams['sort'] <- sort

      urlPath <- "/user/{id}/team/id"
      if (!missing(`id`)) {
        urlPath <- gsub(paste0("\\{", "id", "\\}"), URLencode(as.character(`id`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "PaginatedTeamIds", loadNamespace("synclient")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    GetTeamMember = function(id, principal.id, ...){
      apiResponse <- self$GetTeamMemberWithHttpInfo(id, principal.id, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    GetTeamMemberWithHttpInfo = function(id, principal.id, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`id`)) {
        stop("Missing required parameter `id`.")
      }

      if (missing(`principal.id`)) {
        stop("Missing required parameter `principal.id`.")
      }

      urlPath <- "/team/{id}/member/{principalId}"
      if (!missing(`id`)) {
        urlPath <- gsub(paste0("\\{", "id", "\\}"), URLencode(as.character(`id`), reserved = TRUE), urlPath)
      }

      if (!missing(`principal.id`)) {
        urlPath <- gsub(paste0("\\{", "principalId", "\\}"), URLencode(as.character(`principal.id`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "TeamMember", loadNamespace("synclient")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    GetTeamMemberCount = function(id, fragment=NULL, ...){
      apiResponse <- self$GetTeamMemberCountWithHttpInfo(id, fragment, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    GetTeamMemberCountWithHttpInfo = function(id, fragment=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`id`)) {
        stop("Missing required parameter `id`.")
      }

      queryParams['fragment'] <- fragment

      urlPath <- "/teamMembers/count/{id}"
      if (!missing(`id`)) {
        urlPath <- gsub(paste0("\\{", "id", "\\}"), URLencode(as.character(`id`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "Count", loadNamespace("synclient")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    GetTeamMembers = function(id, fragment=NULL, limit=10, member.type='ALL', offset=0, ...){
      apiResponse <- self$GetTeamMembersWithHttpInfo(id, fragment, limit, member.type, offset, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    GetTeamMembersWithHttpInfo = function(id, fragment=NULL, limit=10, member.type='ALL', offset=0, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`id`)) {
        stop("Missing required parameter `id`.")
      }

      queryParams['fragment'] <- fragment

      queryParams['limit'] <- limit

      queryParams['memberType'] <- member.type

      queryParams['offset'] <- offset

      urlPath <- "/teamMembers/{id}"
      if (!missing(`id`)) {
        urlPath <- gsub(paste0("\\{", "id", "\\}"), URLencode(as.character(`id`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "PaginatedResultsOfTeamMember", loadNamespace("synclient")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    GetTeamMembershipStatus = function(id, principal.id, ...){
      apiResponse <- self$GetTeamMembershipStatusWithHttpInfo(id, principal.id, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    GetTeamMembershipStatusWithHttpInfo = function(id, principal.id, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`id`)) {
        stop("Missing required parameter `id`.")
      }

      if (missing(`principal.id`)) {
        stop("Missing required parameter `principal.id`.")
      }

      urlPath <- "/team/{id}/member/{principalId}/membershipStatus"
      if (!missing(`id`)) {
        urlPath <- gsub(paste0("\\{", "id", "\\}"), URLencode(as.character(`id`), reserved = TRUE), urlPath)
      }

      if (!missing(`principal.id`)) {
        urlPath <- gsub(paste0("\\{", "principalId", "\\}"), URLencode(as.character(`principal.id`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "TeamMembershipStatus", loadNamespace("synclient")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    GetTeamsByMember = function(id, limit=10, offset=0, ...){
      apiResponse <- self$GetTeamsByMemberWithHttpInfo(id, limit, offset, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    GetTeamsByMemberWithHttpInfo = function(id, limit=10, offset=0, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`id`)) {
        stop("Missing required parameter `id`.")
      }

      queryParams['limit'] <- limit

      queryParams['offset'] <- offset

      urlPath <- "/user/{id}/team"
      if (!missing(`id`)) {
        urlPath <- gsub(paste0("\\{", "id", "\\}"), URLencode(as.character(`id`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "PaginatedResultsOfTeam", loadNamespace("synclient")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    GetTeamsByNameFragment = function(fragment=NULL, limit=10, offset=0, ...){
      apiResponse <- self$GetTeamsByNameFragmentWithHttpInfo(fragment, limit, offset, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    GetTeamsByNameFragmentWithHttpInfo = function(fragment=NULL, limit=10, offset=0, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      queryParams['fragment'] <- fragment

      queryParams['limit'] <- limit

      queryParams['offset'] <- offset

      urlPath <- "/teams"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "PaginatedResultsOfTeam", loadNamespace("synclient")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ListTeamMembersGivenTeamandUserList = function(id, id.list=NULL, ...){
      apiResponse <- self$ListTeamMembersGivenTeamandUserListWithHttpInfo(id, id.list, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ListTeamMembersGivenTeamandUserListWithHttpInfo = function(id, id.list=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`id`)) {
        stop("Missing required parameter `id`.")
      }

      if (!missing(`id.list`)) {
        body <- `id.list`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/team/{id}/memberList"
      if (!missing(`id`)) {
        urlPath <- gsub(paste0("\\{", "id", "\\}"), URLencode(as.character(`id`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "ListWrapperOfTeamMember", loadNamespace("synclient")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ListTeamMembersGivenUserandTeamList = function(id, id.list=NULL, ...){
      apiResponse <- self$ListTeamMembersGivenUserandTeamListWithHttpInfo(id, id.list, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ListTeamMembersGivenUserandTeamListWithHttpInfo = function(id, id.list=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`id`)) {
        stop("Missing required parameter `id`.")
      }

      if (!missing(`id.list`)) {
        body <- `id.list`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/user/{id}/memberList"
      if (!missing(`id`)) {
        urlPath <- gsub(paste0("\\{", "id", "\\}"), URLencode(as.character(`id`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "ListWrapperOfTeamMember", loadNamespace("synclient")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    ListTeams = function(id.list=NULL, ...){
      apiResponse <- self$ListTeamsWithHttpInfo(id.list, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    ListTeamsWithHttpInfo = function(id.list=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (!missing(`id.list`)) {
        body <- `id.list`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/teamList"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "POST",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "ListWrapperOfTeam", loadNamespace("synclient")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    RemoveTeamMember = function(id, principal.id, ...){
      apiResponse <- self$RemoveTeamMemberWithHttpInfo(id, principal.id, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    RemoveTeamMemberWithHttpInfo = function(id, principal.id, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`id`)) {
        stop("Missing required parameter `id`.")
      }

      if (missing(`principal.id`)) {
        stop("Missing required parameter `principal.id`.")
      }

      urlPath <- "/team/{id}/member/{principalId}"
      if (!missing(`id`)) {
        urlPath <- gsub(paste0("\\{", "id", "\\}"), URLencode(as.character(`id`), reserved = TRUE), urlPath)
      }

      if (!missing(`principal.id`)) {
        urlPath <- gsub(paste0("\\{", "principalId", "\\}"), URLencode(as.character(`principal.id`), reserved = TRUE), urlPath)
      }


      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "DELETE",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        ApiResponse$new(NULL, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    UpdateTeam = function(team=NULL, ...){
      apiResponse <- self$UpdateTeamWithHttpInfo(team, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    UpdateTeamWithHttpInfo = function(team=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (!missing(`team`)) {
        body <- `team`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/team"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "PUT",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "Team", loadNamespace("synclient")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    },
    UpdateTeamAcl = function(access.control.list=NULL, ...){
      apiResponse <- self$UpdateTeamAclWithHttpInfo(access.control.list, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    UpdateTeamAclWithHttpInfo = function(access.control.list=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (!missing(`access.control.list`)) {
        body <- `access.control.list`$toJSONString()
      } else {
        body <- NULL
      }

      urlPath <- "/team/acl"

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "PUT",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "AccessControlList", loadNamespace("synclient")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    }
  )
)
