# Platform Repository Service
#
# Platform Repository Service - Sage Bionetworks Platform 
#
# The version of the OpenAPI document: develop-SNAPSHOT
# Contact: thomas.yu@sagebionetworks.org
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title TrashedEntity
#' @description TrashedEntity Class
#' @format An \code{R6Class} generator object
#' @field deletedByPrincipalId  character [optional]
#'
#' @field deletedOn  character [optional]
#'
#' @field entityId  character [optional]
#'
#' @field entityName  character [optional]
#'
#' @field originalParentId  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
TrashedEntity <- R6::R6Class(
  'TrashedEntity',
  public = list(
    `deletedByPrincipalId` = NULL,
    `deletedOn` = NULL,
    `entityId` = NULL,
    `entityName` = NULL,
    `originalParentId` = NULL,
    initialize = function(`deletedByPrincipalId`=NULL, `deletedOn`=NULL, `entityId`=NULL, `entityName`=NULL, `originalParentId`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`deletedByPrincipalId`)) {
        stopifnot(is.character(`deletedByPrincipalId`), length(`deletedByPrincipalId`) == 1)
        self$`deletedByPrincipalId` <- `deletedByPrincipalId`
      }
      if (!is.null(`deletedOn`)) {
        stopifnot(is.character(`deletedOn`), length(`deletedOn`) == 1)
        self$`deletedOn` <- `deletedOn`
      }
      if (!is.null(`entityId`)) {
        stopifnot(is.character(`entityId`), length(`entityId`) == 1)
        self$`entityId` <- `entityId`
      }
      if (!is.null(`entityName`)) {
        stopifnot(is.character(`entityName`), length(`entityName`) == 1)
        self$`entityName` <- `entityName`
      }
      if (!is.null(`originalParentId`)) {
        stopifnot(is.character(`originalParentId`), length(`originalParentId`) == 1)
        self$`originalParentId` <- `originalParentId`
      }
    },
    toJSON = function() {
      TrashedEntityObject <- list()
      if (!is.null(self$`deletedByPrincipalId`)) {
        TrashedEntityObject[['deletedByPrincipalId']] <-
          self$`deletedByPrincipalId`
      }
      if (!is.null(self$`deletedOn`)) {
        TrashedEntityObject[['deletedOn']] <-
          self$`deletedOn`
      }
      if (!is.null(self$`entityId`)) {
        TrashedEntityObject[['entityId']] <-
          self$`entityId`
      }
      if (!is.null(self$`entityName`)) {
        TrashedEntityObject[['entityName']] <-
          self$`entityName`
      }
      if (!is.null(self$`originalParentId`)) {
        TrashedEntityObject[['originalParentId']] <-
          self$`originalParentId`
      }

      TrashedEntityObject
    },
    fromJSON = function(TrashedEntityJson) {
      TrashedEntityObject <- jsonlite::fromJSON(TrashedEntityJson)
      if (!is.null(TrashedEntityObject$`deletedByPrincipalId`)) {
        self$`deletedByPrincipalId` <- TrashedEntityObject$`deletedByPrincipalId`
      }
      if (!is.null(TrashedEntityObject$`deletedOn`)) {
        self$`deletedOn` <- TrashedEntityObject$`deletedOn`
      }
      if (!is.null(TrashedEntityObject$`entityId`)) {
        self$`entityId` <- TrashedEntityObject$`entityId`
      }
      if (!is.null(TrashedEntityObject$`entityName`)) {
        self$`entityName` <- TrashedEntityObject$`entityName`
      }
      if (!is.null(TrashedEntityObject$`originalParentId`)) {
        self$`originalParentId` <- TrashedEntityObject$`originalParentId`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`deletedByPrincipalId`)) {
        sprintf(
        '"deletedByPrincipalId":
          "%s"
                ',
        self$`deletedByPrincipalId`
        )},
        if (!is.null(self$`deletedOn`)) {
        sprintf(
        '"deletedOn":
          "%s"
                ',
        self$`deletedOn`
        )},
        if (!is.null(self$`entityId`)) {
        sprintf(
        '"entityId":
          "%s"
                ',
        self$`entityId`
        )},
        if (!is.null(self$`entityName`)) {
        sprintf(
        '"entityName":
          "%s"
                ',
        self$`entityName`
        )},
        if (!is.null(self$`originalParentId`)) {
        sprintf(
        '"originalParentId":
          "%s"
                ',
        self$`originalParentId`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(TrashedEntityJson) {
      TrashedEntityObject <- jsonlite::fromJSON(TrashedEntityJson)
      self$`deletedByPrincipalId` <- TrashedEntityObject$`deletedByPrincipalId`
      self$`deletedOn` <- TrashedEntityObject$`deletedOn`
      self$`entityId` <- TrashedEntityObject$`entityId`
      self$`entityName` <- TrashedEntityObject$`entityName`
      self$`originalParentId` <- TrashedEntityObject$`originalParentId`
      self
    }
  )
)
